import Mathlib.Probability.Kernel.Composition.MapComap
import Mathlib.Order.Filter.CountableInter
import StatInference.AsymptoticStatistics.ExperimentLimits

/-!
# van der Vaart 1998 Chapter 10 Bayes procedure interfaces

This module opens the Chapter 10 lane.  The first layer keeps the posterior
objects source-shaped: posterior laws are Markov kernels from observations to
local parameters, Bernstein-von Mises approximation is recorded as convergence
in probability of a scalar posterior-distance display, and Bayes point
estimators are linked back to the Chapter 9 experiment-limit interface.
-/

noncomputable section

namespace StatInference
namespace AsymptoticStatistics

open Filter MeasureTheory ProbabilityTheory
open scoped ENNReal ProbabilityTheory Topology

/--
If a triangular-array statistic is norm-dominated by an `o_{P_n}(1)`
statistic, then it is also `o_{P_n}(1)`.

This is the small probabilistic handoff used below to pass a BvM
posterior-distance bound through posterior functionals.
-/
theorem vaart1998_measureSeqConvergesInProbabilityToZero_of_norm_le
    {Ω E F : Type*} [MeasurableSpace Ω]
    [SeminormedAddCommGroup E] [SeminormedAddCommGroup F]
    {P : ℕ -> Measure Ω} {X : ℕ -> Ω -> E} {Y : ℕ -> Ω -> F}
    [∀ n, IsFiniteMeasure (P n)]
    (hY_le_X : ∀ n ω, ‖Y n ω‖ ≤ ‖X n ω‖)
    (hX : Vaart1998MeasureSeqConvergesInProbabilityToZero P X) :
    Vaart1998MeasureSeqConvergesInProbabilityToZero P Y := by
  intro ε hε
  refine tendsto_of_tendsto_of_tendsto_of_le_of_le
    tendsto_const_nhds (hX ε hε) ?_ ?_
  · intro n
    exact measureReal_nonneg
  · intro n
    refine measureReal_mono ?_
    intro ω hω
    exact le_trans hω (hY_le_X n ω)

/--
The posterior risk at a candidate decision `t`, using a posterior kernel and
an extended nonnegative loss.  This is the Chapter 10 display
`∫ ell(t, h) d posterior_n(h | X_n)`.
-/
def vaart1998_bayesPosteriorRiskAt
    {Ω H T : Type*} [MeasurableSpace Ω] [MeasurableSpace H]
    (posteriorKernel : ℕ -> Kernel Ω H)
    (loss : T -> H -> ℝ≥0∞) (t : T) :
    ℕ -> Ω -> ℝ≥0∞ :=
  fun n ω => ∫⁻ h, loss t h ∂posteriorKernel n ω

/--
The posterior risk of a data-dependent Bayes estimator.
-/
def vaart1998_bayesPosteriorRisk
    {Ω H T : Type*} [MeasurableSpace Ω] [MeasurableSpace H]
    (posteriorKernel : ℕ -> Kernel Ω H)
    (loss : T -> H -> ℝ≥0∞) (estimator : ℕ -> Ω -> T) :
    ℕ -> Ω -> ℝ≥0∞ :=
  fun n ω =>
    vaart1998_bayesPosteriorRiskAt posteriorKernel loss
      (estimator n ω) n ω

/--
The marginal law of the local parameter generated by drawing observations
from the frequentist law and then drawing from the posterior kernel.
-/
def vaart1998_bayesPosteriorMarginalMeasureSeq
    {Ω H : Type*} [MeasurableSpace Ω] [MeasurableSpace H]
    (P : ℕ -> Measure Ω) (posteriorKernel : ℕ -> Kernel Ω H) :
    ℕ -> Measure H :=
  fun n => posteriorKernel n ∘ₘ P n

/--
Markov posterior kernels turn probability observation laws into probability
marginal laws on local parameters.
-/
@[reducible]
def vaart1998_bayesPosteriorMarginalMeasureSeq_isProbabilityMeasure
    {Ω H : Type*} [MeasurableSpace Ω] [MeasurableSpace H]
    {P : ℕ -> Measure Ω} {posteriorKernel : ℕ -> Kernel Ω H}
    [∀ n, IsProbabilityMeasure (P n)]
    (hK : ∀ n, IsMarkovKernel (posteriorKernel n)) :
    ∀ n, IsProbabilityMeasure
      (vaart1998_bayesPosteriorMarginalMeasureSeq P posteriorKernel n) := by
  intro n
  letI : IsMarkovKernel (posteriorKernel n) := hK n
  change IsProbabilityMeasure (posteriorKernel n ∘ₘ P n)
  infer_instance

/--
Chapter 10 posterior-risk minimizer source.

This records that the data-dependent estimator minimizes the posterior risk
pointwise in the observed data.  It is intentionally independent of the
analytic assumptions that prove existence and measurability of such a
minimizer.
-/
structure Vaart1998BayesPosteriorRiskMinimizerSource
    {Ω H T : Type*} [MeasurableSpace Ω] [MeasurableSpace H]
    (posteriorKernel : ℕ -> Kernel Ω H) where
  /-- The loss used to define the Bayes rule. -/
  loss : T -> H -> ℝ≥0∞
  /-- The data-dependent Bayes point estimator. -/
  estimator : ℕ -> Ω -> T
  /-- The estimator minimizes posterior risk at each sample size and observation. -/
  estimator_minimizes_posteriorRisk :
    ∀ n ω t,
      vaart1998_bayesPosteriorRiskAt posteriorKernel loss
        (estimator n ω) n ω ≤
      vaart1998_bayesPosteriorRiskAt posteriorKernel loss t n ω

/--
The posterior-risk optimality certificate carried by a Bayes minimizer source.
-/
theorem Vaart1998BayesPosteriorRiskMinimizerSource.minimizes_posteriorRisk
    {Ω H T : Type*} [MeasurableSpace Ω] [MeasurableSpace H]
    {posteriorKernel : ℕ -> Kernel Ω H}
    (S : Vaart1998BayesPosteriorRiskMinimizerSource
      (T := T) posteriorKernel)
    (n : ℕ) (ω : Ω) (t : T) :
    vaart1998_bayesPosteriorRiskAt posteriorKernel S.loss
      (S.estimator n ω) n ω ≤
    vaart1998_bayesPosteriorRiskAt posteriorKernel S.loss t n ω :=
  S.estimator_minimizes_posteriorRisk n ω t

/--
Chapter 10 Bernstein-von Mises posterior approximation source.

The field `posteriorApproxDistance` is the textbook random distance between
the rescaled posterior law and its Gaussian random approximation, typically
the total variation distance in Theorem 10.1.
-/
structure Vaart1998BvMPosteriorApproximationSource
    {Ω H : Type*} [MeasurableSpace Ω] [MeasurableSpace H]
    (P : ℕ -> Measure Ω) [∀ n, IsProbabilityMeasure (P n)] where
  /-- Posterior laws of the rescaled local parameter given the data. -/
  posteriorKernel : ℕ -> Kernel Ω H
  /-- Gaussian random posterior laws used in the BvM approximation. -/
  gaussianPosteriorKernel : ℕ -> Kernel Ω H
  /-- Posterior laws are Markov kernels. -/
  posteriorKernel_isMarkov : ∀ n, IsMarkovKernel (posteriorKernel n)
  /-- Gaussian approximating laws are Markov kernels. -/
  gaussianPosteriorKernel_isMarkov :
    ∀ n, IsMarkovKernel (gaussianPosteriorKernel n)
  /-- Random posterior-approximation distance, e.g. total variation. -/
  posteriorApproxDistance : ℕ -> Ω -> ℝ
  /-- The approximation distance is nonnegative. -/
  posteriorApproxDistance_nonneg :
    ∀ n ω, 0 ≤ posteriorApproxDistance n ω
  /-- Bernstein-von Mises convergence in frequentist probability. -/
  posteriorApproxDistance_convergesInProbability :
    Vaart1998MeasureSeqConvergesInProbabilityToZero P
      posteriorApproxDistance

/--
The BvM convergence-in-probability certificate carried by a posterior
approximation source.
-/
theorem Vaart1998BvMPosteriorApproximationSource.convergesInProbability
    {Ω H : Type*} [MeasurableSpace Ω] [MeasurableSpace H]
    {P : ℕ -> Measure Ω} [∀ n, IsProbabilityMeasure (P n)]
    (S : Vaart1998BvMPosteriorApproximationSource (H := H) P) :
    Vaart1998MeasureSeqConvergesInProbabilityToZero P
      S.posteriorApproxDistance :=
  S.posteriorApproxDistance_convergesInProbability

/--
The BvM posterior approximation distance is stochastically bounded.
-/
theorem Vaart1998BvMPosteriorApproximationSource.posteriorApproxDistance_stochasticallyBounded
    {Ω H : Type*} [MeasurableSpace Ω] [MeasurableSpace H]
    {P : ℕ -> Measure Ω} [∀ n, IsProbabilityMeasure (P n)]
    (S : Vaart1998BvMPosteriorApproximationSource (H := H) P) :
    Vaart1998MeasureSeqStochasticBounded P S.posteriorApproxDistance :=
  vaart1998_measureSeqStochasticBounded_of_convergesInProbabilityToZero
    S.posteriorApproxDistance_convergesInProbability

/--
The marginal law of the local parameter induced by a BvM posterior source.
-/
def Vaart1998BvMPosteriorApproximationSource.posteriorMarginalMeasureSeq
    {Ω H : Type*} [MeasurableSpace Ω] [MeasurableSpace H]
    {P : ℕ -> Measure Ω} [∀ n, IsProbabilityMeasure (P n)]
    (S : Vaart1998BvMPosteriorApproximationSource (H := H) P) :
    ℕ -> Measure H :=
  vaart1998_bayesPosteriorMarginalMeasureSeq P S.posteriorKernel

/--
The Gaussian marginal law induced by a BvM posterior source.
-/
def Vaart1998BvMPosteriorApproximationSource.gaussianPosteriorMarginalMeasureSeq
    {Ω H : Type*} [MeasurableSpace Ω] [MeasurableSpace H]
    {P : ℕ -> Measure Ω} [∀ n, IsProbabilityMeasure (P n)]
    (S : Vaart1998BvMPosteriorApproximationSource (H := H) P) :
    ℕ -> Measure H :=
  vaart1998_bayesPosteriorMarginalMeasureSeq P
    S.gaussianPosteriorKernel

/--
The posterior marginal law sequence in a BvM source is a sequence of
probability measures.
-/
@[reducible]
def Vaart1998BvMPosteriorApproximationSource.posteriorMarginal_isProbabilityMeasure
    {Ω H : Type*} [MeasurableSpace Ω] [MeasurableSpace H]
    {P : ℕ -> Measure Ω} [∀ n, IsProbabilityMeasure (P n)]
    (S : Vaart1998BvMPosteriorApproximationSource (H := H) P) :
    ∀ n, IsProbabilityMeasure
      (S.posteriorMarginalMeasureSeq (H := H) n) :=
  vaart1998_bayesPosteriorMarginalMeasureSeq_isProbabilityMeasure
    (P := P) (posteriorKernel := S.posteriorKernel)
    S.posteriorKernel_isMarkov

/--
The Gaussian approximating marginal law sequence in a BvM source is a
sequence of probability measures.
-/
@[reducible]
def Vaart1998BvMPosteriorApproximationSource.gaussianPosteriorMarginal_isProbabilityMeasure
    {Ω H : Type*} [MeasurableSpace Ω] [MeasurableSpace H]
    {P : ℕ -> Measure Ω} [∀ n, IsProbabilityMeasure (P n)]
    (S : Vaart1998BvMPosteriorApproximationSource (H := H) P) :
    ∀ n, IsProbabilityMeasure
      (S.gaussianPosteriorMarginalMeasureSeq (H := H) n) :=
  vaart1998_bayesPosteriorMarginalMeasureSeq_isProbabilityMeasure
    (P := P) (posteriorKernel := S.gaussianPosteriorKernel)
    S.gaussianPosteriorKernel_isMarkov

/--
Rejection set built from a uniformly consistent estimator.

For testing `H₀ : θ = θ0` against alternatives at distance at least
`epsilon`, the Chapter 10 reduction rejects when the estimator is at least
`epsilon / 2` away from `theta0`.
-/
def vaart1998_bayesEstimatorSeparationTestSet
    {Ω Θ : Type*} [PseudoMetricSpace Θ]
    (estimator : ℕ -> Ω -> Θ) (theta0 : Θ) (epsilon : ℝ) :
    ℕ -> Set Ω :=
  fun n => {ω | epsilon / 2 ≤ dist (estimator n ω) theta0}

/--
Chapter 10 source for uniformly consistent estimators.

This is the estimator-side hypothesis used before Lemmas 10.4 and 10.6:
uniformly over a parameter set, the estimator error probability is bounded by
a deterministic radius that tends to zero.
-/
structure Vaart1998BayesUniformEstimatorConsistencySource
    {Ω Θ : Type*} [MeasurableSpace Ω] [PseudoMetricSpace Θ]
    (P : Θ -> ℕ -> Measure Ω) where
  /-- Parameters over which the consistency statement is uniform. -/
  parameterSet : Set Θ
  /-- Estimator sequence `T_n`. -/
  estimator : ℕ -> Ω -> Θ
  /-- Deterministic uniform error-probability bound. -/
  errorBound : ℝ -> ℕ -> ℝ
  /-- The error bound tends to zero for every positive radius. -/
  errorBound_tendsto_zero :
    ∀ ε : ℝ, 0 < ε -> Tendsto (errorBound ε) atTop (𝓝 0)
  /-- Uniform consistency on the parameter set. -/
  estimator_error_probability_le :
    ∀ ε : ℝ, 0 < ε -> ∀ n θ, θ ∈ parameterSet ->
      (P θ n).real {ω | ε ≤ dist (estimator n ω) θ} ≤
        errorBound ε n

/--
Chapter 10 uniformly consistent separating tests.

The test set `testSet epsilon n` represents the rejection region in (10.2)
for testing `θ = theta0` against alternatives at distance at least `epsilon`.
-/
structure Vaart1998BayesUniformTestSeparationSource
    {Ω Θ : Type*} [MeasurableSpace Ω] [PseudoMetricSpace Θ]
    (P : Θ -> ℕ -> Measure Ω) (theta0 : Θ) where
  /-- Alternatives are measured inside this parameter set. -/
  parameterSet : Set Θ
  /-- The null parameter belongs to the parameter set. -/
  theta0_mem : theta0 ∈ parameterSet
  /-- Rejection regions for each separation radius and sample size. -/
  testSet : ℝ -> ℕ -> Set Ω
  /-- Deterministic bound on the null rejection probability. -/
  sizeBound : ℝ -> ℕ -> ℝ
  /-- Deterministic bound on the worst alternative non-rejection probability. -/
  missBound : ℝ -> ℕ -> ℝ
  /-- Null rejection probabilities tend to zero. -/
  sizeBound_tendsto_zero :
    ∀ ε : ℝ, 0 < ε -> Tendsto (sizeBound ε) atTop (𝓝 0)
  /-- Alternative non-rejection probabilities tend to zero. -/
  missBound_tendsto_zero :
    ∀ ε : ℝ, 0 < ε -> Tendsto (missBound ε) atTop (𝓝 0)
  /-- The test has asymptotically vanishing size at `theta0`. -/
  size_probability_le :
    ∀ ε : ℝ, 0 < ε -> ∀ n,
      (P theta0 n).real (testSet ε n) ≤ sizeBound ε n
  /-- The test has asymptotically vanishing worst miss probability. -/
  miss_probability_le :
    ∀ ε : ℝ, 0 < ε -> ∀ n θ, θ ∈ parameterSet ->
      ε ≤ dist θ theta0 ->
        (P θ n).real ((testSet ε n)ᶜ) ≤ missBound ε n

/--
The null rejection bound carried by a Chapter 10 separating-test source.
-/
theorem Vaart1998BayesUniformTestSeparationSource.size_tendsto_zero
    {Ω Θ : Type*} [MeasurableSpace Ω] [PseudoMetricSpace Θ]
    {P : Θ -> ℕ -> Measure Ω} {theta0 : Θ}
    (S : Vaart1998BayesUniformTestSeparationSource P theta0)
    (ε : ℝ) (hε : 0 < ε) :
    Tendsto (S.sizeBound ε) atTop (𝓝 0) :=
  S.sizeBound_tendsto_zero ε hε

/--
The alternative non-rejection bound carried by a Chapter 10 separating-test
source.
-/
theorem Vaart1998BayesUniformTestSeparationSource.miss_tendsto_zero
    {Ω Θ : Type*} [MeasurableSpace Ω] [PseudoMetricSpace Θ]
    {P : Θ -> ℕ -> Measure Ω} {theta0 : Θ}
    (S : Vaart1998BayesUniformTestSeparationSource P theta0)
    (ε : ℝ) (hε : 0 < ε) :
    Tendsto (S.missBound ε) atTop (𝓝 0) :=
  S.missBound_tendsto_zero ε hε

/--
Uniformly consistent estimators give uniformly consistent tests separating
`theta0` from every fixed complement of a ball around `theta0`.

This is the triangle-inequality reduction immediately preceding Lemma 10.4:
reject when `dist (T_n, theta0) ≥ epsilon / 2`.
-/
def Vaart1998BayesUniformEstimatorConsistencySource.testSeparationSource
    {Ω Θ : Type*} [MeasurableSpace Ω] [PseudoMetricSpace Θ]
    {P : Θ -> ℕ -> Measure Ω} [∀ θ n, IsFiniteMeasure (P θ n)]
    (S : Vaart1998BayesUniformEstimatorConsistencySource P)
    (theta0 : Θ) (htheta0 : theta0 ∈ S.parameterSet) :
    Vaart1998BayesUniformTestSeparationSource P theta0 :=
  { parameterSet := S.parameterSet
    theta0_mem := htheta0
    testSet :=
      fun ε =>
        vaart1998_bayesEstimatorSeparationTestSet
          S.estimator theta0 ε
    sizeBound := fun ε n => S.errorBound (ε / 2) n
    missBound := fun ε n => S.errorBound (ε / 2) n
    sizeBound_tendsto_zero := by
      intro ε hε
      exact S.errorBound_tendsto_zero (ε / 2) (by nlinarith)
    missBound_tendsto_zero := by
      intro ε hε
      exact S.errorBound_tendsto_zero (ε / 2) (by nlinarith)
    size_probability_le := by
      intro ε hε n
      exact S.estimator_error_probability_le (ε / 2) (by nlinarith)
        n theta0 htheta0
    miss_probability_le := by
      intro ε hε n θ hθ hsep
      calc
        (P θ n).real
            (((vaart1998_bayesEstimatorSeparationTestSet
              S.estimator theta0 ε) n)ᶜ)
            ≤ (P θ n).real
                {ω | ε / 2 ≤ dist (S.estimator n ω) θ} := by
              refine measureReal_mono ?_
              intro ω hω
              change ¬ ε / 2 ≤ dist (S.estimator n ω) theta0 at hω
              have hlt : dist (S.estimator n ω) theta0 < ε / 2 :=
                lt_of_not_ge hω
              have htri :
                  dist θ theta0 ≤
                    dist θ (S.estimator n ω) +
                      dist (S.estimator n ω) theta0 :=
                dist_triangle θ (S.estimator n ω) theta0
              have hhalf : ε / 2 < dist θ (S.estimator n ω) := by
                nlinarith
              have hdist : ε / 2 < dist (S.estimator n ω) θ := by
                simpa [dist_comm] using hhalf
              exact le_of_lt hdist
        _ ≤ S.errorBound (ε / 2) n :=
              S.estimator_error_probability_le (ε / 2) (by nlinarith)
                n θ hθ }

/--
Source-shaped form of Lemma 10.4.

The fields record the uniform Glivenko-Cantelli estimator route and the
display (10.5) separation condition.  The resulting estimator consistency
source can be converted into the separating tests required by Theorem 10.1.
-/
structure Vaart1998BayesLemma10_4UniformGCConsistencySource
    {Ω Θ : Type*} [MeasurableSpace Ω] [PseudoMetricSpace Θ]
    (P : Θ -> ℕ -> Measure Ω) where
  /-- Uniform estimator consistency obtained from the GC minimum-distance construction. -/
  estimatorSource : Vaart1998BayesUniformEstimatorConsistencySource P
  /-- Model discrepancy `‖P_θ - P_θ'‖_𝓕` from display (10.5). -/
  modelDiscrepancy : Θ -> Θ -> ℝ
  /-- The discrepancy is nonnegative. -/
  modelDiscrepancy_nonneg : ∀ θ θ', 0 ≤ modelDiscrepancy θ θ'
  /-- Display (10.5), written with a supplied positive lower bound. -/
  separation_10_5 :
    ∀ ε : ℝ, 0 < ε ->
      ∃ δ : ℝ, 0 < δ ∧
        ∀ θ θ', θ ∈ estimatorSource.parameterSet ->
          θ' ∈ estimatorSource.parameterSet ->
            ε < dist θ θ' -> δ ≤ modelDiscrepancy θ θ'

/--
Lemma 10.4 supplies the separating tests required by the BvM hypothesis once
the null parameter is in the uniform-consistency parameter set.
-/
def Vaart1998BayesLemma10_4UniformGCConsistencySource.testSeparationSource
    {Ω Θ : Type*} [MeasurableSpace Ω] [PseudoMetricSpace Θ]
    {P : Θ -> ℕ -> Measure Ω} [∀ θ n, IsFiniteMeasure (P θ n)]
    (S : Vaart1998BayesLemma10_4UniformGCConsistencySource P)
    (theta0 : Θ) (htheta0 : theta0 ∈ S.estimatorSource.parameterSet) :
    Vaart1998BayesUniformTestSeparationSource P theta0 :=
  S.estimatorSource.testSeparationSource theta0 htheta0

/--
Source-shaped form of Lemma 10.6.

It records the compact-subset consistency conclusion obtained from
identifiability and total-variation continuity on a sigma-compact parameter
space.
-/
structure Vaart1998BayesLemma10_6CompactUniformConsistencySource
    {Ω Θ : Type*} [MeasurableSpace Ω] [PseudoMetricSpace Θ]
    (P : Θ -> ℕ -> Measure Ω) where
  /-- Compact subset on which the estimator is uniformly consistent. -/
  compactParameterSet : Set Θ
  /-- Uniform estimator consistency on a parameter set containing the compact set. -/
  estimatorSource : Vaart1998BayesUniformEstimatorConsistencySource P
  /-- The compact set is covered by the estimator consistency source. -/
  compact_subset_parameterSet :
    compactParameterSet ⊆ estimatorSource.parameterSet
  /-- Identifiability of the model, as used in Lemma 10.6. -/
  identifiable : Prop
  /-- Continuity of `θ ↦ P_θ` in total variation, as used in Lemma 10.6. -/
  totalVariation_continuous : Prop

/--
Lemma 10.6 supplies separating tests on every compact subset once a null
parameter in that compact set is fixed.
-/
def Vaart1998BayesLemma10_6CompactUniformConsistencySource.testSeparationSource
    {Ω Θ : Type*} [MeasurableSpace Ω] [PseudoMetricSpace Θ]
    {P : Θ -> ℕ -> Measure Ω} [∀ θ n, IsFiniteMeasure (P θ n)]
    (S : Vaart1998BayesLemma10_6CompactUniformConsistencySource P)
    (theta0 : Θ) (htheta0 : theta0 ∈ S.compactParameterSet) :
    Vaart1998BayesUniformTestSeparationSource P theta0 :=
  S.estimatorSource.testSeparationSource theta0
    (S.compact_subset_parameterSet htheta0)

/--
Posterior consistency at one parameter, represented by a real-valued
posterior weak-distance display that is `o_{P_θ^\infty}(1)`.
-/
structure Vaart1998BayesPosteriorConsistencyAtSource
    {Ω Θ : Type*} [MeasurableSpace Ω] [MeasurableSpace Θ]
    (PthetaInfinite : Measure Ω) (posteriorKernel : ℕ -> Kernel Ω Θ)
    (theta : Θ) where
  /-- Real display of posterior weak distance to `δ_theta`. -/
  posteriorConsistencyDistance : ℕ -> Ω -> ℝ
  /-- The displayed distance is nonnegative. -/
  posteriorConsistencyDistance_nonneg :
    ∀ n ω, 0 ≤ posteriorConsistencyDistance n ω
  /-- Posterior consistency in probability under `P_θ^\infty`. -/
  posteriorConsistencyDistance_convergesInProbability :
    Vaart1998MeasureSeqConvergesInProbabilityToZero
      (fun _ : ℕ => PthetaInfinite) posteriorConsistencyDistance

/--
The posterior consistency certificate at one parameter.
-/
theorem Vaart1998BayesPosteriorConsistencyAtSource.convergesInProbability
    {Ω Θ : Type*} [MeasurableSpace Ω] [MeasurableSpace Θ]
    {PthetaInfinite : Measure Ω} {posteriorKernel : ℕ -> Kernel Ω Θ}
    {theta : Θ}
    (S : Vaart1998BayesPosteriorConsistencyAtSource
      PthetaInfinite posteriorKernel theta) :
    Vaart1998MeasureSeqConvergesInProbabilityToZero
      (fun _ : ℕ => PthetaInfinite)
      S.posteriorConsistencyDistance :=
  S.posteriorConsistencyDistance_convergesInProbability

/--
Doob's consistency theorem, source-shaped.

The theorem gives posterior consistency for a prior-a.e. set of parameters.
The analytic proof builds the recovery map from the infinite sample and then
uses Doob martingale convergence; this source records the resulting
parameterwise consistency certificates and the prior-a.e. conclusion.
-/
structure Vaart1998BayesDoobConsistencySource
    {Ω Θ : Type*} [MeasurableSpace Ω] [MeasurableSpace Θ]
    (prior : Measure Θ) where
  /-- Infinite-sample laws `P_θ^∞`. -/
  sampleLawInfinite : Θ -> Measure Ω
  /-- Posterior kernels based on the first `n` observations. -/
  posteriorKernel : ℕ -> Kernel Ω Θ
  /-- Posterior kernels are Markov kernels. -/
  posteriorKernel_isMarkov : ∀ n, IsMarkovKernel (posteriorKernel n)
  /-- Identifiability assumption `P_θ ≠ P_θ'` for `θ ≠ θ'`. -/
  identifiable : ∀ θ θ', θ ≠ θ' -> sampleLawInfinite θ ≠ sampleLawInfinite θ'
  /-- Parameters at which posterior consistency holds. -/
  consistentSet : Set Θ
  /-- Doob consistency holds for prior-a.e. parameter. -/
  consistentSet_ae_prior : ∀ᵐ θ ∂prior, θ ∈ consistentSet
  /-- Parameterwise posterior consistency certificates. -/
  consistencyAtSource :
    ∀ θ, θ ∈ consistentSet ->
      Vaart1998BayesPosteriorConsistencyAtSource
        (sampleLawInfinite θ) posteriorKernel θ

/--
The prior-a.e. consistency conclusion carried by a Doob source.
-/
theorem Vaart1998BayesDoobConsistencySource.consistent_ae
    {Ω Θ : Type*} [MeasurableSpace Ω] [MeasurableSpace Θ]
    {prior : Measure Θ}
    (S : Vaart1998BayesDoobConsistencySource
      (Ω := Ω) (Θ := Θ) prior) :
    ∀ᵐ θ ∂prior, θ ∈ S.consistentSet :=
  S.consistentSet_ae_prior

/--
At every parameter in the Doob consistency set, the posterior weak-distance
display converges to zero in probability under `P_θ^∞`.
-/
theorem Vaart1998BayesDoobConsistencySource.convergesInProbability_of_mem
    {Ω Θ : Type*} [MeasurableSpace Ω] [MeasurableSpace Θ]
    {prior : Measure Θ}
    (S : Vaart1998BayesDoobConsistencySource
      (Ω := Ω) (Θ := Θ) prior)
    (theta : Θ) (htheta : theta ∈ S.consistentSet) :
    Vaart1998MeasureSeqConvergesInProbabilityToZero
      (fun _ : ℕ => S.sampleLawInfinite theta)
      (S.consistencyAtSource theta htheta).posteriorConsistencyDistance :=
  (S.consistencyAtSource theta htheta).convergesInProbability

/--
Coordinate cylinder sets generated by a countable family of real-valued
measurable functions.  This is the concrete sigma-field generator in
Lemma 10.12.
-/
def vaart1998_bayesCoordinateCylinder
    {Θ ι : Type*} (coordinate : ι -> Θ -> ℝ) :
    Set (Set Θ) :=
  {A | ∃ i B, MeasurableSet B ∧ A = {θ | coordinate i θ ∈ B}}

/--
Source-shaped form of Lemma 10.12.

A countable measurable family separates points of the Euclidean parameter
space, and its coordinate cylinders generate the Borel sigma-field.
-/
structure Vaart1998BayesLemma10_12MeasurableSeparationSource
    (Θ ι : Type*) [MeasurableSpace Θ] where
  /-- Countable coordinate family `f ∈ 𝓕`. -/
  coordinate : ι -> Θ -> ℝ
  /-- The family is countable. -/
  index_countable : Countable ι
  /-- Every coordinate is measurable. -/
  coordinate_measurable : ∀ i, Measurable (coordinate i)
  /-- The coordinates separate the points of `Θ`. -/
  separates_points :
    ∀ {θ θ' : Θ}, (∀ i, coordinate i θ = coordinate i θ') -> θ = θ'
  /--
  Lemma 10.12 conclusion: the ambient Borel/measurable sigma-field is the
  sigma-field generated by the coordinate cylinders.
  -/
  borel_eq_generated_by_coordinates :
    ∀ A : Set Θ,
      MeasurableSet A ↔
        @MeasurableSet Θ
          (MeasurableSpace.generateFrom
            (vaart1998_bayesCoordinateCylinder coordinate)) A

/--
The coordinate map associated with a Lemma 10.12 source.
-/
def Vaart1998BayesLemma10_12MeasurableSeparationSource.coordinateMap
    {Θ ι : Type*} [MeasurableSpace Θ]
    (S : Vaart1998BayesLemma10_12MeasurableSeparationSource Θ ι) :
    Θ -> ι -> ℝ :=
  fun θ i => S.coordinate i θ

/--
The coordinate map in Lemma 10.12 is injective because the family separates
points.
-/
theorem Vaart1998BayesLemma10_12MeasurableSeparationSource.coordinateMap_injective
    {Θ ι : Type*} [MeasurableSpace Θ]
    (S : Vaart1998BayesLemma10_12MeasurableSeparationSource Θ ι) :
    Function.Injective S.coordinateMap := by
  intro θ θ' hθ
  exact S.separates_points (fun i => congrFun hθ i)

/--
The generated-sigma-field conclusion carried by a Lemma 10.12 source.
-/
theorem Vaart1998BayesLemma10_12MeasurableSeparationSource.generated_borel_eq
    {Θ ι : Type*} [MeasurableSpace Θ]
    (S : Vaart1998BayesLemma10_12MeasurableSeparationSource Θ ι)
    (A : Set Θ) :
    MeasurableSet A ↔
      @MeasurableSet Θ
        (MeasurableSpace.generateFrom
          (vaart1998_bayesCoordinateCylinder S.coordinate)) A :=
  S.borel_eq_generated_by_coordinates A

/--
Source-shaped form of Lemma 10.13.

The accessible functions form the monotone class used in Doob's theorem.
The conclusion field is the monotone-class theorem: every integrable function
measurable with respect to the generated sigma-field is accessible.
-/
structure Vaart1998BayesLemma10_13MonotoneClassSource
    {Θ : Type*} [MeasurableSpace Θ] (prior : Measure Θ) where
  /-- The accessible real-valued functions in Doob's proof. -/
  accessible : (Θ -> ℝ) -> Prop
  /-- Accessible functions form a linear space. -/
  add_mem :
    ∀ {f g : Θ -> ℝ}, accessible f -> accessible g ->
      accessible (fun θ => f θ + g θ)
  /-- Accessible functions are closed under additive inverse. -/
  neg_mem :
    ∀ {f : Θ -> ℝ}, accessible f -> accessible (fun θ => -f θ)
  /-- Accessible functions are closed under pointwise minimum. -/
  inf_mem :
    ∀ {f g : Θ -> ℝ}, accessible f -> accessible g ->
      accessible (fun θ => min (f θ) (g θ))
  /-- Accessible functions are closed under integrable monotone limits. -/
  monotone_limit_mem :
    ∀ {u : ℕ -> Θ -> ℝ} {f : Θ -> ℝ},
      (∀ n, accessible (u n)) ->
        (∀ n θ, u n θ ≤ u (n + 1) θ) ->
          (∀ θ, Tendsto (fun n => u n θ) atTop (𝓝 (f θ))) ->
            Integrable f prior -> accessible f
  /-- The constant-one function is accessible. -/
  one_mem : accessible (fun _ : Θ => 1)
  /--
  Lemma 10.13 conclusion: every integrable function measurable in the
  generated sigma-field is accessible.
  -/
  sigma_measurable_integrable_mem :
    ∀ {f : Θ -> ℝ}, Measurable f -> Integrable f prior -> accessible f

/--
The constant-one function is accessible in a Lemma 10.13 source.
-/
theorem Vaart1998BayesLemma10_13MonotoneClassSource.one_accessible
    {Θ : Type*} [MeasurableSpace Θ] {prior : Measure Θ}
    (S : Vaart1998BayesLemma10_13MonotoneClassSource prior) :
    S.accessible (fun _ : Θ => 1) :=
  S.one_mem

/--
Lemma 10.13 handoff: measurable integrable functions are accessible.
-/
theorem Vaart1998BayesLemma10_13MonotoneClassSource.contains_sigma_measurable
    {Θ : Type*} [MeasurableSpace Θ] {prior : Measure Θ}
    (S : Vaart1998BayesLemma10_13MonotoneClassSource prior)
    {f : Θ -> ℝ} (hf : Measurable f) (hfi : Integrable f prior) :
    S.accessible f :=
  S.sigma_measurable_integrable_mem hf hfi

/--
The coordinate functions from Lemma 10.12 are accessible once Lemma 10.13 is
available and the coordinates are integrable under the prior.
-/
theorem Vaart1998BayesLemma10_12MeasurableSeparationSource.coordinate_accessible
    {Θ ι : Type*} [MeasurableSpace Θ] {prior : Measure Θ}
    (S : Vaart1998BayesLemma10_12MeasurableSeparationSource Θ ι)
    (M : Vaart1998BayesLemma10_13MonotoneClassSource prior)
    (i : ι) (hi : Integrable (S.coordinate i) prior) :
    M.accessible (S.coordinate i) :=
  M.contains_sigma_measurable (S.coordinate_measurable i) hi

/--
Doob recovery-map source.

This records display (10.11): the infinite sample determines the parameter
almost surely under the joint law.
-/
structure Vaart1998BayesDoobRecoveryMapSource
    {Ω Θ : Type*} [MeasurableSpace Ω] [MeasurableSpace Θ]
    (jointLaw : Measure (Ω × Θ)) where
  /-- Measurable recovery map `h : X^∞ -> Θ`. -/
  recoveryMap : Ω -> Θ
  /-- The recovery map is measurable. -/
  recoveryMap_measurable : Measurable recoveryMap
  /-- Display (10.11): `h(X_1, X_2, ...) = θ` almost surely. -/
  recovery_eq_parameter_ae :
    ∀ᵐ z ∂jointLaw, recoveryMap z.1 = z.2

/--
The almost-sure recovery statement carried by a Doob recovery-map source.
-/
theorem Vaart1998BayesDoobRecoveryMapSource.recovery_eq_parameter
    {Ω Θ : Type*} [MeasurableSpace Ω] [MeasurableSpace Θ]
    {jointLaw : Measure (Ω × Θ)}
    (S : Vaart1998BayesDoobRecoveryMapSource jointLaw) :
    ∀ᵐ z ∂jointLaw, S.recoveryMap z.1 = z.2 :=
  S.recovery_eq_parameter_ae

/--
Doob recovery route assembled from Lemmas 10.12 and 10.13.

The source records the countable separating family, the monotone-class
closure of accessible functions, integrability of the coordinates, and the
resulting recovery-map display.
-/
structure Vaart1998BayesDoobRecoveryRouteSource
    {Ω Θ ι : Type*} [MeasurableSpace Ω] [MeasurableSpace Θ]
    (prior : Measure Θ) where
  /-- Lemma 10.12 measurable separating family. -/
  measurableSeparationSource :
    Vaart1998BayesLemma10_12MeasurableSeparationSource Θ ι
  /-- Lemma 10.13 monotone-class source for accessible functions. -/
  monotoneClassSource :
    Vaart1998BayesLemma10_13MonotoneClassSource prior
  /-- Integrability of each separating coordinate. -/
  coordinate_integrable :
    ∀ i, Integrable (measurableSeparationSource.coordinate i) prior
  /-- Joint law of infinite sample and parameter. -/
  jointLaw : Measure (Ω × Θ)
  /-- Recovery map supplied by the Doob proof. -/
  recoveryMapSource :
    Vaart1998BayesDoobRecoveryMapSource jointLaw

/--
Every separating coordinate in a Doob recovery route is accessible.
-/
theorem Vaart1998BayesDoobRecoveryRouteSource.coordinate_accessible
    {Ω Θ ι : Type*} [MeasurableSpace Ω] [MeasurableSpace Θ]
    {prior : Measure Θ}
    (S : Vaart1998BayesDoobRecoveryRouteSource
      (Ω := Ω) (Θ := Θ) (ι := ι) prior)
    (i : ι) :
    S.monotoneClassSource.accessible
      (S.measurableSeparationSource.coordinate i) :=
  S.measurableSeparationSource.coordinate_accessible
    S.monotoneClassSource i (S.coordinate_integrable i)

/--
The recovery-map display carried by a Doob recovery route.
-/
theorem Vaart1998BayesDoobRecoveryRouteSource.recovery_eq_parameter
    {Ω Θ ι : Type*} [MeasurableSpace Ω] [MeasurableSpace Θ]
    {prior : Measure Θ}
    (S : Vaart1998BayesDoobRecoveryRouteSource
      (Ω := Ω) (Θ := Θ) (ι := ι) prior) :
    ∀ᵐ z ∂S.jointLaw, S.recoveryMapSource.recoveryMap z.1 = z.2 :=
  S.recoveryMapSource.recovery_eq_parameter

/--
Doob consistency route with the recovery-map construction attached to the
posterior-consistency conclusion.
-/
structure Vaart1998BayesDoobConsistencyRouteSource
    {Ω Θ ι : Type*} [MeasurableSpace Ω] [MeasurableSpace Θ]
    (prior : Measure Θ) where
  /-- The final Doob prior-a.e. posterior-consistency source. -/
  doobSource : Vaart1998BayesDoobConsistencySource
    (Ω := Ω) (Θ := Θ) prior
  /-- The Lemma 10.12/10.13 recovery-map route used in the proof. -/
  recoveryRouteSource :
    Vaart1998BayesDoobRecoveryRouteSource
      (Ω := Ω) (Θ := Θ) (ι := ι) prior

/--
The final Doob source carried by the expanded consistency route.
-/
def Vaart1998BayesDoobConsistencyRouteSource.doobConsistencySource
    {Ω Θ ι : Type*} [MeasurableSpace Ω] [MeasurableSpace Θ]
    {prior : Measure Θ}
    (S : Vaart1998BayesDoobConsistencyRouteSource
      (Ω := Ω) (Θ := Θ) (ι := ι) prior) :
    Vaart1998BayesDoobConsistencySource (Ω := Ω) (Θ := Θ) prior :=
  S.doobSource

/--
The prior-a.e. consistency conclusion from the expanded Doob route.
-/
theorem Vaart1998BayesDoobConsistencyRouteSource.consistent_ae
    {Ω Θ ι : Type*} [MeasurableSpace Ω] [MeasurableSpace Θ]
    {prior : Measure Θ}
    (S : Vaart1998BayesDoobConsistencyRouteSource
      (Ω := Ω) (Θ := Θ) (ι := ι) prior) :
    ∀ᵐ θ ∂prior, θ ∈ S.doobSource.consistentSet :=
  S.doobSource.consistent_ae

/--
Countable determining class used after Doob martingale convergence.

This is the Lemma 2.25 input in the proof of Theorem 10.10: a countable
family of bounded continuous test functions determines weak convergence.
-/
structure Vaart1998BayesDoobCountableDeterminingClassSource
    (Θ κ : Type*) [MeasurableSpace Θ] where
  /-- Determining test functions. -/
  testFunction : κ -> Θ -> ℝ
  /-- The determining class is countable. -/
  index_countable : Countable κ
  /-- Test functions are measurable. -/
  testFunction_measurable : ∀ k, Measurable (testFunction k)
  /-- Boundedness certificate for each test function. -/
  testFunction_bounded : ∀ k, ∃ C : ℝ, 0 ≤ C ∧ ∀ θ, ‖testFunction k θ‖ ≤ C
  /-- Continuity/bounded-continuity certificate, kept source-shaped. -/
  testFunction_continuous : Prop
  /-- The family determines weak convergence of probability measures. -/
  determines_weak_convergence : Prop

/--
Doob martingale convergence source for a countable determining class.

For each determining test function `f`, the posterior integral
`E(f(Theta) | X_1, ..., X_n)` converges almost surely to `f(h(X_1, X_2, ...))`.
-/
structure Vaart1998BayesDoobMartingaleConvergenceSource
    {Ω Θ κ : Type*} [MeasurableSpace Ω] [MeasurableSpace Θ]
    (jointLaw : Measure (Ω × Θ)) (posteriorKernel : ℕ -> Kernel Ω Θ)
    (recoveryMap : Ω -> Θ) where
  /-- Countable determining family of test functions. -/
  determiningClass :
    Vaart1998BayesDoobCountableDeterminingClassSource Θ κ
  /-- Posterior integral display for each test function. -/
  posteriorIntegral : κ -> ℕ -> Ω -> ℝ
  /-- Infinite-sample conditional expectation display. -/
  recoveryIntegral : κ -> Ω -> ℝ
  /-- The infinite-sample display equals evaluation at the recovery map. -/
  recoveryIntegral_eq_testFunction :
    ∀ k, ∀ᵐ z ∂jointLaw,
      recoveryIntegral k z.1 =
        determiningClass.testFunction k (recoveryMap z.1)
  /-- Doob martingale convergence for each determining test function. -/
  martingale_tendsto :
    ∀ k, ∀ᵐ z ∂jointLaw,
      Tendsto (fun n => posteriorIntegral k n z.1) atTop
        (𝓝 (recoveryIntegral k z.1))

/--
The Doob martingale convergence holds simultaneously for all functions in
the countable determining class.
-/
theorem Vaart1998BayesDoobMartingaleConvergenceSource.martingale_tendsto_all
    {Ω Θ κ : Type*} [MeasurableSpace Ω] [MeasurableSpace Θ]
    {jointLaw : Measure (Ω × Θ)} {posteriorKernel : ℕ -> Kernel Ω Θ}
    {recoveryMap : Ω -> Θ}
    (S : Vaart1998BayesDoobMartingaleConvergenceSource
      (κ := κ) jointLaw posteriorKernel recoveryMap) :
    ∀ᵐ z ∂jointLaw, ∀ k : κ,
      Tendsto (fun n => S.posteriorIntegral k n z.1) atTop
        (𝓝 (S.recoveryIntegral k z.1)) := by
  letI : Countable κ := S.determiningClass.index_countable
  exact eventually_countable_forall.2 S.martingale_tendsto

/--
The recovery-integral equality holds simultaneously for all functions in the
countable determining class.
-/
theorem Vaart1998BayesDoobMartingaleConvergenceSource.recoveryIntegral_eq_all
    {Ω Θ κ : Type*} [MeasurableSpace Ω] [MeasurableSpace Θ]
    {jointLaw : Measure (Ω × Θ)} {posteriorKernel : ℕ -> Kernel Ω Θ}
    {recoveryMap : Ω -> Θ}
    (S : Vaart1998BayesDoobMartingaleConvergenceSource
      (κ := κ) jointLaw posteriorKernel recoveryMap) :
    ∀ᵐ z ∂jointLaw, ∀ k : κ,
      S.recoveryIntegral k z.1 =
        S.determiningClass.testFunction k (recoveryMap z.1) := by
  letI : Countable κ := S.determiningClass.index_countable
  exact eventually_countable_forall.2 S.recoveryIntegral_eq_testFunction

/--
Doob martingale convergence rewritten with the limiting test-function value
at the recovery map.
-/
theorem Vaart1998BayesDoobMartingaleConvergenceSource.martingale_tendsto_testFunction_all
    {Ω Θ κ : Type*} [MeasurableSpace Ω] [MeasurableSpace Θ]
    {jointLaw : Measure (Ω × Θ)} {posteriorKernel : ℕ -> Kernel Ω Θ}
    {recoveryMap : Ω -> Θ}
    (S : Vaart1998BayesDoobMartingaleConvergenceSource
      (κ := κ) jointLaw posteriorKernel recoveryMap) :
    ∀ᵐ z ∂jointLaw, ∀ k : κ,
      Tendsto (fun n => S.posteriorIntegral k n z.1) atTop
        (𝓝 (S.determiningClass.testFunction k (recoveryMap z.1))) := by
  exact (S.martingale_tendsto_all.and S.recoveryIntegral_eq_all).mono
    (fun z hz k => by
      simpa [hz.2 k] using hz.1 k)

/--
Countable determining-class bridge from test-function martingale convergence
to weak posterior convergence toward the recovered parameter.
-/
structure Vaart1998BayesDoobDeterminingWeakConvergenceBridgeSource
    {Ω Θ κ : Type*} [MeasurableSpace Ω] [MeasurableSpace Θ]
    {jointLaw : Measure (Ω × Θ)} {posteriorKernel : ℕ -> Kernel Ω Θ}
    {recoveryMap : Ω -> Θ}
    (martingaleSource :
      Vaart1998BayesDoobMartingaleConvergenceSource
        (κ := κ) jointLaw posteriorKernel recoveryMap) where
  /-- Event on which posterior laws converge weakly to `δ_{h(X)}`. -/
  weakPosteriorConvergenceEvent : Set (Ω × Θ)
  /-- The countable determining class transfers test convergence to weak convergence. -/
  determiningClassTransfer :
    (∀ᵐ z ∂jointLaw, ∀ k : κ,
      Tendsto (fun n => martingaleSource.posteriorIntegral k n z.1) atTop
        (𝓝 (martingaleSource.determiningClass.testFunction k
          (recoveryMap z.1)))) ->
      ∀ᵐ z ∂jointLaw, z ∈ weakPosteriorConvergenceEvent

/--
The weak posterior convergence event holds almost surely under the joint law.
-/
theorem Vaart1998BayesDoobDeterminingWeakConvergenceBridgeSource.weakPosteriorConvergence_ae
    {Ω Θ κ : Type*} [MeasurableSpace Ω] [MeasurableSpace Θ]
    {jointLaw : Measure (Ω × Θ)} {posteriorKernel : ℕ -> Kernel Ω Θ}
    {recoveryMap : Ω -> Θ}
    {martingaleSource :
      Vaart1998BayesDoobMartingaleConvergenceSource
        (κ := κ) jointLaw posteriorKernel recoveryMap}
    (S : Vaart1998BayesDoobDeterminingWeakConvergenceBridgeSource
      martingaleSource) :
    ∀ᵐ z ∂jointLaw, z ∈ S.weakPosteriorConvergenceEvent :=
  S.determiningClassTransfer
    martingaleSource.martingale_tendsto_testFunction_all

/--
Fubini horizontal-section source in Doob's proof.

It turns a joint-law almost-sure event into a statement that, for prior-a.e.
parameter `θ`, the horizontal section has full `P_θ^∞` probability.
-/
structure Vaart1998BayesDoobFubiniHorizontalSectionSource
    {Ω Θ : Type*} [MeasurableSpace Ω] [MeasurableSpace Θ]
    (prior : Measure Θ) (sampleLawInfinite : Θ -> Measure Ω) where
  /-- Joint law of infinite sample and parameter. -/
  jointLaw : Measure (Ω × Θ)
  /-- Joint event whose sections are used in the proof. -/
  jointEvent : Set (Ω × Θ)
  /-- Horizontal section at parameter `θ`. -/
  horizontalSection : Θ -> Set Ω
  /-- The horizontal section is the section of the joint event. -/
  horizontalSection_eq :
    ∀ θ, horizontalSection θ = {ω | (ω, θ) ∈ jointEvent}
  /-- Fubini conclusion: sections have full probability for prior-a.e. θ. -/
  horizontalSection_full_ae_prior :
    ∀ᵐ θ ∂prior, sampleLawInfinite θ (horizontalSection θ) = 1

/--
The Fubini horizontal-section conclusion carried by the source.
-/
theorem Vaart1998BayesDoobFubiniHorizontalSectionSource.sections_full_ae
    {Ω Θ : Type*} [MeasurableSpace Ω] [MeasurableSpace Θ]
    {prior : Measure Θ} {sampleLawInfinite : Θ -> Measure Ω}
    (S : Vaart1998BayesDoobFubiniHorizontalSectionSource
      prior sampleLawInfinite) :
    ∀ᵐ θ ∂prior, sampleLawInfinite θ (S.horizontalSection θ) = 1 :=
  S.horizontalSection_full_ae_prior

/--
Final Doob weak-posterior-consistency route: martingale convergence plus a
countable determining class gives joint weak posterior convergence, and the
Fubini section argument transfers it to prior-a.e. parameterwise consistency.
-/
structure Vaart1998BayesDoobFinalConsistencyRouteSource
    {Ω Θ ι κ : Type*} [MeasurableSpace Ω] [MeasurableSpace Θ]
    (prior : Measure Θ) where
  /-- Existing Doob consistency route with recovery map. -/
  consistencyRoute :
    Vaart1998BayesDoobConsistencyRouteSource
      (Ω := Ω) (Θ := Θ) (ι := ι) prior
  /-- Doob martingale convergence along a countable determining class. -/
  martingaleSource :
    Vaart1998BayesDoobMartingaleConvergenceSource
      (κ := κ)
      consistencyRoute.recoveryRouteSource.jointLaw
      consistencyRoute.doobSource.posteriorKernel
      consistencyRoute.recoveryRouteSource.recoveryMapSource.recoveryMap
  /-- Test-function convergence to weak posterior convergence. -/
  determiningBridgeSource :
    Vaart1998BayesDoobDeterminingWeakConvergenceBridgeSource
      martingaleSource
  /-- Fubini horizontal-section handoff from joint law to parameter laws. -/
  fubiniSectionSource :
    Vaart1998BayesDoobFubiniHorizontalSectionSource
      prior consistencyRoute.doobSource.sampleLawInfinite

/--
The final Doob consistency source carried by the martingale/Fubini route.
-/
def Vaart1998BayesDoobFinalConsistencyRouteSource.doobConsistencySource
    {Ω Θ ι κ : Type*} [MeasurableSpace Ω] [MeasurableSpace Θ]
    {prior : Measure Θ}
    (S : Vaart1998BayesDoobFinalConsistencyRouteSource
      (Ω := Ω) (Θ := Θ) (ι := ι) (κ := κ) prior) :
    Vaart1998BayesDoobConsistencySource (Ω := Ω) (Θ := Θ) prior :=
  S.consistencyRoute.doobSource

/--
The joint weak posterior convergence event holds almost surely in the final
Doob route.
-/
theorem Vaart1998BayesDoobFinalConsistencyRouteSource.weakPosteriorConvergence_ae
    {Ω Θ ι κ : Type*} [MeasurableSpace Ω] [MeasurableSpace Θ]
    {prior : Measure Θ}
    (S : Vaart1998BayesDoobFinalConsistencyRouteSource
      (Ω := Ω) (Θ := Θ) (ι := ι) (κ := κ) prior) :
    ∀ᵐ z ∂S.consistencyRoute.recoveryRouteSource.jointLaw,
      z ∈ S.determiningBridgeSource.weakPosteriorConvergenceEvent :=
  S.determiningBridgeSource.weakPosteriorConvergence_ae

/--
The Fubini section handoff in the final Doob route.
-/
theorem Vaart1998BayesDoobFinalConsistencyRouteSource.sections_full_ae
    {Ω Θ ι κ : Type*} [MeasurableSpace Ω] [MeasurableSpace Θ]
    {prior : Measure Θ}
    (S : Vaart1998BayesDoobFinalConsistencyRouteSource
      (Ω := Ω) (Θ := Θ) (ι := ι) (κ := κ) prior) :
    ∀ᵐ θ ∂prior,
      S.consistencyRoute.doobSource.sampleLawInfinite θ
        (S.fubiniSectionSource.horizontalSection θ) = 1 :=
  S.fubiniSectionSource.sections_full_ae

/--
The prior-a.e. posterior-consistency conclusion from the final Doob route.
-/
theorem Vaart1998BayesDoobFinalConsistencyRouteSource.consistent_ae
    {Ω Θ ι κ : Type*} [MeasurableSpace Ω] [MeasurableSpace Θ]
    {prior : Measure Θ}
    (S : Vaart1998BayesDoobFinalConsistencyRouteSource
      (Ω := Ω) (Θ := Θ) (ι := ι) (κ := κ) prior) :
    ∀ᵐ θ ∂prior, θ ∈ S.consistencyRoute.doobSource.consistentSet :=
  S.consistencyRoute.consistent_ae

/--
Map a posterior kernel through a measurable posterior functional.
-/
def vaart1998_bayesPosteriorFunctionalKernel
    {Ω H T : Type*} [MeasurableSpace Ω] [MeasurableSpace H]
    [MeasurableSpace T]
    (posteriorKernel : ℕ -> Kernel Ω H) (functional : H -> T) :
    ℕ -> Kernel Ω T :=
  fun n => (posteriorKernel n).map functional

/--
Measurable functionals of Markov posterior kernels are Markov kernels.
-/
@[reducible]
def vaart1998_bayesPosteriorFunctionalKernel_isMarkov
    {Ω H T : Type*} [MeasurableSpace Ω] [MeasurableSpace H]
    [MeasurableSpace T]
    {posteriorKernel : ℕ -> Kernel Ω H} {functional : H -> T}
    (hfunctional : Measurable functional)
    (hK : ∀ n, IsMarkovKernel (posteriorKernel n)) :
    ∀ n, IsMarkovKernel
      (vaart1998_bayesPosteriorFunctionalKernel posteriorKernel
        functional n) := by
  intro n
  letI : IsMarkovKernel (posteriorKernel n) := hK n
  exact ProbabilityTheory.Kernel.IsMarkovKernel.map
    (posteriorKernel n) hfunctional

/--
The marginal law of a measurable posterior functional.
-/
def vaart1998_bayesPosteriorFunctionalMarginalMeasureSeq
    {Ω H T : Type*} [MeasurableSpace Ω] [MeasurableSpace H]
    [MeasurableSpace T]
    (P : ℕ -> Measure Ω) (posteriorKernel : ℕ -> Kernel Ω H)
    (functional : H -> T) :
    ℕ -> Measure T :=
  vaart1998_bayesPosteriorMarginalMeasureSeq P
    (vaart1998_bayesPosteriorFunctionalKernel posteriorKernel functional)

/--
Measurable posterior functionals of Markov posterior kernels induce
probability marginal laws.
-/
@[reducible]
def vaart1998_bayesPosteriorFunctionalMarginalMeasureSeq_isProbabilityMeasure
    {Ω H T : Type*} [MeasurableSpace Ω] [MeasurableSpace H]
    [MeasurableSpace T]
    {P : ℕ -> Measure Ω} {posteriorKernel : ℕ -> Kernel Ω H}
    {functional : H -> T}
    [∀ n, IsProbabilityMeasure (P n)]
    (hfunctional : Measurable functional)
    (hK : ∀ n, IsMarkovKernel (posteriorKernel n)) :
    ∀ n, IsProbabilityMeasure
      (vaart1998_bayesPosteriorFunctionalMarginalMeasureSeq P
        posteriorKernel functional n) :=
  vaart1998_bayesPosteriorMarginalMeasureSeq_isProbabilityMeasure
    (P := P)
    (posteriorKernel :=
      vaart1998_bayesPosteriorFunctionalKernel posteriorKernel functional)
    (vaart1998_bayesPosteriorFunctionalKernel_isMarkov
      hfunctional hK)

/--
Chapter 10 BvM approximation after a measurable posterior functional.

For total variation, the distance between pushforward posterior laws is
bounded by the original posterior distance.  The field
`functionalApproxDistance_norm_le_posteriorApproxDistance` records exactly
the domination needed to derive convergence in probability.
-/
structure Vaart1998BvMPosteriorFunctionalApproximationSource
    {Ω H T : Type*} [MeasurableSpace Ω] [MeasurableSpace H]
    [MeasurableSpace T]
    (P : ℕ -> Measure Ω) [∀ n, IsProbabilityMeasure (P n)] where
  /-- BvM approximation of the underlying posterior laws. -/
  bvmSource : Vaart1998BvMPosteriorApproximationSource (H := H) P
  /-- Measurable posterior functional. -/
  functional : H -> T
  /-- Measurability of the posterior functional. -/
  functional_measurable : Measurable functional
  /-- Random distance between the functional posterior law and its Gaussian approximation. -/
  functionalApproxDistance : ℕ -> Ω -> ℝ
  /-- The functional distance is dominated by the original posterior distance. -/
  functionalApproxDistance_norm_le_posteriorApproxDistance :
    ∀ n ω,
      ‖functionalApproxDistance n ω‖ ≤
        ‖bvmSource.posteriorApproxDistance n ω‖

/--
The posterior functional kernel attached to a BvM functional source.
-/
def Vaart1998BvMPosteriorFunctionalApproximationSource.posteriorFunctionalKernel
    {Ω H T : Type*} [MeasurableSpace Ω] [MeasurableSpace H]
    [MeasurableSpace T]
    {P : ℕ -> Measure Ω} [∀ n, IsProbabilityMeasure (P n)]
    (S : Vaart1998BvMPosteriorFunctionalApproximationSource (H := H)
      (T := T) P) :
    ℕ -> Kernel Ω T :=
  vaart1998_bayesPosteriorFunctionalKernel
    S.bvmSource.posteriorKernel S.functional

/--
The Gaussian posterior functional kernel attached to a BvM functional source.
-/
def Vaart1998BvMPosteriorFunctionalApproximationSource.gaussianPosteriorFunctionalKernel
    {Ω H T : Type*} [MeasurableSpace Ω] [MeasurableSpace H]
    [MeasurableSpace T]
    {P : ℕ -> Measure Ω} [∀ n, IsProbabilityMeasure (P n)]
    (S : Vaart1998BvMPosteriorFunctionalApproximationSource (H := H)
      (T := T) P) :
    ℕ -> Kernel Ω T :=
  vaart1998_bayesPosteriorFunctionalKernel
    S.bvmSource.gaussianPosteriorKernel S.functional

/--
The posterior functional kernels are Markov kernels.
-/
@[reducible]
def Vaart1998BvMPosteriorFunctionalApproximationSource.posteriorFunctionalKernel_isMarkov
    {Ω H T : Type*} [MeasurableSpace Ω] [MeasurableSpace H]
    [MeasurableSpace T]
    {P : ℕ -> Measure Ω} [∀ n, IsProbabilityMeasure (P n)]
    (S : Vaart1998BvMPosteriorFunctionalApproximationSource (H := H)
      (T := T) P) :
    ∀ n, IsMarkovKernel
      (S.posteriorFunctionalKernel (H := H) (T := T) n) :=
  vaart1998_bayesPosteriorFunctionalKernel_isMarkov
    S.functional_measurable S.bvmSource.posteriorKernel_isMarkov

/--
The Gaussian posterior functional kernels are Markov kernels.
-/
@[reducible]
def Vaart1998BvMPosteriorFunctionalApproximationSource.gaussianPosteriorFunctionalKernel_isMarkov
    {Ω H T : Type*} [MeasurableSpace Ω] [MeasurableSpace H]
    [MeasurableSpace T]
    {P : ℕ -> Measure Ω} [∀ n, IsProbabilityMeasure (P n)]
    (S : Vaart1998BvMPosteriorFunctionalApproximationSource (H := H)
      (T := T) P) :
    ∀ n, IsMarkovKernel
      (S.gaussianPosteriorFunctionalKernel (H := H) (T := T) n) :=
  vaart1998_bayesPosteriorFunctionalKernel_isMarkov
    S.functional_measurable S.bvmSource.gaussianPosteriorKernel_isMarkov

/--
The functional posterior approximation distance converges to zero in
frequentist probability.
-/
theorem Vaart1998BvMPosteriorFunctionalApproximationSource.convergesInProbability
    {Ω H T : Type*} [MeasurableSpace Ω] [MeasurableSpace H]
    [MeasurableSpace T]
    {P : ℕ -> Measure Ω} [∀ n, IsProbabilityMeasure (P n)]
    (S : Vaart1998BvMPosteriorFunctionalApproximationSource (H := H)
      (T := T) P) :
    Vaart1998MeasureSeqConvergesInProbabilityToZero P
      S.functionalApproxDistance :=
  vaart1998_measureSeqConvergesInProbabilityToZero_of_norm_le
    S.functionalApproxDistance_norm_le_posteriorApproxDistance
    S.bvmSource.posteriorApproxDistance_convergesInProbability

/--
The functional posterior approximation distance is stochastically bounded.
-/
theorem Vaart1998BvMPosteriorFunctionalApproximationSource.functionalApproxDistance_stochasticallyBounded
    {Ω H T : Type*} [MeasurableSpace Ω] [MeasurableSpace H]
    [MeasurableSpace T]
    {P : ℕ -> Measure Ω} [∀ n, IsProbabilityMeasure (P n)]
    (S : Vaart1998BvMPosteriorFunctionalApproximationSource (H := H)
      (T := T) P) :
    Vaart1998MeasureSeqStochasticBounded P S.functionalApproxDistance :=
  vaart1998_measureSeqStochasticBounded_of_convergesInProbabilityToZero
    S.convergesInProbability

/--
The marginal laws of the posterior functional in a BvM functional source.
-/
def Vaart1998BvMPosteriorFunctionalApproximationSource.posteriorFunctionalMarginalMeasureSeq
    {Ω H T : Type*} [MeasurableSpace Ω] [MeasurableSpace H]
    [MeasurableSpace T]
    {P : ℕ -> Measure Ω} [∀ n, IsProbabilityMeasure (P n)]
    (S : Vaart1998BvMPosteriorFunctionalApproximationSource (H := H)
      (T := T) P) :
    ℕ -> Measure T :=
  vaart1998_bayesPosteriorFunctionalMarginalMeasureSeq P
    S.bvmSource.posteriorKernel S.functional

/--
The Gaussian marginal laws of the posterior functional in a BvM functional
source.
-/
def Vaart1998BvMPosteriorFunctionalApproximationSource.gaussianPosteriorFunctionalMarginalMeasureSeq
    {Ω H T : Type*} [MeasurableSpace Ω] [MeasurableSpace H]
    [MeasurableSpace T]
    {P : ℕ -> Measure Ω} [∀ n, IsProbabilityMeasure (P n)]
    (S : Vaart1998BvMPosteriorFunctionalApproximationSource (H := H)
      (T := T) P) :
    ℕ -> Measure T :=
  vaart1998_bayesPosteriorFunctionalMarginalMeasureSeq P
    S.bvmSource.gaussianPosteriorKernel S.functional

/--
The posterior functional marginal laws are probability measures.
-/
@[reducible]
def Vaart1998BvMPosteriorFunctionalApproximationSource.posteriorFunctionalMarginal_isProbabilityMeasure
    {Ω H T : Type*} [MeasurableSpace Ω] [MeasurableSpace H]
    [MeasurableSpace T]
    {P : ℕ -> Measure Ω} [∀ n, IsProbabilityMeasure (P n)]
    (S : Vaart1998BvMPosteriorFunctionalApproximationSource (H := H)
      (T := T) P) :
    ∀ n, IsProbabilityMeasure
      (S.posteriorFunctionalMarginalMeasureSeq (H := H) (T := T) n) :=
  vaart1998_bayesPosteriorFunctionalMarginalMeasureSeq_isProbabilityMeasure
    (P := P) (posteriorKernel := S.bvmSource.posteriorKernel)
    (functional := S.functional)
    S.functional_measurable S.bvmSource.posteriorKernel_isMarkov

/--
The Gaussian posterior functional marginal laws are probability measures.
-/
@[reducible]
def Vaart1998BvMPosteriorFunctionalApproximationSource.gaussianPosteriorFunctionalMarginal_isProbabilityMeasure
    {Ω H T : Type*} [MeasurableSpace Ω] [MeasurableSpace H]
    [MeasurableSpace T]
    {P : ℕ -> Measure Ω} [∀ n, IsProbabilityMeasure (P n)]
    (S : Vaart1998BvMPosteriorFunctionalApproximationSource (H := H)
      (T := T) P) :
    ∀ n, IsProbabilityMeasure
      (S.gaussianPosteriorFunctionalMarginalMeasureSeq (H := H)
        (T := T) n) :=
  vaart1998_bayesPosteriorFunctionalMarginalMeasureSeq_isProbabilityMeasure
    (P := P) (posteriorKernel := S.bvmSource.gaussianPosteriorKernel)
    (functional := S.functional)
    S.functional_measurable S.bvmSource.gaussianPosteriorKernel_isMarkov

/--
The posterior tail integral appearing in display (10.9).  The set
`tailSet n` represents `C_nᶜ`, while `tailWeight` is the nonnegative
function `f` or a loss envelope.
-/
def vaart1998_bayesPosteriorTailLIntegral
    {Ω H : Type*} [MeasurableSpace Ω] [MeasurableSpace H]
    (posteriorKernel : ℕ -> Kernel Ω H) (tailSet : ℕ -> Set H)
    (tailWeight : H -> ℝ≥0∞) :
    ℕ -> Ω -> ℝ≥0∞ :=
  fun n ω =>
    ∫⁻ h, (tailSet n).indicator tailWeight h ∂posteriorKernel n ω

/--
Chapter 10 posterior-tail truncation source.

This is the source-shaped form of display (10.9): the posterior integral of
the tail part `f 1_{C_nᶜ}` is represented by a real-valued display and is
assumed to be `o_{P_n}(1)`.
-/
structure Vaart1998BayesPosteriorTailTruncationSource
    {Ω H : Type*} [MeasurableSpace Ω] [MeasurableSpace H]
    (P : ℕ -> Measure Ω) [∀ n, IsProbabilityMeasure (P n)] where
  /-- Posterior laws of the local parameter. -/
  posteriorKernel : ℕ -> Kernel Ω H
  /-- Posterior laws are Markov kernels. -/
  posteriorKernel_isMarkov : ∀ n, IsMarkovKernel (posteriorKernel n)
  /-- Tail sets, typically complements of balls `C_nᶜ`. -/
  tailSet : ℕ -> Set H
  /-- Nonnegative tail weight, e.g. a subpolynomial envelope. -/
  tailWeight : H -> ℝ≥0∞
  /-- Real-valued display of the posterior tail integral. -/
  tailIntegralDisplay : ℕ -> Ω -> ℝ
  /-- The displayed tail integral is nonnegative. -/
  tailIntegralDisplay_nonneg : ∀ n ω, 0 ≤ tailIntegralDisplay n ω
  /-- Display (10.9): the posterior tail integral is negligible in probability. -/
  tailIntegralDisplay_convergesInProbability :
    Vaart1998MeasureSeqConvergesInProbabilityToZero P tailIntegralDisplay

/--
The posterior tail integral as an extended nonnegative integral.
-/
def Vaart1998BayesPosteriorTailTruncationSource.tailLIntegral
    {Ω H : Type*} [MeasurableSpace Ω] [MeasurableSpace H]
    {P : ℕ -> Measure Ω} [∀ n, IsProbabilityMeasure (P n)]
    (S : Vaart1998BayesPosteriorTailTruncationSource (H := H) P) :
    ℕ -> Ω -> ℝ≥0∞ :=
  vaart1998_bayesPosteriorTailLIntegral S.posteriorKernel
    S.tailSet S.tailWeight

/--
The convergence-in-probability certificate for the tail display.
-/
theorem Vaart1998BayesPosteriorTailTruncationSource.convergesInProbability
    {Ω H : Type*} [MeasurableSpace Ω] [MeasurableSpace H]
    {P : ℕ -> Measure Ω} [∀ n, IsProbabilityMeasure (P n)]
    (S : Vaart1998BayesPosteriorTailTruncationSource (H := H) P) :
    Vaart1998MeasureSeqConvergesInProbabilityToZero P
      S.tailIntegralDisplay :=
  S.tailIntegralDisplay_convergesInProbability

/--
The posterior tail display is stochastically bounded.
-/
theorem Vaart1998BayesPosteriorTailTruncationSource.tailIntegralDisplay_stochasticallyBounded
    {Ω H : Type*} [MeasurableSpace Ω] [MeasurableSpace H]
    {P : ℕ -> Measure Ω} [∀ n, IsProbabilityMeasure (P n)]
    (S : Vaart1998BayesPosteriorTailTruncationSource (H := H) P) :
    Vaart1998MeasureSeqStochasticBounded P S.tailIntegralDisplay :=
  vaart1998_measureSeqStochasticBounded_of_convergesInProbabilityToZero
    S.tailIntegralDisplay_convergesInProbability

/--
Chapter 10 risk-process tail approximation source.

The full posterior-risk process `Z_n` and a truncated version `Z_{n,M_n}`
are recorded together with a pointwise bound of their difference by the
posterior tail display from (10.9).
-/
structure Vaart1998BayesRiskProcessTailApproximationSource
    {Ω H R : Type*} [MeasurableSpace Ω] [MeasurableSpace H]
    [SeminormedAddCommGroup R]
    (P : ℕ -> Measure Ω) [∀ n, IsProbabilityMeasure (P n)] where
  /-- Posterior-tail negligibility source. -/
  tailSource : Vaart1998BayesPosteriorTailTruncationSource
    (H := H) P
  /-- Full posterior-risk process `Z_n`. -/
  riskProcess : ℕ -> Ω -> R
  /-- Truncated posterior-risk process `Z_{n,M_n}`. -/
  truncatedRiskProcess : ℕ -> Ω -> R
  /-- The truncation error is bounded by the posterior tail display. -/
  riskProcess_sub_truncated_norm_le_tailIntegral :
    ∀ n ω,
      ‖riskProcess n ω - truncatedRiskProcess n ω‖ ≤
        ‖tailSource.tailIntegralDisplay n ω‖

/--
The full and truncated posterior-risk processes differ by `o_{P_n}(1)`.
-/
theorem Vaart1998BayesRiskProcessTailApproximationSource.riskProcess_sub_truncated_convergesInProbability
    {Ω H R : Type*} [MeasurableSpace Ω] [MeasurableSpace H]
    [SeminormedAddCommGroup R]
    {P : ℕ -> Measure Ω} [∀ n, IsProbabilityMeasure (P n)]
    (S : Vaart1998BayesRiskProcessTailApproximationSource (H := H)
      (R := R) P) :
    Vaart1998MeasureSeqConvergesInProbabilityToZero P
      (fun n ω => S.riskProcess n ω - S.truncatedRiskProcess n ω) :=
  vaart1998_measureSeqConvergesInProbabilityToZero_of_norm_le
    S.riskProcess_sub_truncated_norm_le_tailIntegral
    S.tailSource.tailIntegralDisplay_convergesInProbability

/--
The truncation error between the full and truncated risk processes is
stochastically bounded.
-/
theorem Vaart1998BayesRiskProcessTailApproximationSource.riskProcess_sub_truncated_stochasticallyBounded
    {Ω H R : Type*} [MeasurableSpace Ω] [MeasurableSpace H]
    [SeminormedAddCommGroup R]
    {P : ℕ -> Measure Ω} [∀ n, IsProbabilityMeasure (P n)]
    (S : Vaart1998BayesRiskProcessTailApproximationSource (H := H)
      (R := R) P) :
    Vaart1998MeasureSeqStochasticBounded P
      (fun n ω => S.riskProcess n ω - S.truncatedRiskProcess n ω) :=
  vaart1998_measureSeqStochasticBounded_of_convergesInProbabilityToZero
    S.riskProcess_sub_truncated_convergesInProbability

/--
Chapter 10 compact risk-process convergence source.

This packages the final risk-process step in Theorem 10.8.  A truncated
process converges weakly on the compact index set, the full/truncated
difference is negligible by the posterior-tail source, and a supplied
Slutsky/diagonal-transfer certificate upgrades the truncated convergence to
the full posterior-risk process.
-/
structure Vaart1998BayesCompactRiskProcessConvergenceSource
    {Ω ΩLimit H R : Type*} [MeasurableSpace Ω]
    [MeasurableSpace ΩLimit] [MeasurableSpace H]
    [SeminormedAddCommGroup R] [TopologicalSpace R] [MeasurableSpace R]
    [OpensMeasurableSpace R]
    (P : ℕ -> Measure Ω) (LimitLaw : Measure ΩLimit)
    [∀ n, IsProbabilityMeasure (P n)] [IsProbabilityMeasure LimitLaw] where
  /-- Tail approximation of the full risk process by truncated processes. -/
  tailApproximationSource :
    Vaart1998BayesRiskProcessTailApproximationSource (H := H)
      (R := R) P
  /-- Limiting posterior-risk process `Z`. -/
  limitRiskProcess : ΩLimit -> R
  /-- Weak convergence of the selected truncated process. -/
  truncatedRiskProcess_tendstoInDistribution :
    TendstoInDistribution
      tailApproximationSource.truncatedRiskProcess atTop limitRiskProcess
      P LimitLaw
  /--
  Slutsky/diagonal transfer from truncated compact-process convergence and
  tail negligibility to convergence of the full risk process.
  -/
  tailSlutskyTransfer :
    Vaart1998MeasureSeqConvergesInProbabilityToZero P
        (fun n ω =>
          tailApproximationSource.riskProcess n ω -
            tailApproximationSource.truncatedRiskProcess n ω) ->
      TendstoInDistribution
        tailApproximationSource.truncatedRiskProcess atTop
        limitRiskProcess P LimitLaw ->
      TendstoInDistribution
        tailApproximationSource.riskProcess atTop
        limitRiskProcess P LimitLaw

/--
The compact risk-process convergence certificate carried by a Chapter 10
risk-process source.
-/
theorem Vaart1998BayesCompactRiskProcessConvergenceSource.riskProcess_tendstoInDistribution
    {Ω ΩLimit H R : Type*} [MeasurableSpace Ω]
    [MeasurableSpace ΩLimit] [MeasurableSpace H]
    [SeminormedAddCommGroup R] [TopologicalSpace R] [MeasurableSpace R]
    [OpensMeasurableSpace R]
    {P : ℕ -> Measure Ω} {LimitLaw : Measure ΩLimit}
    [∀ n, IsProbabilityMeasure (P n)] [IsProbabilityMeasure LimitLaw]
    (S : Vaart1998BayesCompactRiskProcessConvergenceSource
      (H := H) (R := R) P LimitLaw) :
    TendstoInDistribution S.tailApproximationSource.riskProcess atTop
      S.limitRiskProcess P LimitLaw :=
  S.tailSlutskyTransfer
    S.tailApproximationSource.riskProcess_sub_truncated_convergesInProbability
    S.truncatedRiskProcess_tendstoInDistribution

/--
Chapter 10 diagonal-radius source for the selected truncation level `M_n`.

The proof of Theorem 10.8 first proves compact-process convergence for fixed
truncation radii and then chooses a diverging radius sequence.  This source
records that selected sequence and packages the resulting truncated process.
-/
structure Vaart1998BayesDiagonalRadiusTruncationSource
    {Ω ΩLimit H R : Type*} [MeasurableSpace Ω]
    [MeasurableSpace ΩLimit] [MeasurableSpace H]
    [SeminormedAddCommGroup R] [TopologicalSpace R] [MeasurableSpace R]
    [OpensMeasurableSpace R]
    (P : ℕ -> Measure Ω) (LimitLaw : Measure ΩLimit)
    [∀ n, IsProbabilityMeasure (P n)] [IsProbabilityMeasure LimitLaw] where
  /-- Posterior-tail negligibility source for the chosen complements `C_nᶜ`. -/
  tailSource : Vaart1998BayesPosteriorTailTruncationSource
    (H := H) P
  /-- Diverging truncation radius sequence `M_n`. -/
  radius : ℕ -> ℝ
  /-- The chosen radii diverge. -/
  radius_tendsto_atTop : Tendsto radius atTop atTop
  /-- Eventually the chosen radii are positive. -/
  radius_eventually_pos : ∀ᶠ n in atTop, 0 < radius n
  /-- Full posterior-risk process `Z_n`. -/
  riskProcess : ℕ -> Ω -> R
  /-- Selected truncated posterior-risk process `Z_{n,M_n}`. -/
  selectedTruncatedRiskProcess : ℕ -> Ω -> R
  /-- Limiting posterior-risk process `Z`. -/
  limitRiskProcess : ΩLimit -> R
  /-- Weak convergence of the selected truncated process. -/
  selectedTruncatedRiskProcess_tendstoInDistribution :
    TendstoInDistribution selectedTruncatedRiskProcess atTop
      limitRiskProcess P LimitLaw
  /-- The selected truncation error is bounded by the posterior tail display. -/
  riskProcess_sub_selected_norm_le_tailIntegral :
    ∀ n ω,
      ‖riskProcess n ω - selectedTruncatedRiskProcess n ω‖ ≤
        ‖tailSource.tailIntegralDisplay n ω‖
  /-- Slutsky transfer from selected truncated convergence to full convergence. -/
  tailSlutskyTransfer :
    Vaart1998MeasureSeqConvergesInProbabilityToZero P
        (fun n ω => riskProcess n ω - selectedTruncatedRiskProcess n ω) ->
      TendstoInDistribution selectedTruncatedRiskProcess atTop
        limitRiskProcess P LimitLaw ->
      TendstoInDistribution riskProcess atTop limitRiskProcess P LimitLaw

/--
The selected diagonal truncation gives a tail-approximation source.
-/
def Vaart1998BayesDiagonalRadiusTruncationSource.tailApproximationSource
    {Ω ΩLimit H R : Type*} [MeasurableSpace Ω]
    [MeasurableSpace ΩLimit] [MeasurableSpace H]
    [SeminormedAddCommGroup R] [TopologicalSpace R] [MeasurableSpace R]
    [OpensMeasurableSpace R]
    {P : ℕ -> Measure Ω} {LimitLaw : Measure ΩLimit}
    [∀ n, IsProbabilityMeasure (P n)] [IsProbabilityMeasure LimitLaw]
    (S : Vaart1998BayesDiagonalRadiusTruncationSource
      (H := H) (R := R) P LimitLaw) :
    Vaart1998BayesRiskProcessTailApproximationSource (H := H)
      (R := R) P :=
  { tailSource := S.tailSource
    riskProcess := S.riskProcess
    truncatedRiskProcess := S.selectedTruncatedRiskProcess
    riskProcess_sub_truncated_norm_le_tailIntegral :=
      S.riskProcess_sub_selected_norm_le_tailIntegral }

/--
The selected diagonal truncation error is `o_{P_n}(1)`.
-/
theorem Vaart1998BayesDiagonalRadiusTruncationSource.riskProcess_sub_selected_convergesInProbability
    {Ω ΩLimit H R : Type*} [MeasurableSpace Ω]
    [MeasurableSpace ΩLimit] [MeasurableSpace H]
    [SeminormedAddCommGroup R] [TopologicalSpace R] [MeasurableSpace R]
    [OpensMeasurableSpace R]
    {P : ℕ -> Measure Ω} {LimitLaw : Measure ΩLimit}
    [∀ n, IsProbabilityMeasure (P n)] [IsProbabilityMeasure LimitLaw]
    (S : Vaart1998BayesDiagonalRadiusTruncationSource
      (H := H) (R := R) P LimitLaw) :
    Vaart1998MeasureSeqConvergesInProbabilityToZero P
      (fun n ω => S.riskProcess n ω -
        S.selectedTruncatedRiskProcess n ω) :=
  S.tailApproximationSource.riskProcess_sub_truncated_convergesInProbability

/--
A diagonal-radius source yields the compact risk-process convergence source
used by the argmin theorem.
-/
def Vaart1998BayesDiagonalRadiusTruncationSource.compactRiskProcessConvergenceSource
    {Ω ΩLimit H R : Type*} [MeasurableSpace Ω]
    [MeasurableSpace ΩLimit] [MeasurableSpace H]
    [SeminormedAddCommGroup R] [TopologicalSpace R] [MeasurableSpace R]
    [OpensMeasurableSpace R]
    {P : ℕ -> Measure Ω} {LimitLaw : Measure ΩLimit}
    [∀ n, IsProbabilityMeasure (P n)] [IsProbabilityMeasure LimitLaw]
    (S : Vaart1998BayesDiagonalRadiusTruncationSource
      (H := H) (R := R) P LimitLaw) :
    Vaart1998BayesCompactRiskProcessConvergenceSource (H := H)
      (R := R) P LimitLaw :=
  { tailApproximationSource := S.tailApproximationSource
    limitRiskProcess := S.limitRiskProcess
    truncatedRiskProcess_tendstoInDistribution :=
      S.selectedTruncatedRiskProcess_tendstoInDistribution
    tailSlutskyTransfer := S.tailSlutskyTransfer }

/--
The full posterior-risk process converges after diagonal radius selection.
-/
theorem Vaart1998BayesDiagonalRadiusTruncationSource.riskProcess_tendstoInDistribution
    {Ω ΩLimit H R : Type*} [MeasurableSpace Ω]
    [MeasurableSpace ΩLimit] [MeasurableSpace H]
    [SeminormedAddCommGroup R] [TopologicalSpace R] [MeasurableSpace R]
    [OpensMeasurableSpace R]
    {P : ℕ -> Measure Ω} {LimitLaw : Measure ΩLimit}
    [∀ n, IsProbabilityMeasure (P n)] [IsProbabilityMeasure LimitLaw]
    (S : Vaart1998BayesDiagonalRadiusTruncationSource
      (H := H) (R := R) P LimitLaw) :
    TendstoInDistribution S.riskProcess atTop S.limitRiskProcess
      P LimitLaw :=
  S.compactRiskProcessConvergenceSource.riskProcess_tendstoInDistribution

/--
Chapter 10 Bayes point-estimator limit source.

This is the point-estimator consequence layer of BvM: after a posterior
approximation source and a Bayes posterior-risk minimizer are available, the
standardized estimator is recorded as converging in distribution to the
corresponding limit-experiment Bayes functional.
-/
structure Vaart1998BayesPointEstimatorLimitSource
    {Ω ΩLimit H T : Type*} [MeasurableSpace Ω] [MeasurableSpace ΩLimit]
    [MeasurableSpace H]
    [TopologicalSpace T] [MeasurableSpace T] [OpensMeasurableSpace T]
    (P : ℕ -> Measure Ω) (LimitLaw : Measure ΩLimit)
    [∀ n, IsProbabilityMeasure (P n)] [IsProbabilityMeasure LimitLaw] where
  /-- BvM approximation of the full posterior laws. -/
  bvmSource : Vaart1998BvMPosteriorApproximationSource (H := H) P
  /-- Posterior-risk minimizer that defines the Bayes point estimator. -/
  minimizerSource :
    Vaart1998BayesPosteriorRiskMinimizerSource
      (T := T) bvmSource.posteriorKernel
  /-- Limit-experiment Bayes functional. -/
  limitEstimator : ΩLimit -> T
  /-- Frequentist weak limit of the standardized Bayes point estimator. -/
  estimator_tendstoInDistribution :
    TendstoInDistribution minimizerSource.estimator atTop limitEstimator
      P LimitLaw

/--
The weak limit certificate carried by a Bayes point-estimator source.
-/
theorem Vaart1998BayesPointEstimatorLimitSource.tendstoInDistribution
    {Ω ΩLimit H T : Type*} [MeasurableSpace Ω] [MeasurableSpace ΩLimit]
    [MeasurableSpace H]
    [TopologicalSpace T] [MeasurableSpace T] [OpensMeasurableSpace T]
    {P : ℕ -> Measure Ω} {LimitLaw : Measure ΩLimit}
    [∀ n, IsProbabilityMeasure (P n)] [IsProbabilityMeasure LimitLaw]
    (S : Vaart1998BayesPointEstimatorLimitSource
      (H := H) (T := T) P LimitLaw) :
    TendstoInDistribution S.minimizerSource.estimator atTop
      S.limitEstimator P LimitLaw :=
  S.estimator_tendstoInDistribution

/--
A Chapter 10 Bayes point-estimator limit is a one-parameter Chapter 9
experiment-limit source.
-/
def Vaart1998BayesPointEstimatorLimitSource.experimentLimitSource
    {Ω ΩLimit H T : Type*} [MeasurableSpace Ω] [MeasurableSpace ΩLimit]
    [MeasurableSpace H]
    [TopologicalSpace T] [MeasurableSpace T] [OpensMeasurableSpace T]
    {P : ℕ -> Measure Ω} {LimitLaw : Measure ΩLimit}
    [∀ n, IsProbabilityMeasure (P n)] [IsProbabilityMeasure LimitLaw]
    (S : Vaart1998BayesPointEstimatorLimitSource
      (H := H) (T := T) P LimitLaw) :
    Vaart1998ExperimentLimitSource
      (Ω := Ω) (ΩLimit := ΩLimit) (Θ := Unit) (Z := T)
      (fun _ : Unit => P) (fun _ : Unit => LimitLaw) :=
  { parameterSet := Set.univ
    statistic := S.minimizerSource.estimator
    limitStatistic := S.limitEstimator
    statistic_tendstoInDistribution := fun _ _ =>
      S.estimator_tendstoInDistribution }

/--
The Bayes point estimator remains a posterior-risk minimizer inside the
combined BvM/point-estimator source.
-/
theorem Vaart1998BayesPointEstimatorLimitSource.minimizes_posteriorRisk
    {Ω ΩLimit H T : Type*} [MeasurableSpace Ω] [MeasurableSpace ΩLimit]
    [MeasurableSpace H]
    [TopologicalSpace T] [MeasurableSpace T] [OpensMeasurableSpace T]
    {P : ℕ -> Measure Ω} {LimitLaw : Measure ΩLimit}
    [∀ n, IsProbabilityMeasure (P n)] [IsProbabilityMeasure LimitLaw]
    (S : Vaart1998BayesPointEstimatorLimitSource
      (H := H) (T := T) P LimitLaw)
    (n : ℕ) (ω : Ω) (t : T) :
    vaart1998_bayesPosteriorRiskAt S.bvmSource.posteriorKernel
      S.minimizerSource.loss (S.minimizerSource.estimator n ω) n ω ≤
    vaart1998_bayesPosteriorRiskAt S.bvmSource.posteriorKernel
      S.minimizerSource.loss t n ω :=
  S.minimizerSource.minimizes_posteriorRisk n ω t

/--
Chapter 10 argmin continuous-mapping source for Bayes estimators.

This packages the proof skeleton of Theorem 10.8: posterior risk processes
converge weakly in a process space, a continuous argmin functional selects
the estimator, and therefore the Bayes estimator converges to the argmin of
the limiting posterior risk process.
-/
structure Vaart1998BayesArgminContinuitySource
    {Ω ΩLimit H R T : Type*} [MeasurableSpace Ω] [MeasurableSpace ΩLimit]
    [MeasurableSpace H]
    [TopologicalSpace R] [MeasurableSpace R] [OpensMeasurableSpace R]
    [TopologicalSpace T] [MeasurableSpace T] [BorelSpace T]
    [OpensMeasurableSpace T]
    (P : ℕ -> Measure Ω) (LimitLaw : Measure ΩLimit)
    [∀ n, IsProbabilityMeasure (P n)] [IsProbabilityMeasure LimitLaw] where
  /-- Functional BvM approximation supplying the posterior-law side. -/
  functionalSource :
    Vaart1998BvMPosteriorFunctionalApproximationSource (H := H)
      (T := T) P
  /-- Posterior-risk process, such as `t ↦ Z_n(t)` on a compact set. -/
  riskProcess : ℕ -> Ω -> R
  /-- Limiting posterior-risk process, such as `t ↦ Z(t)`. -/
  limitRiskProcess : ΩLimit -> R
  /-- Continuous argmin/selection map from risk processes to decisions. -/
  argminFunctional : R -> T
  /-- Continuity assumption supplied by the argmax/argmin theorem. -/
  argminFunctional_continuous : Continuous argminFunctional
  /-- Weak convergence of posterior-risk processes. -/
  riskProcess_tendstoInDistribution :
    TendstoInDistribution riskProcess atTop limitRiskProcess P LimitLaw
  /-- Posterior-risk minimizer that represents the Bayes estimator. -/
  minimizerSource :
    Vaart1998BayesPosteriorRiskMinimizerSource
      (T := T) functionalSource.bvmSource.posteriorKernel
  /-- The Bayes estimator is the argmin of the finite-sample risk process. -/
  estimator_eq_argminFunctional :
    ∀ n ω,
      minimizerSource.estimator n ω =
        argminFunctional (riskProcess n ω)
  /-- Limiting Bayes estimator. -/
  limitEstimator : ΩLimit -> T
  /-- The limiting estimator is the argmin of the limiting risk process. -/
  limitEstimator_eq_argminFunctional :
    ∀ ω,
      limitEstimator ω = argminFunctional (limitRiskProcess ω)

/--
The argmin continuous-mapping certificate for Chapter 10 Bayes estimators.
-/
theorem Vaart1998BayesArgminContinuitySource.tendstoInDistribution
    {Ω ΩLimit H R T : Type*} [MeasurableSpace Ω] [MeasurableSpace ΩLimit]
    [MeasurableSpace H]
    [TopologicalSpace R] [MeasurableSpace R] [OpensMeasurableSpace R]
    [TopologicalSpace T] [MeasurableSpace T] [BorelSpace T]
    [OpensMeasurableSpace T]
    {P : ℕ -> Measure Ω} {LimitLaw : Measure ΩLimit}
    [∀ n, IsProbabilityMeasure (P n)] [IsProbabilityMeasure LimitLaw]
    (S : Vaart1998BayesArgminContinuitySource
      (H := H) (R := R) (T := T) P LimitLaw) :
    TendstoInDistribution S.minimizerSource.estimator atTop
      S.limitEstimator P LimitLaw := by
  have hArgmin :
      TendstoInDistribution
        (fun n ω => S.argminFunctional (S.riskProcess n ω)) atTop
        (fun ω => S.argminFunctional (S.limitRiskProcess ω))
        P LimitLaw :=
    TendstoInDistribution.continuous_comp S.argminFunctional_continuous
      S.riskProcess_tendstoInDistribution
  refine hArgmin.congr ?_ ?_
  · intro n
    exact ae_of_all _ fun ω => by
      simp [S.estimator_eq_argminFunctional n ω]
  · exact ae_of_all _ fun ω => by
      simp [S.limitEstimator_eq_argminFunctional ω]

/--
A Chapter 10 argmin-continuity source is a Bayes point-estimator limit source.
-/
def Vaart1998BayesArgminContinuitySource.bayesPointEstimatorLimitSource
    {Ω ΩLimit H R T : Type*} [MeasurableSpace Ω] [MeasurableSpace ΩLimit]
    [MeasurableSpace H]
    [TopologicalSpace R] [MeasurableSpace R] [OpensMeasurableSpace R]
    [TopologicalSpace T] [MeasurableSpace T] [BorelSpace T]
    [OpensMeasurableSpace T]
    {P : ℕ -> Measure Ω} {LimitLaw : Measure ΩLimit}
    [∀ n, IsProbabilityMeasure (P n)] [IsProbabilityMeasure LimitLaw]
    (S : Vaart1998BayesArgminContinuitySource
      (H := H) (R := R) (T := T) P LimitLaw) :
    Vaart1998BayesPointEstimatorLimitSource (H := H) (T := T)
      P LimitLaw :=
  { bvmSource := S.functionalSource.bvmSource
    minimizerSource := S.minimizerSource
    limitEstimator := S.limitEstimator
    estimator_tendstoInDistribution := S.tendstoInDistribution }

/--
A compact risk-process convergence source supplies the risk-process field of
the Chapter 10 argmin-continuity source.
-/
def Vaart1998BayesCompactRiskProcessConvergenceSource.argminContinuitySource
    {Ω ΩLimit H R T : Type*} [MeasurableSpace Ω]
    [MeasurableSpace ΩLimit] [MeasurableSpace H]
    [SeminormedAddCommGroup R] [TopologicalSpace R] [MeasurableSpace R]
    [OpensMeasurableSpace R]
    [TopologicalSpace T] [MeasurableSpace T] [BorelSpace T]
    [OpensMeasurableSpace T]
    {P : ℕ -> Measure Ω} {LimitLaw : Measure ΩLimit}
    [∀ n, IsProbabilityMeasure (P n)] [IsProbabilityMeasure LimitLaw]
    (S : Vaart1998BayesCompactRiskProcessConvergenceSource
      (H := H) (R := R) P LimitLaw)
    (functionalSource :
      Vaart1998BvMPosteriorFunctionalApproximationSource (H := H)
        (T := T) P)
    (argminFunctional : R -> T)
    (argminFunctional_continuous : Continuous argminFunctional)
    (minimizerSource :
      Vaart1998BayesPosteriorRiskMinimizerSource
        (T := T) functionalSource.bvmSource.posteriorKernel)
    (estimator_eq_argminFunctional :
      ∀ n ω,
        minimizerSource.estimator n ω =
          argminFunctional (S.tailApproximationSource.riskProcess n ω))
    (limitEstimator : ΩLimit -> T)
    (limitEstimator_eq_argminFunctional :
      ∀ ω, limitEstimator ω = argminFunctional (S.limitRiskProcess ω)) :
    Vaart1998BayesArgminContinuitySource
      (H := H) (R := R) (T := T) P LimitLaw :=
  { functionalSource := functionalSource
    riskProcess := S.tailApproximationSource.riskProcess
    limitRiskProcess := S.limitRiskProcess
    argminFunctional := argminFunctional
    argminFunctional_continuous := argminFunctional_continuous
    riskProcess_tendstoInDistribution := S.riskProcess_tendstoInDistribution
    minimizerSource := minimizerSource
    estimator_eq_argminFunctional := estimator_eq_argminFunctional
    limitEstimator := limitEstimator
    limitEstimator_eq_argminFunctional := limitEstimator_eq_argminFunctional }

/--
The compact-risk-process route directly yields a Bayes point-estimator limit
once the argmin selector and posterior-risk minimizer are supplied.
-/
def Vaart1998BayesCompactRiskProcessConvergenceSource.bayesPointEstimatorLimitSource
    {Ω ΩLimit H R T : Type*} [MeasurableSpace Ω]
    [MeasurableSpace ΩLimit] [MeasurableSpace H]
    [SeminormedAddCommGroup R] [TopologicalSpace R] [MeasurableSpace R]
    [OpensMeasurableSpace R]
    [TopologicalSpace T] [MeasurableSpace T] [BorelSpace T]
    [OpensMeasurableSpace T]
    {P : ℕ -> Measure Ω} {LimitLaw : Measure ΩLimit}
    [∀ n, IsProbabilityMeasure (P n)] [IsProbabilityMeasure LimitLaw]
    (S : Vaart1998BayesCompactRiskProcessConvergenceSource
      (H := H) (R := R) P LimitLaw)
    (functionalSource :
      Vaart1998BvMPosteriorFunctionalApproximationSource (H := H)
        (T := T) P)
    (argminFunctional : R -> T)
    (argminFunctional_continuous : Continuous argminFunctional)
    (minimizerSource :
      Vaart1998BayesPosteriorRiskMinimizerSource
        (T := T) functionalSource.bvmSource.posteriorKernel)
    (estimator_eq_argminFunctional :
      ∀ n ω,
        minimizerSource.estimator n ω =
          argminFunctional (S.tailApproximationSource.riskProcess n ω))
    (limitEstimator : ΩLimit -> T)
    (limitEstimator_eq_argminFunctional :
      ∀ ω, limitEstimator ω = argminFunctional (S.limitRiskProcess ω)) :
    Vaart1998BayesPointEstimatorLimitSource (H := H) (T := T)
      P LimitLaw :=
  (S.argminContinuitySource functionalSource argminFunctional
    argminFunctional_continuous minimizerSource
    estimator_eq_argminFunctional limitEstimator
    limitEstimator_eq_argminFunctional).bayesPointEstimatorLimitSource

/--
Chapter 10 nonzero-subconvex-loss center source.

The final sentence of Theorem 10.8 uses Anderson's lemma to identify the
limit argmin, for a nonzero subconvex loss, with the center `X` of the
Gaussian posterior.  This source records that Anderson-lemma identification
and transfers the already-proved Bayes estimator limit to the Gaussian center.
-/
structure Vaart1998BayesNonzeroSubconvexLossCenterSource
    {Ω ΩLimit H T : Type*} [MeasurableSpace Ω]
    [MeasurableSpace ΩLimit] [MeasurableSpace H]
    [TopologicalSpace T] [MeasurableSpace T] [OpensMeasurableSpace T]
    (P : ℕ -> Measure Ω) (LimitLaw : Measure ΩLimit)
    [∀ n, IsProbabilityMeasure (P n)] [IsProbabilityMeasure LimitLaw] where
  /-- Bayes point-estimator limit source from the argmin route. -/
  bayesPointSource :
    Vaart1998BayesPointEstimatorLimitSource (H := H) (T := T)
      P LimitLaw
  /-- Center of the limiting Gaussian posterior, denoted `X` in the theorem. -/
  gaussianCenter : ΩLimit -> T
  /-- Anderson/subconvex-loss certificate: the limit argmin is the center. -/
  andersonSubconvex_limitEstimator_eq_center :
    ∀ ω, bayesPointSource.limitEstimator ω = gaussianCenter ω

/--
For a nonzero subconvex loss, the standardized Bayes estimator converges to
the center `X` of the limiting Gaussian posterior.
-/
theorem Vaart1998BayesNonzeroSubconvexLossCenterSource.tendstoInDistribution_gaussianCenter
    {Ω ΩLimit H T : Type*} [MeasurableSpace Ω]
    [MeasurableSpace ΩLimit] [MeasurableSpace H]
    [TopologicalSpace T] [MeasurableSpace T] [OpensMeasurableSpace T]
    {P : ℕ -> Measure Ω} {LimitLaw : Measure ΩLimit}
    [∀ n, IsProbabilityMeasure (P n)] [IsProbabilityMeasure LimitLaw]
    (S : Vaart1998BayesNonzeroSubconvexLossCenterSource
      (H := H) (T := T) P LimitLaw) :
    TendstoInDistribution S.bayesPointSource.minimizerSource.estimator atTop
      S.gaussianCenter P LimitLaw := by
  refine S.bayesPointSource.tendstoInDistribution.congr
    (fun _ => Filter.EventuallyEq.rfl) ?_
  exact ae_of_all _ fun ω =>
    S.andersonSubconvex_limitEstimator_eq_center ω

/--
The nonzero-subconvex-loss center limit as a one-parameter Chapter 9
experiment-limit source.
-/
def Vaart1998BayesNonzeroSubconvexLossCenterSource.experimentLimitSource
    {Ω ΩLimit H T : Type*} [MeasurableSpace Ω]
    [MeasurableSpace ΩLimit] [MeasurableSpace H]
    [TopologicalSpace T] [MeasurableSpace T] [OpensMeasurableSpace T]
    {P : ℕ -> Measure Ω} {LimitLaw : Measure ΩLimit}
    [∀ n, IsProbabilityMeasure (P n)] [IsProbabilityMeasure LimitLaw]
    (S : Vaart1998BayesNonzeroSubconvexLossCenterSource
      (H := H) (T := T) P LimitLaw) :
    Vaart1998ExperimentLimitSource
      (Ω := Ω) (ΩLimit := ΩLimit) (Θ := Unit) (Z := T)
      (fun _ : Unit => P) (fun _ : Unit => LimitLaw) :=
  { parameterSet := Set.univ
    statistic := S.bayesPointSource.minimizerSource.estimator
    limitStatistic := S.gaussianCenter
    statistic_tendstoInDistribution := fun _ _ =>
      S.tendstoInDistribution_gaussianCenter }

end AsymptoticStatistics
end StatInference
