from __future__ import annotations

import json
import re
import shutil
import subprocess
import time
from pathlib import Path
from typing import Any, Mapping

from .verifier import DEFAULT_LOCAL_LEAN_PROJECTS, placeholder_proof_errors


ARTIFACT_KIND = "TheoremReductionClosureWorkOrderAuditManifest"
BOUNDARY = (
    "Theorem reduction closure work-order audits are proof-task diagnostics. "
    "Exported Lean sketches, queue rows, and placeholder rejection are not proof "
    "evidence. Only a row with kernel_verified=true from local Lean/AXLE "
    "counts as proof evidence."
)


def audit_theorem_reduction_closure_work_orders(
    queue_jsonl: Path,
    out_dir: Path,
    *,
    run_local_lean: bool = False,
    lean_project: Path | None = None,
    lean_timeout_seconds: int = 240,
) -> dict[str, Any]:
    """Audit theorem-level closure work orders exported by live AgentRuntime.

    This is intentionally a narrow ProofEngineer bridge: it exports the Lean
    statement sketches generated by the runtime, rejects placeholders, and can
    optionally run `lake env lean` as the trusted kernel gate.
    """

    out_dir = out_dir.expanduser().resolve()
    queue_jsonl = queue_jsonl.expanduser().resolve()
    out_dir.mkdir(parents=True, exist_ok=True)
    lean_export_dir = out_dir / "lean_statement_sketches"
    lean_export_dir.mkdir(parents=True, exist_ok=True)
    checks_path = out_dir / "theorem_reduction_closure_work_order_checks.jsonl"
    manifest_path = out_dir / "theorem_reduction_closure_work_order_audit_manifest.json"

    rows = _read_jsonl(queue_jsonl)
    resolved_lean_project = _resolve_lean_project(lean_project) if run_local_lean else None
    checks: list[dict[str, Any]] = []

    for index, row in enumerate(rows, start=1):
        check = _audit_one_work_order(
            row,
            index=index,
            lean_export_dir=lean_export_dir,
            run_local_lean=run_local_lean,
            lean_project=resolved_lean_project,
            lean_timeout_seconds=lean_timeout_seconds,
        )
        checks.append(check)

    n_exported = sum(1 for row in checks if row.get("lean_export_path"))
    n_local_attempted = sum(1 for row in checks if row.get("local_lean_attempted"))
    n_kernel_verified = sum(1 for row in checks if row.get("kernel_verified"))
    n_placeholder_rejected = sum(1 for row in checks if row.get("status") == "PLACEHOLDER_REJECTED")
    n_formal_blocked = sum(1 for row in checks if str(row.get("status", "")).startswith("FORMAL_BLOCKED"))
    n_local_lean_failed = sum(1 for row in checks if row.get("status") in {"LOCAL_LEAN_REJECTED", "LOCAL_LEAN_TIMEOUT"})
    proof_evidence_status = (
        "KERNEL_VERIFIED_THEOREM_CLOSURE_PRESENT"
        if n_kernel_verified
        else "NO_KERNEL_VERIFIED_THEOREM_CLOSURE"
    )
    manifest: dict[str, Any] = {
        "artifact_kind": ARTIFACT_KIND,
        "schema_version": 1,
        "source_queue_jsonl": str(queue_jsonl),
        "lean_export_dir": str(lean_export_dir),
        "checks_jsonl": str(checks_path),
        "n_work_orders": len(rows),
        "n_exported_lean_sketches": n_exported,
        "n_local_lean_attempted": n_local_attempted,
        "n_kernel_verified": n_kernel_verified,
        "n_formal_blocked": n_formal_blocked,
        "n_placeholder_rejected": n_placeholder_rejected,
        "n_local_lean_failed": n_local_lean_failed,
        "all_kernel_verified": bool(rows) and n_kernel_verified == len(rows),
        "proof_evidence_status": proof_evidence_status,
        "local_lean_requested": bool(run_local_lean),
        "local_lean_project": str(resolved_lean_project) if resolved_lean_project else "",
        "local_lean_timeout_seconds": int(lean_timeout_seconds),
        "checks": checks,
        "boundary": BOUNDARY,
    }
    _write_jsonl(checks_path, checks)
    manifest_path.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return manifest


def _audit_one_work_order(
    row: Mapping[str, Any],
    *,
    index: int,
    lean_export_dir: Path,
    run_local_lean: bool,
    lean_project: Path | None,
    lean_timeout_seconds: int,
) -> dict[str, Any]:
    work_order_id = str(row.get("work_order_id", "") or "").strip() or f"work_order:{index}"
    lean_statement_sketch = str(row.get("lean_statement_sketch", "") or "").strip()
    check: dict[str, Any] = {
        "work_order_id": work_order_id,
        "question_id": str(row.get("question_id", "") or ""),
        "source_formal_target_id": str(row.get("source_formal_target_id", "") or ""),
        "target_lean_declaration": _lean_declaration_name(lean_statement_sketch),
        "target_theorem_goal_ids": list(row.get("target_theorem_goal_ids", []) or []),
        "verified_bridge_obligation_ids": list(row.get("verified_bridge_obligation_ids", []) or []),
        "lean_export_path": "",
        "status": "",
        "kernel_verified": False,
        "local_lean_attempted": False,
        "local_lean_returncode": None,
        "elapsed_ms": 0,
        "errors": [],
        "proof_evidence_status": "NO_KERNEL_VERIFIED_THEOREM_CLOSURE",
        "boundary": BOUNDARY,
    }

    if not lean_statement_sketch:
        check["status"] = "FORMAL_BLOCKED_MISSING_LEAN_STATEMENT"
        check["errors"] = ["work order has no lean_statement_sketch"]
        return check

    lean_export_path = (lean_export_dir / f"{_safe_filename(work_order_id)}.lean").resolve()
    lean_export_path.write_text(_lean_export_content(row, lean_statement_sketch), encoding="utf-8")
    check["lean_export_path"] = str(lean_export_path)

    if not _looks_like_lean_declaration(lean_statement_sketch):
        check["status"] = "FORMAL_BLOCKED_NO_THEOREM_LIKE_STATEMENT"
        check["errors"] = ["lean_statement_sketch does not contain a theorem/lemma/example/def declaration"]
        return check

    placeholder_errors = placeholder_proof_errors(lean_statement_sketch)
    if placeholder_errors:
        check["status"] = "PLACEHOLDER_REJECTED"
        check["errors"] = placeholder_errors
        return check

    if not run_local_lean:
        check["status"] = "QUEUED_NOT_CHECKED"
        check["errors"] = ["local Lean was not requested; exported sketch is not proof evidence"]
        return check

    if shutil.which("lake") is None:
        check["status"] = "FORMAL_BLOCKED_LOCAL_LEAN_UNAVAILABLE"
        check["errors"] = ["lake executable not found on PATH"]
        return check
    if lean_project is None:
        check["status"] = "FORMAL_BLOCKED_LOCAL_LEAN_PROJECT_MISSING"
        check["errors"] = ["no local Lean/Lake project found; pass --lean-project or set AI_STATISTICIAN_LEAN_PROJECT"]
        return check

    start = time.perf_counter()
    check["local_lean_attempted"] = True
    try:
        completed = subprocess.run(
            ["lake", "env", "lean", str(lean_export_path.resolve())],
            cwd=str(lean_project),
            capture_output=True,
            text=True,
            timeout=int(lean_timeout_seconds),
            check=False,
        )
    except subprocess.TimeoutExpired:
        check["status"] = "LOCAL_LEAN_TIMEOUT"
        check["elapsed_ms"] = int((time.perf_counter() - start) * 1000)
        check["errors"] = [f"local Lean timed out after {lean_timeout_seconds}s"]
        return check
    except Exception as exc:
        check["status"] = "LOCAL_LEAN_REJECTED"
        check["elapsed_ms"] = int((time.perf_counter() - start) * 1000)
        check["errors"] = [f"{type(exc).__name__}: {exc}"]
        return check

    check["elapsed_ms"] = int((time.perf_counter() - start) * 1000)
    check["local_lean_returncode"] = completed.returncode
    if completed.returncode == 0:
        check["status"] = "KERNEL_VERIFIED"
        check["kernel_verified"] = True
        check["proof_evidence_status"] = "KERNEL_VERIFIED_THEOREM_CLOSURE"
        return check

    output = "\n".join(part for part in (completed.stdout, completed.stderr) if part)
    check["status"] = "LOCAL_LEAN_REJECTED"
    check["errors"] = [line.strip() for line in output.splitlines() if line.strip()][:20]
    if not check["errors"]:
        check["errors"] = [f"local Lean returned exit code {completed.returncode}"]
    return check


def _read_jsonl(path: Path) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for line_no, raw_line in enumerate(path.read_text(encoding="utf-8").splitlines(), start=1):
        line = raw_line.strip()
        if not line:
            continue
        value = json.loads(line)
        if not isinstance(value, dict):
            raise ValueError(f"{path}:{line_no}: expected JSON object row")
        rows.append(value)
    return rows


def _write_jsonl(path: Path, rows: list[Mapping[str, Any]]) -> None:
    path.write_text(
        "".join(json.dumps(dict(row), sort_keys=True) + "\n" for row in rows),
        encoding="utf-8",
    )


def _lean_export_content(row: Mapping[str, Any], lean_statement_sketch: str) -> str:
    header = [
        "/-",
        "Generated from an AI Statistician theorem reduction closure work order.",
        "This file is not proof evidence unless local Lean/AXLE verifies it.",
        f"work_order_id: {row.get('work_order_id', '')}",
        f"source_formal_target_id: {row.get('source_formal_target_id', '')}",
        "-/",
        "",
    ]
    return "\n".join(header) + lean_statement_sketch.rstrip() + "\n"


def _looks_like_lean_declaration(content: str) -> bool:
    return bool(re.search(r"\b(theorem|lemma|example|def|abbrev)\b", content))


def _lean_declaration_name(content: str) -> str:
    match = re.search(
        r"(?m)^\s*(?:noncomputable\s+)?(?:private\s+)?"
        r"(?:theorem|lemma|def|abbrev)\s+([A-Za-z_][A-Za-z0-9_'.]*)",
        content,
    )
    return match.group(1) if match else ""


def _resolve_lean_project(project: Path | None) -> Path | None:
    candidates = (project,) if project else tuple(path for path in DEFAULT_LOCAL_LEAN_PROJECTS if path is not None)
    for candidate in candidates:
        if candidate is None:
            continue
        if (candidate / "lakefile.toml").exists() or (candidate / "lakefile.lean").exists():
            return candidate
    return None


def _safe_filename(value: str) -> str:
    cleaned = "".join(char if char.isalnum() or char in {"_", "-"} else "_" for char in value)
    cleaned = cleaned.strip("_-") or "work_order"
    return cleaned[:160]
