import StatInference.Optimization.ASGDStepContraction

/-!
# Chewi Chapter 12 general ASGD bridge

This module starts the Chewi Theorem 12.8 route.  It isolates the deterministic
bookkeeping that reduces the general ASGD recursion to the already formalized
quadratic ASGD endpoint plus the Taylor/Hessian residual `zeta`.
-/

namespace StatInference
namespace Optimization

open Filter MeasureTheory ProbabilityTheory
open StatInference.AsymptoticStatistics
open Finset
open scoped BigOperators Topology

/--
The source residual `zeta_n` enters the ASGD recursion in the same position as
the noise increment `xi_{n+1}`.  This shifted sequence has value `zeta_n` at
index `n+1` and a harmless zero at index `0`.
-/
def chewi128ShiftedResidual
    {Ω E : Type*} [Zero E] (zeta : ℕ -> Ω -> E) (n : ℕ) (ω : Ω) : E :=
  match n with
  | 0 => 0
  | k + 1 => zeta k ω

@[simp]
theorem chewi128ShiftedResidual_zero
    {Ω E : Type*} [Zero E] (zeta : ℕ -> Ω -> E) (ω : Ω) :
    chewi128ShiftedResidual zeta 0 ω = 0 := rfl

@[simp]
theorem chewi128ShiftedResidual_succ
    {Ω E : Type*} [Zero E] (zeta : ℕ -> Ω -> E) (n : ℕ) (ω : Ω) :
    chewi128ShiftedResidual zeta (n + 1) ω = zeta n ω := rfl

/--
The perturbed noise sequence `xi_n + zeta_{n-1}` used to view the general ASGD
recursion as a quadratic ASGD recursion.
-/
def chewi128PerturbedNoise
    {Ω E : Type*} [Zero E] [Add E]
    (xi zeta : ℕ -> Ω -> E) (n : ℕ) (ω : Ω) : E :=
  xi n ω + chewi128ShiftedResidual zeta n ω

@[simp]
theorem chewi128PerturbedNoise_succ
    {Ω E : Type*} [Zero E] [Add E]
    (xi zeta : ℕ -> Ω -> E) (n : ℕ) (ω : Ω) :
    chewi128PerturbedNoise xi zeta (n + 1) ω = xi (n + 1) ω + zeta n ω :=
  rfl

/-- The scaled martingale sum is additive in its increment sequence. -/
theorem chewi127ScaledNoiseSum_add
    {Ω E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
    (xi eta : ℕ -> Ω -> E) (N : ℕ) (ω : Ω) :
    chewi127ScaledNoiseSum (fun n ω => xi n ω + eta n ω) N ω =
      chewi127ScaledNoiseSum xi N ω + chewi127ScaledNoiseSum eta N ω := by
  simp [chewi127ScaledNoiseSum, Finset.sum_add_distrib, smul_add]

/-- The endpoint-corrected ASGD remainder is additive in its increment sequence. -/
theorem chewi123ASGDEndpointCorrectedRemainder_add
    {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
    (A Ainv : E →L[ℝ] E) (h : ℕ -> ℝ) (xi eta : ℕ -> E) (N : ℕ) :
    chewi123ASGDEndpointCorrectedRemainder A Ainv h
        (fun n => xi n + eta n) N =
      chewi123ASGDEndpointCorrectedRemainder A Ainv h xi N +
        chewi123ASGDEndpointCorrectedRemainder A Ainv h eta N := by
  simp [chewi123ASGDEndpointCorrectedRemainder, map_add,
    Finset.sum_add_distrib, smul_add]
  module

/--
The extra Chewi 12.8 contribution generated by the Taylor/Hessian residual
`zeta`.  The next analytic packet discharges that this term is `o_P(1)` from
the source estimate `E ||zeta_k|| = O(k^{-gamma})`.
-/
noncomputable def chewi128ASGDZetaContribution
    {Ω E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
    (A Ainv : E →L[ℝ] E) (h : ℕ -> ℝ)
    (zeta : ℕ -> Ω -> E) (N : ℕ) (ω : Ω) : E :=
  -Ainv (chewi127ScaledNoiseSum (chewi128ShiftedResidual zeta) N ω) +
    chewi123ASGDEndpointCorrectedRemainder A Ainv h
      (fun n => chewi128ShiftedResidual zeta n ω) N

/-- Deterministic envelope corresponding to `chewi128ShiftedResidual`. -/
def chewi128ShiftedResidualBound (b : ℕ -> ℝ) (n : ℕ) : ℝ :=
  match n with
  | 0 => 0
  | k + 1 => b k

@[simp]
theorem chewi128ShiftedResidualBound_zero (b : ℕ -> ℝ) :
    chewi128ShiftedResidualBound b 0 = 0 := rfl

@[simp]
theorem chewi128ShiftedResidualBound_succ (b : ℕ -> ℝ) (n : ℕ) :
    chewi128ShiftedResidualBound b (n + 1) = b n := rfl

theorem chewi128ShiftedResidual_norm_le_bound
    {Ω E : Type*} [NormedAddCommGroup E] (zeta : ℕ -> Ω -> E)
    (b : ℕ -> ℝ) (hzeta_bound : ∀ n ω, ‖zeta n ω‖ ≤ b n)
    (n : ℕ) (ω : Ω) :
    ‖chewi128ShiftedResidual zeta n ω‖ ≤
      chewi128ShiftedResidualBound b n := by
  cases n with
  | zero => simp [chewi128ShiftedResidual, chewi128ShiftedResidualBound]
  | succ k => simpa using hzeta_bound k ω

theorem chewi128ShiftedResidualBound_nonneg
    (b : ℕ -> ℝ) (hb_nonneg : ∀ n, 0 ≤ b n) (n : ℕ) :
    0 ≤ chewi128ShiftedResidualBound b n := by
  cases n with
  | zero => simp
  | succ k => simpa using hb_nonneg k

theorem chewi128ShiftedResidual_norm_eq_shiftedResidualBound_norm
    {Ω E : Type*} [NormedAddCommGroup E] (zeta : ℕ -> Ω -> E)
    (n : ℕ) (ω : Ω) :
    ‖chewi128ShiftedResidual zeta n ω‖ =
      chewi128ShiftedResidualBound (fun k => ‖zeta k ω‖) n := by
  cases n with
  | zero => simp [chewi128ShiftedResidual, chewi128ShiftedResidualBound]
  | succ k => simp [chewi128ShiftedResidual, chewi128ShiftedResidualBound]

theorem chewi128ShiftedResidualBound_le_sum_range
    (b : ℕ -> ℝ) (hb_nonneg : ∀ n, 0 ≤ b n) (N : ℕ) :
    chewi128ShiftedResidualBound b N ≤ ∑ k ∈ Finset.range N, b k := by
  cases N with
  | zero => simp
  | succ n =>
      simpa using
        Finset.single_le_sum
          (s := Finset.range (n + 1)) (a := n) (f := b)
          (fun k _hk => hb_nonneg k)
          (Finset.mem_range.mpr (Nat.lt_succ_self n))

theorem chewi128_sum_Ico_shiftedResidualBound_le_sum_range
    (b : ℕ -> ℝ) (hb_nonneg : ∀ n, 0 ≤ b n) (N : ℕ) :
    (∑ k ∈ Finset.Ico 1 N, chewi128ShiftedResidualBound b k) ≤
      ∑ k ∈ Finset.range N, b k := by
  calc
    (∑ k ∈ Finset.Ico 1 N, chewi128ShiftedResidualBound b k) =
        ∑ k ∈ Finset.range (N - 1), b k := by
      rw [Finset.sum_Ico_eq_sum_range]
      refine Finset.sum_congr rfl ?_
      intro k _hk
      rw [Nat.add_comm 1 k]
      simp
    _ ≤ ∑ k ∈ Finset.range N, b k := by
      refine Finset.sum_le_sum_of_subset_of_nonneg ?_ ?_
      · intro k hk
        exact Finset.mem_range.mpr
          ((Finset.mem_range.mp hk).trans_le (Nat.sub_le N 1))
      · intro k _hk _hnot
        exact hb_nonneg k

theorem chewi128_sum_Ico_coeff_shiftedResidualBound_le_uniform_mul_sum_range
    {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
    (A Ainv : E →L[ℝ] E) (h : ℕ -> ℝ)
    (b : ℕ -> ℝ) (K : ℝ)
    (hb_nonneg : ∀ n, 0 ≤ b n) (hK_nonneg : 0 ≤ K)
    (hcoeff_bound : ∀ N k, k ∈ Finset.Ico 1 N ->
      ‖chewi123SourceNoiseCoefficient A h k N - Ainv‖ ≤ K)
    (N : ℕ) :
    (∑ k ∈ Finset.Ico 1 N,
        ‖chewi123SourceNoiseCoefficient A h k N - Ainv‖ *
          chewi128ShiftedResidualBound b k) ≤
      K * ∑ k ∈ Finset.range N, b k := by
  calc
    (∑ k ∈ Finset.Ico 1 N,
        ‖chewi123SourceNoiseCoefficient A h k N - Ainv‖ *
          chewi128ShiftedResidualBound b k) ≤
        ∑ k ∈ Finset.Ico 1 N,
          K * chewi128ShiftedResidualBound b k := by
      refine Finset.sum_le_sum fun k hk => ?_
      exact
        mul_le_mul_of_nonneg_right
          (hcoeff_bound N k hk)
          (chewi128ShiftedResidualBound_nonneg b hb_nonneg k)
    _ = K * ∑ k ∈ Finset.Ico 1 N, chewi128ShiftedResidualBound b k := by
      rw [Finset.mul_sum]
    _ ≤ K * ∑ k ∈ Finset.range N, b k :=
      mul_le_mul_of_nonneg_left
        (chewi128_sum_Ico_shiftedResidualBound_le_sum_range b hb_nonneg N)
        hK_nonneg

/--
Pointwise deterministic upper bound for the Chewi 12.8 `zeta` contribution.
The first row controls the extra scaled-noise sum and the second row controls
the endpoint-correction remainder.
-/
noncomputable def chewi128ASGDZetaContributionPointwiseBound
    {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
    (A Ainv : E →L[ℝ] E) (h : ℕ -> ℝ) (b : ℕ -> ℝ) (N : ℕ) : ℝ :=
  ‖(Real.sqrt (N : ℝ))⁻¹‖ * ‖Ainv‖ *
      ∑ k ∈ Finset.range N, b k +
    (‖(Real.sqrt (N : ℝ))⁻¹‖ * ‖Ainv‖ *
        chewi128ShiftedResidualBound b N +
      ‖(Real.sqrt (N : ℝ))⁻¹‖ *
        ∑ k ∈ Finset.Ico 1 N,
          ‖chewi123SourceNoiseCoefficient A h k N - Ainv‖ *
            chewi128ShiftedResidualBound b k)

theorem chewi128_neg_inverse_scaled_shiftedResidual_norm_le_bound
    {Ω E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
    (Ainv : E →L[ℝ] E) (zeta : ℕ -> Ω -> E) (b : ℕ -> ℝ)
    (hzeta_bound : ∀ n ω, ‖zeta n ω‖ ≤ b n)
    (N : ℕ) (ω : Ω) :
    ‖-Ainv (chewi127ScaledNoiseSum (chewi128ShiftedResidual zeta) N ω)‖ ≤
      ‖(Real.sqrt (N : ℝ))⁻¹‖ * ‖Ainv‖ *
        ∑ k ∈ Finset.range N, b k := by
  let c : ℝ := (Real.sqrt (N : ℝ))⁻¹
  have hsum :
      ‖∑ k ∈ Finset.range N, chewi128ShiftedResidual zeta (k + 1) ω‖ ≤
        ∑ k ∈ Finset.range N, b k := by
    calc
      ‖∑ k ∈ Finset.range N, chewi128ShiftedResidual zeta (k + 1) ω‖ ≤
          ∑ k ∈ Finset.range N, ‖chewi128ShiftedResidual zeta (k + 1) ω‖ := by
        simpa using
          norm_sum_le
            (s := Finset.range N)
            (f := fun k => chewi128ShiftedResidual zeta (k + 1) ω)
      _ ≤ ∑ k ∈ Finset.range N, b k :=
        Finset.sum_le_sum fun k _hk => by
          simpa using hzeta_bound k ω
  calc
    ‖-Ainv (chewi127ScaledNoiseSum (chewi128ShiftedResidual zeta) N ω)‖ =
        ‖Ainv (c • ∑ k ∈ Finset.range N,
          chewi128ShiftedResidual zeta (k + 1) ω)‖ := by
      simp [chewi127ScaledNoiseSum, c]
    _ ≤ ‖Ainv‖ *
        ‖c • ∑ k ∈ Finset.range N,
          chewi128ShiftedResidual zeta (k + 1) ω‖ :=
      Ainv.le_opNorm _
    _ = ‖Ainv‖ *
        (‖c‖ *
          ‖∑ k ∈ Finset.range N, chewi128ShiftedResidual zeta (k + 1) ω‖) := by
      simp [norm_smul]
    _ ≤ ‖Ainv‖ * (‖c‖ * ∑ k ∈ Finset.range N, b k) :=
      mul_le_mul_of_nonneg_left
        (mul_le_mul_of_nonneg_left hsum (norm_nonneg _))
        (norm_nonneg _)
    _ = ‖(Real.sqrt (N : ℝ))⁻¹‖ * ‖Ainv‖ *
        ∑ k ∈ Finset.range N, b k := by
      ring

theorem chewi128_endpoint_corrected_shiftedResidual_norm_le_bound
    {Ω E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
    (A Ainv : E →L[ℝ] E) (h : ℕ -> ℝ)
    (zeta : ℕ -> Ω -> E) (b : ℕ -> ℝ)
    (hzeta_bound : ∀ n ω, ‖zeta n ω‖ ≤ b n)
    (N : ℕ) (ω : Ω) :
    ‖chewi123ASGDEndpointCorrectedRemainder A Ainv h
        (fun n => chewi128ShiftedResidual zeta n ω) N‖ ≤
      ‖(Real.sqrt (N : ℝ))⁻¹‖ * ‖Ainv‖ *
          chewi128ShiftedResidualBound b N +
        ‖(Real.sqrt (N : ℝ))⁻¹‖ *
          ∑ k ∈ Finset.Ico 1 N,
            ‖chewi123SourceNoiseCoefficient A h k N - Ainv‖ *
              chewi128ShiftedResidualBound b k := by
  have hbase :=
    chewi123ASGDEndpointCorrectedRemainder_norm_le_opNorm_sum
      A Ainv h (fun n => chewi128ShiftedResidual zeta n ω) N
  refine hbase.trans (add_le_add ?_ ?_)
  · exact
      mul_le_mul_of_nonneg_left
        (chewi128ShiftedResidual_norm_le_bound zeta b hzeta_bound N ω)
        (mul_nonneg (norm_nonneg _) (norm_nonneg _))
  · refine
      mul_le_mul_of_nonneg_left
        (Finset.sum_le_sum fun k _hk => ?_)
        (norm_nonneg _)
    exact
      mul_le_mul_of_nonneg_left
        (chewi128ShiftedResidual_norm_le_bound zeta b hzeta_bound k ω)
        (norm_nonneg _)

theorem chewi128ASGDZetaContribution_norm_le_pointwiseBound
    {Ω E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
    (A Ainv : E →L[ℝ] E) (h : ℕ -> ℝ)
    (zeta : ℕ -> Ω -> E) (b : ℕ -> ℝ)
    (hzeta_bound : ∀ n ω, ‖zeta n ω‖ ≤ b n)
    (N : ℕ) (ω : Ω) :
    ‖chewi128ASGDZetaContribution A Ainv h zeta N ω‖ ≤
      chewi128ASGDZetaContributionPointwiseBound A Ainv h b N := by
  have hfirst :=
    chewi128_neg_inverse_scaled_shiftedResidual_norm_le_bound
      Ainv zeta b hzeta_bound N ω
  have hsecond :=
    chewi128_endpoint_corrected_shiftedResidual_norm_le_bound
      A Ainv h zeta b hzeta_bound N ω
  calc
    ‖chewi128ASGDZetaContribution A Ainv h zeta N ω‖ ≤
        ‖-Ainv (chewi127ScaledNoiseSum (chewi128ShiftedResidual zeta) N ω)‖ +
          ‖chewi123ASGDEndpointCorrectedRemainder A Ainv h
              (fun n => chewi128ShiftedResidual zeta n ω) N‖ := by
      simpa [chewi128ASGDZetaContribution] using
        norm_add_le
          (-Ainv (chewi127ScaledNoiseSum (chewi128ShiftedResidual zeta) N ω))
          (chewi123ASGDEndpointCorrectedRemainder A Ainv h
            (fun n => chewi128ShiftedResidual zeta n ω) N)
    _ ≤ chewi128ASGDZetaContributionPointwiseBound A Ainv h b N := by
      simpa [chewi128ASGDZetaContributionPointwiseBound] using
        add_le_add hfirst hsecond

theorem chewi128_neg_inverse_scaled_shiftedResidual_norm_le_sum_norm
    {Ω E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
    (Ainv : E →L[ℝ] E) (zeta : ℕ -> Ω -> E)
    (N : ℕ) (ω : Ω) :
    ‖-Ainv (chewi127ScaledNoiseSum (chewi128ShiftedResidual zeta) N ω)‖ ≤
      ‖(Real.sqrt (N : ℝ))⁻¹‖ * ‖Ainv‖ *
        ∑ k ∈ Finset.range N, ‖zeta k ω‖ := by
  let c : ℝ := (Real.sqrt (N : ℝ))⁻¹
  have hsum :
      ‖∑ k ∈ Finset.range N, chewi128ShiftedResidual zeta (k + 1) ω‖ ≤
        ∑ k ∈ Finset.range N, ‖zeta k ω‖ := by
    calc
      ‖∑ k ∈ Finset.range N, chewi128ShiftedResidual zeta (k + 1) ω‖ ≤
          ∑ k ∈ Finset.range N, ‖chewi128ShiftedResidual zeta (k + 1) ω‖ := by
        simpa using
          norm_sum_le
            (s := Finset.range N)
            (f := fun k => chewi128ShiftedResidual zeta (k + 1) ω)
      _ = ∑ k ∈ Finset.range N, ‖zeta k ω‖ := by
        simp
  calc
    ‖-Ainv (chewi127ScaledNoiseSum (chewi128ShiftedResidual zeta) N ω)‖ =
        ‖Ainv (c • ∑ k ∈ Finset.range N,
          chewi128ShiftedResidual zeta (k + 1) ω)‖ := by
      simp [chewi127ScaledNoiseSum, c]
    _ ≤ ‖Ainv‖ *
        ‖c • ∑ k ∈ Finset.range N,
          chewi128ShiftedResidual zeta (k + 1) ω‖ :=
      Ainv.le_opNorm _
    _ = ‖Ainv‖ *
        (‖c‖ *
          ‖∑ k ∈ Finset.range N, chewi128ShiftedResidual zeta (k + 1) ω‖) := by
      simp [norm_smul]
    _ ≤ ‖Ainv‖ *
        (‖c‖ * ∑ k ∈ Finset.range N, ‖zeta k ω‖) :=
      mul_le_mul_of_nonneg_left
        (mul_le_mul_of_nonneg_left hsum (norm_nonneg _))
        (norm_nonneg _)
    _ = ‖(Real.sqrt (N : ℝ))⁻¹‖ * ‖Ainv‖ *
        ∑ k ∈ Finset.range N, ‖zeta k ω‖ := by
      ring

theorem chewi128_endpoint_corrected_shiftedResidual_norm_le_sum_norm
    {Ω E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
    (A Ainv : E →L[ℝ] E) (h : ℕ -> ℝ)
    (zeta : ℕ -> Ω -> E) (N : ℕ) (ω : Ω) :
    ‖chewi123ASGDEndpointCorrectedRemainder A Ainv h
        (fun n => chewi128ShiftedResidual zeta n ω) N‖ ≤
      ‖(Real.sqrt (N : ℝ))⁻¹‖ * ‖Ainv‖ *
          chewi128ShiftedResidualBound (fun k => ‖zeta k ω‖) N +
        ‖(Real.sqrt (N : ℝ))⁻¹‖ *
          ∑ k ∈ Finset.Ico 1 N,
            ‖chewi123SourceNoiseCoefficient A h k N - Ainv‖ *
              chewi128ShiftedResidualBound (fun j => ‖zeta j ω‖) k := by
  simpa [chewi128ShiftedResidual_norm_eq_shiftedResidualBound_norm] using
    chewi123ASGDEndpointCorrectedRemainder_norm_le_opNorm_sum
      A Ainv h (fun n => chewi128ShiftedResidual zeta n ω) N

theorem chewi128ASGDZetaContribution_norm_le_source_row_of_uniform_coeff_bound
    {Ω E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
    (A Ainv : E →L[ℝ] E) (h : ℕ -> ℝ)
    (zeta : ℕ -> Ω -> E) (K : ℝ)
    (hK_nonneg : 0 ≤ K)
    (hcoeff_bound : ∀ N k, k ∈ Finset.Ico 1 N ->
      ‖chewi123SourceNoiseCoefficient A h k N - Ainv‖ ≤ K)
    (N : ℕ) (ω : Ω) :
    ‖chewi128ASGDZetaContribution A Ainv h zeta N ω‖ ≤
      (2 * ‖Ainv‖ + K) *
        (‖(Real.sqrt (N : ℝ))⁻¹‖ *
          ∑ k ∈ Finset.range N, ‖zeta k ω‖) := by
  let b : ℕ -> ℝ := fun k => ‖zeta k ω‖
  let c : ℝ := ‖(Real.sqrt (N : ℝ))⁻¹‖
  let S : ℝ := ∑ k ∈ Finset.range N, b k
  have hb_nonneg : ∀ n, 0 ≤ b n := fun n => norm_nonneg _
  have hfirst :
      ‖-Ainv (chewi127ScaledNoiseSum (chewi128ShiftedResidual zeta) N ω)‖ ≤
        c * ‖Ainv‖ * S := by
    simpa [b, c, S] using
      chewi128_neg_inverse_scaled_shiftedResidual_norm_le_sum_norm
        Ainv zeta N ω
  have hsecond :
      ‖chewi123ASGDEndpointCorrectedRemainder A Ainv h
          (fun n => chewi128ShiftedResidual zeta n ω) N‖ ≤
        c * ‖Ainv‖ * chewi128ShiftedResidualBound b N +
          c *
            ∑ k ∈ Finset.Ico 1 N,
              ‖chewi123SourceNoiseCoefficient A h k N - Ainv‖ *
                chewi128ShiftedResidualBound b k := by
    simpa [b, c] using
      chewi128_endpoint_corrected_shiftedResidual_norm_le_sum_norm
        A Ainv h zeta N ω
  have hshift :
      chewi128ShiftedResidualBound b N ≤ S :=
    chewi128ShiftedResidualBound_le_sum_range b hb_nonneg N
  have hcoeff_sum :
      (∑ k ∈ Finset.Ico 1 N,
          ‖chewi123SourceNoiseCoefficient A h k N - Ainv‖ *
            chewi128ShiftedResidualBound b k) ≤ K * S :=
    chewi128_sum_Ico_coeff_shiftedResidualBound_le_uniform_mul_sum_range
      A Ainv h b K hb_nonneg hK_nonneg hcoeff_bound N
  have hsecond_to_row :
      c * ‖Ainv‖ * chewi128ShiftedResidualBound b N +
          c *
            ∑ k ∈ Finset.Ico 1 N,
              ‖chewi123SourceNoiseCoefficient A h k N - Ainv‖ *
                chewi128ShiftedResidualBound b k ≤
        c * ‖Ainv‖ * S + c * (K * S) := by
    exact
      add_le_add
        (mul_le_mul_of_nonneg_left hshift
          (mul_nonneg (norm_nonneg _) (norm_nonneg _)))
        (mul_le_mul_of_nonneg_left hcoeff_sum (norm_nonneg _))
  calc
    ‖chewi128ASGDZetaContribution A Ainv h zeta N ω‖ ≤
        ‖-Ainv (chewi127ScaledNoiseSum (chewi128ShiftedResidual zeta) N ω)‖ +
          ‖chewi123ASGDEndpointCorrectedRemainder A Ainv h
              (fun n => chewi128ShiftedResidual zeta n ω) N‖ := by
      simpa [chewi128ASGDZetaContribution] using
        norm_add_le
          (-Ainv (chewi127ScaledNoiseSum (chewi128ShiftedResidual zeta) N ω))
          (chewi123ASGDEndpointCorrectedRemainder A Ainv h
            (fun n => chewi128ShiftedResidual zeta n ω) N)
    _ ≤ c * ‖Ainv‖ * S + (c * ‖Ainv‖ * S + c * (K * S)) :=
      add_le_add hfirst (hsecond.trans hsecond_to_row)
    _ = (2 * ‖Ainv‖ + K) * (c * S) := by
      ring

/--
Source-facing stochastic-o handoff for the Chewi 12.8 residual.  A later packet
will discharge the displayed deterministic decay from the textbook's
`(sqrt N)^{-1} sum E ||zeta_k|| -> 0` estimate and Taylor/Hessian bounds.
-/
theorem chewi128ASGDZetaContribution_tendstoInMeasure_zero_of_pointwise_bound
    {Ω E : Type*} [MeasurableSpace Ω] {P : Measure Ω}
    [NormedAddCommGroup E] [NormedSpace ℝ E]
    (A Ainv : E →L[ℝ] E) (h : ℕ -> ℝ)
    (zeta : ℕ -> Ω -> E) (b : ℕ -> ℝ)
    (hzeta_bound : ∀ n ω, ‖zeta n ω‖ ≤ b n)
    (hbound_tendsto :
      Tendsto
        (chewi128ASGDZetaContributionPointwiseBound A Ainv h b)
        atTop (𝓝 0)) :
    TendstoInMeasure P
      (fun N ω => chewi128ASGDZetaContribution A Ainv h zeta N ω)
      atTop (fun _ => 0) := by
  simpa [StochasticLittleO] using
    vaart1998_stochastic_littleO_of_uniform_norm_bound
      (P := P)
      (X := fun N ω => chewi128ASGDZetaContribution A Ainv h zeta N ω)
      (a := chewi128ASGDZetaContributionPointwiseBound A Ainv h b)
      hbound_tendsto
      (Eventually.of_forall fun N ω =>
        chewi128ASGDZetaContribution_norm_le_pointwiseBound
          A Ainv h zeta b hzeta_bound N ω)

/--
Markov/L1 handoff: convergence to zero in expected norm implies convergence in
measure.  This is the reusable probability step behind Chewi's residual
estimate in Theorem 12.8.
-/
theorem tendstoInMeasure_zero_of_integral_norm_tendsto_zero
    {Ω E : Type*} [MeasurableSpace Ω] {P : Measure Ω}
    [IsFiniteMeasure P] [SeminormedAddCommGroup E]
    {X : ℕ -> Ω -> E}
    (hX_int : ∀ n, Integrable (fun ω => ‖X n ω‖) P)
    (hL1 : Tendsto (fun n => ∫ ω, ‖X n ω‖ ∂P) atTop (𝓝 (0 : ℝ))) :
    TendstoInMeasure P X atTop (fun _ => 0) := by
  rw [MeasureTheory.tendstoInMeasure_iff_measureReal_norm]
  intro ε hε
  have hε_nonneg : 0 ≤ ε := le_of_lt hε
  have hupper :
      ∀ n,
        P.real {ω | ε ≤ ‖X n ω - (0 : E)‖} ≤
          ε⁻¹ * ∫ ω, ‖X n ω‖ ∂P := by
    intro n
    have hmarkov :
        ε * P.real {ω | ε ≤ ‖X n ω - (0 : E)‖} ≤
          ∫ ω, ‖X n ω‖ ∂P := by
      simpa [sub_zero] using
        MeasureTheory.mul_meas_ge_le_integral_of_nonneg
          (μ := P) (f := fun ω => ‖X n ω‖)
          (Eventually.of_forall fun _ => norm_nonneg _)
          (hX_int n) ε
    calc
      P.real {ω | ε ≤ ‖X n ω - (0 : E)‖} =
          ε⁻¹ * (ε * P.real {ω | ε ≤ ‖X n ω - (0 : E)‖}) := by
        field_simp [ne_of_gt hε]
      _ ≤ ε⁻¹ * ∫ ω, ‖X n ω‖ ∂P :=
        mul_le_mul_of_nonneg_left hmarkov (inv_nonneg.mpr hε_nonneg)
  have hright :
      Tendsto (fun n => ε⁻¹ * ∫ ω, ‖X n ω‖ ∂P) atTop (𝓝 0) := by
    simpa using hL1.const_mul ε⁻¹
  exact
    tendsto_of_tendsto_of_tendsto_of_le_of_le
      tendsto_const_nhds hright
      (fun _ => MeasureTheory.measureReal_nonneg)
      hupper

/--
Deterministic L1-bound version of the Chewi 12.8 residual handoff.  The caller
may prove the displayed integral bound from the source estimate
`(sqrt N)^{-1} sum E ||zeta_k|| -> 0` and coefficient-row boundedness.
-/
theorem chewi128ASGDZetaContribution_tendstoInMeasure_zero_of_integral_norm_bound
    {Ω E : Type*} [MeasurableSpace Ω] {P : Measure Ω}
    [IsFiniteMeasure P]
    [NormedAddCommGroup E] [NormedSpace ℝ E]
    (A Ainv : E →L[ℝ] E) (h : ℕ -> ℝ)
    (zeta : ℕ -> Ω -> E) (B : ℕ -> ℝ)
    (hZeta_int :
      ∀ N,
        Integrable
          (fun ω => ‖chewi128ASGDZetaContribution A Ainv h zeta N ω‖) P)
    (hZeta_l1_bound :
      ∀ N,
        ∫ ω, ‖chewi128ASGDZetaContribution A Ainv h zeta N ω‖ ∂P ≤ B N)
    (hB_tendsto : Tendsto B atTop (𝓝 0)) :
    TendstoInMeasure P
      (fun N ω => chewi128ASGDZetaContribution A Ainv h zeta N ω)
      atTop (fun _ => 0) := by
  refine
    tendstoInMeasure_zero_of_integral_norm_tendsto_zero
      (P := P)
      (X := fun N ω => chewi128ASGDZetaContribution A Ainv h zeta N ω)
      hZeta_int ?_
  exact
    tendsto_of_tendsto_of_tendsto_of_le_of_le
      tendsto_const_nhds hB_tendsto
      (fun _ => integral_nonneg fun _ => norm_nonneg _)
      hZeta_l1_bound

/--
Source-shaped L1 gate for Chewi Theorem 12.8.  Once the contribution's expected
norm is bounded by a constant times the textbook row
`(sqrt N)^{-1} sum_{k<N} E ||zeta_k||`, the source row convergence gives the
required residual `o_P(1)`.
-/
theorem chewi128ASGDZetaContribution_tendstoInMeasure_zero_of_source_l1_bound
    {Ω E : Type*} [MeasurableSpace Ω] {P : Measure Ω}
    [IsFiniteMeasure P]
    [NormedAddCommGroup E] [NormedSpace ℝ E]
    (A Ainv : E →L[ℝ] E) (h : ℕ -> ℝ)
    (zeta : ℕ -> Ω -> E) (K : ℝ)
    (hZetaContribution_int :
      ∀ N,
        Integrable
          (fun ω => ‖chewi128ASGDZetaContribution A Ainv h zeta N ω‖) P)
    (hContribution_l1_bound :
      ∀ N,
        ∫ ω, ‖chewi128ASGDZetaContribution A Ainv h zeta N ω‖ ∂P ≤
          (2 * ‖Ainv‖ + K) *
            (‖(Real.sqrt (N : ℝ))⁻¹‖ *
              ∑ k ∈ Finset.range N, ∫ ω, ‖zeta k ω‖ ∂P))
    (hSource_l1 :
      Tendsto
        (fun N : ℕ =>
          ‖(Real.sqrt (N : ℝ))⁻¹‖ *
            ∑ k ∈ Finset.range N, ∫ ω, ‖zeta k ω‖ ∂P)
        atTop (𝓝 0)) :
    TendstoInMeasure P
      (fun N ω => chewi128ASGDZetaContribution A Ainv h zeta N ω)
      atTop (fun _ => 0) := by
  refine
    chewi128ASGDZetaContribution_tendstoInMeasure_zero_of_integral_norm_bound
      A Ainv h zeta
      (fun N : ℕ =>
        (2 * ‖Ainv‖ + K) *
          (‖(Real.sqrt (N : ℝ))⁻¹‖ *
            ∑ k ∈ Finset.range N, ∫ ω, ‖zeta k ω‖ ∂P))
      hZetaContribution_int hContribution_l1_bound ?_
  simpa using hSource_l1.const_mul (2 * ‖Ainv‖ + K)

/--
Expected-norm row bound for the Chewi 12.8 `zeta` contribution under a
uniform residual-coefficient bound.  This is the source proof's step that
reduces the extra residual to `(sqrt N)^{-1} sum E ||zeta_k||`.
-/
theorem chewi128ASGDZetaContribution_integral_norm_le_source_l1_row_of_uniform_coeff_bound
    {Ω E : Type*} [MeasurableSpace Ω] {P : Measure Ω}
    [NormedAddCommGroup E] [NormedSpace ℝ E]
    (A Ainv : E →L[ℝ] E) (h : ℕ -> ℝ)
    (zeta : ℕ -> Ω -> E) (K : ℝ)
    (hK_nonneg : 0 ≤ K)
    (hcoeff_bound : ∀ N k, k ∈ Finset.Ico 1 N ->
      ‖chewi123SourceNoiseCoefficient A h k N - Ainv‖ ≤ K)
    (hzeta_int : ∀ k, Integrable (fun ω => ‖zeta k ω‖) P)
    (hZetaContribution_int :
      ∀ N,
        Integrable
          (fun ω => ‖chewi128ASGDZetaContribution A Ainv h zeta N ω‖) P)
    (N : ℕ) :
    ∫ ω, ‖chewi128ASGDZetaContribution A Ainv h zeta N ω‖ ∂P ≤
      (2 * ‖Ainv‖ + K) *
        (‖(Real.sqrt (N : ℝ))⁻¹‖ *
          ∑ k ∈ Finset.range N, ∫ ω, ‖zeta k ω‖ ∂P) := by
  let C : ℝ := 2 * ‖Ainv‖ + K
  let c : ℝ := ‖(Real.sqrt (N : ℝ))⁻¹‖
  have hsum_int :
      Integrable (fun ω => ∑ k ∈ Finset.range N, ‖zeta k ω‖) P := by
    refine integrable_finsetSum (Finset.range N) ?_
    intro k _hk
    exact hzeta_int k
  have hrow_int :
      Integrable
        (fun ω => C * (c * ∑ k ∈ Finset.range N, ‖zeta k ω‖)) P := by
    simpa [C, c, mul_assoc, mul_comm, mul_left_comm] using
      ((hsum_int.const_mul c).const_mul C)
  have hpoint :
      (fun ω =>
        ‖chewi128ASGDZetaContribution A Ainv h zeta N ω‖) ≤ᵐ[P]
      fun ω => C * (c * ∑ k ∈ Finset.range N, ‖zeta k ω‖) := by
    exact Eventually.of_forall fun ω => by
      simpa [C, c, mul_assoc, mul_comm, mul_left_comm] using
        chewi128ASGDZetaContribution_norm_le_source_row_of_uniform_coeff_bound
          A Ainv h zeta K hK_nonneg hcoeff_bound N ω
  calc
    ∫ ω, ‖chewi128ASGDZetaContribution A Ainv h zeta N ω‖ ∂P ≤
        ∫ ω, C * (c * ∑ k ∈ Finset.range N, ‖zeta k ω‖) ∂P :=
      integral_mono_ae (hZetaContribution_int N) hrow_int hpoint
    _ = C * (c * ∑ k ∈ Finset.range N, ∫ ω, ‖zeta k ω‖ ∂P) := by
      rw [integral_const_mul]
      rw [integral_const_mul]
      rw [integral_finsetSum]
      intro k _hk
      exact hzeta_int k
    _ = (2 * ‖Ainv‖ + K) *
        (‖(Real.sqrt (N : ℝ))⁻¹‖ *
          ∑ k ∈ Finset.range N, ∫ ω, ‖zeta k ω‖ ∂P) := by
      simp [C, c]

/--
Source-facing Chewi 12.8 residual theorem under a uniform coefficient bound
and the source L1 row convergence.
-/
theorem chewi128ASGDZetaContribution_tendstoInMeasure_zero_of_source_l1_and_uniform_coeff_bound
    {Ω E : Type*} [MeasurableSpace Ω] {P : Measure Ω}
    [IsFiniteMeasure P]
    [NormedAddCommGroup E] [NormedSpace ℝ E]
    (A Ainv : E →L[ℝ] E) (h : ℕ -> ℝ)
    (zeta : ℕ -> Ω -> E) (K : ℝ)
    (hK_nonneg : 0 ≤ K)
    (hcoeff_bound : ∀ N k, k ∈ Finset.Ico 1 N ->
      ‖chewi123SourceNoiseCoefficient A h k N - Ainv‖ ≤ K)
    (hzeta_int : ∀ k, Integrable (fun ω => ‖zeta k ω‖) P)
    (hZetaContribution_int :
      ∀ N,
        Integrable
          (fun ω => ‖chewi128ASGDZetaContribution A Ainv h zeta N ω‖) P)
    (hSource_l1 :
      Tendsto
        (fun N : ℕ =>
          ‖(Real.sqrt (N : ℝ))⁻¹‖ *
            ∑ k ∈ Finset.range N, ∫ ω, ‖zeta k ω‖ ∂P)
        atTop (𝓝 0)) :
    TendstoInMeasure P
      (fun N ω => chewi128ASGDZetaContribution A Ainv h zeta N ω)
      atTop (fun _ => 0) := by
  refine
    chewi128ASGDZetaContribution_tendstoInMeasure_zero_of_source_l1_bound
      A Ainv h zeta K hZetaContribution_int ?_ hSource_l1
  intro N
  exact
    chewi128ASGDZetaContribution_integral_norm_le_source_l1_row_of_uniform_coeff_bound
      A Ainv h zeta K hK_nonneg hcoeff_bound hzeta_int
      hZetaContribution_int N

/--
If a deterministic row has order `N^beta` with `beta < 1/2`, then multiplying
by `1 / sqrt N` sends it to zero.  This is the finite-power analytic gate for
Chewi's `gamma > 1/2` residual estimate.
-/
theorem chewi128_sqrt_inv_mul_power_tendsto_zero
    (D beta : ℝ) (hbeta_lt : beta < (1 : ℝ) / 2) :
    Tendsto
      (fun N : ℕ => ‖(Real.sqrt (N : ℝ))⁻¹‖ * (D * (N : ℝ) ^ beta))
      atTop (𝓝 0) := by
  have hpow :
      Tendsto (fun x : ℝ => x ^ (beta - (1 : ℝ) / 2)) atTop (𝓝 0) := by
    simpa [sub_eq_add_neg] using
      (tendsto_rpow_neg_atTop
        (show 0 < (1 : ℝ) / 2 - beta by linarith))
  have hnat :
      Tendsto
        (fun N : ℕ => (N : ℝ) ^ (beta - (1 : ℝ) / 2))
        atTop (𝓝 0) :=
    hpow.comp tendsto_natCast_atTop_atTop
  have hD :
      Tendsto
        (fun N : ℕ => D * (N : ℝ) ^ (beta - (1 : ℝ) / 2))
        atTop (𝓝 0) := by
    simpa using
      (tendsto_const_nhds.mul hnat :
        Tendsto
          (fun N : ℕ => D * (N : ℝ) ^ (beta - (1 : ℝ) / 2))
          atTop (𝓝 (D * 0)))
  refine hD.congr' ?_
  refine eventually_atTop.2 ⟨1, ?_⟩
  intro N hN
  have hNpos : 0 < (N : ℝ) := by exact_mod_cast hN
  have hNnonneg : 0 ≤ (N : ℝ) := le_of_lt hNpos
  have hsqrt_nonneg : 0 ≤ (Real.sqrt (N : ℝ))⁻¹ :=
    inv_nonneg.mpr (Real.sqrt_nonneg _)
  symm
  calc
    ‖(Real.sqrt (N : ℝ))⁻¹‖ * (D * (N : ℝ) ^ beta)
        = (Real.sqrt (N : ℝ))⁻¹ * (D * (N : ℝ) ^ beta) := by
          rw [Real.norm_eq_abs, abs_of_nonneg hsqrt_nonneg]
    _ = ((N : ℝ) ^ ((1 : ℝ) / 2))⁻¹ * (D * (N : ℝ) ^ beta) := by
          rw [Real.sqrt_eq_rpow]
    _ = (N : ℝ) ^ (-((1 : ℝ) / 2)) * (D * (N : ℝ) ^ beta) := by
          rw [← Real.rpow_neg hNnonneg ((1 : ℝ) / 2)]
    _ = D * ((N : ℝ) ^ beta * (N : ℝ) ^ (-((1 : ℝ) / 2))) := by ring
    _ = D * (N : ℝ) ^ (beta - (1 : ℝ) / 2) := by
          rw [← Real.rpow_add hNpos]
          ring_nf

/--
Squeeze form of `chewi128_sqrt_inv_mul_power_tendsto_zero`: an eventually
nonnegative row bounded by `D * N^beta`, `beta < 1/2`, is `o(sqrt N)`.
-/
theorem chewi128_sqrt_inv_row_tendsto_zero_of_power_bound
    (R : ℕ -> ℝ) {D beta : ℝ}
    (hbeta_lt : beta < (1 : ℝ) / 2)
    (hR_nonneg : ∀ᶠ N in atTop, 0 ≤ R N)
    (hR_bound : ∀ᶠ N in atTop, R N ≤ D * (N : ℝ) ^ beta) :
    Tendsto
      (fun N : ℕ => ‖(Real.sqrt (N : ℝ))⁻¹‖ * R N)
      atTop (𝓝 0) := by
  have hupper :
      Tendsto
        (fun N : ℕ => ‖(Real.sqrt (N : ℝ))⁻¹‖ * (D * (N : ℝ) ^ beta))
        atTop (𝓝 0) :=
    chewi128_sqrt_inv_mul_power_tendsto_zero D beta hbeta_lt
  refine tendsto_of_tendsto_of_tendsto_of_le_of_le' tendsto_const_nhds hupper ?_ ?_
  · filter_upwards [hR_nonneg] with N hRN
    exact mul_nonneg (norm_nonneg _) hRN
  · filter_upwards [hR_bound] with N hRN
    exact mul_le_mul_of_nonneg_left hRN (norm_nonneg _)

/--
Finite power-row estimate for the Chewi 12.8 residual source.  It packages
the existing integral-test bound with the one-based `k + 1` indexing used by
the `zeta` row.
-/
theorem chewi128_sum_range_one_add_rpow_neg_le_power
    {C gamma : ℝ} (hC_nonneg : 0 ≤ C)
    (hgamma_pos : 0 < gamma) (hgamma_lt_one : gamma < 1)
    {N : ℕ} (hN : 1 ≤ N) :
    (∑ k ∈ Finset.range N,
        C * (((k + 1 : ℕ) : ℝ) ^ (-gamma))) ≤
      (C * ((1 + (1 - gamma)⁻¹) * (2 : ℝ) ^ (1 - gamma))) *
        (N : ℝ) ^ (1 - gamma) := by
  let beta : ℝ := 1 - gamma
  have hbeta_pos : 0 < beta := by
    dsimp [beta]
    linarith
  have hbeta_lt : beta < 1 := by
    dsimp [beta]
    linarith
  have hsum_shift :
      (∑ k ∈ Finset.range N,
          (((k + 1 : ℕ) : ℝ) ^ (-gamma))) =
        ∑ j ∈ Finset.Ico 1 (N + 1), (j : ℝ) ^ (-gamma) := by
    rw [Finset.sum_Ico_eq_sum_range]
    have hlen : N + 1 - 1 = N := by omega
    rw [hlen]
    refine Finset.sum_congr rfl ?_
    intro k _hk
    congr 1
    ring_nf
  have houter_raw :=
    chewi125_sum_Ico_rpow_gamma_sub_one_le
      (gamma := beta) hbeta_pos hbeta_lt
      (N := N + 1) (by omega : 1 ≤ N + 1)
  have houter :
      (∑ j ∈ Finset.Ico 1 (N + 1), (j : ℝ) ^ (-gamma)) ≤
        (1 + (1 - gamma)⁻¹) * ((N + 1 : ℕ) : ℝ) ^ (1 - gamma) := by
    simpa [beta, sub_eq_add_neg, add_comm, add_left_comm, add_assoc] using houter_raw
  have hN1_le_twoN : (((N + 1 : ℕ) : ℝ)) ≤ 2 * (N : ℝ) := by
    have hN_real : (1 : ℝ) ≤ (N : ℝ) := by exact_mod_cast hN
    norm_num
    nlinarith
  have hpow_le :
      (((N + 1 : ℕ) : ℝ) ^ (1 - gamma)) ≤
        ((2 : ℝ) ^ (1 - gamma)) * (N : ℝ) ^ (1 - gamma) := by
    have hmono :=
      Real.rpow_le_rpow
        (Nat.cast_nonneg (N + 1)) hN1_le_twoN
        (show 0 ≤ 1 - gamma by linarith)
    have htwo_nonneg : (0 : ℝ) ≤ 2 := by norm_num
    have hN_nonneg : 0 ≤ (N : ℝ) := Nat.cast_nonneg N
    calc
      (((N + 1 : ℕ) : ℝ) ^ (1 - gamma)) ≤
          (2 * (N : ℝ)) ^ (1 - gamma) := hmono
      _ = ((2 : ℝ) ^ (1 - gamma)) * (N : ℝ) ^ (1 - gamma) := by
          rw [Real.mul_rpow htwo_nonneg hN_nonneg]
  have hfactor_nonneg : 0 ≤ 1 + (1 - gamma)⁻¹ := by
    exact add_nonneg zero_le_one (inv_nonneg.mpr (le_of_lt hbeta_pos))
  have hsum_bound :
      (∑ j ∈ Finset.Ico 1 (N + 1), (j : ℝ) ^ (-gamma)) ≤
        (1 + (1 - gamma)⁻¹) *
          (((2 : ℝ) ^ (1 - gamma)) * (N : ℝ) ^ (1 - gamma)) := by
    exact houter.trans
      (mul_le_mul_of_nonneg_left hpow_le hfactor_nonneg)
  calc
    (∑ k ∈ Finset.range N,
        C * (((k + 1 : ℕ) : ℝ) ^ (-gamma)))
        = C * ∑ k ∈ Finset.range N,
            (((k + 1 : ℕ) : ℝ) ^ (-gamma)) := by
          rw [Finset.mul_sum]
    _ = C * ∑ j ∈ Finset.Ico 1 (N + 1), (j : ℝ) ^ (-gamma) := by
          rw [hsum_shift]
    _ ≤ C *
        ((1 + (1 - gamma)⁻¹) *
          (((2 : ℝ) ^ (1 - gamma)) * (N : ℝ) ^ (1 - gamma))) :=
          mul_le_mul_of_nonneg_left hsum_bound hC_nonneg
    _ = (C * ((1 + (1 - gamma)⁻¹) * (2 : ℝ) ^ (1 - gamma))) *
        (N : ℝ) ^ (1 - gamma) := by ring

/--
Closed finite-power row for Chewi's `gamma > 1/2` residual regime.
-/
theorem chewi128_power_source_row_tendsto_zero_of_gamma_gt_half
    (C gamma : ℝ) (hC_nonneg : 0 ≤ C)
    (hgamma_half : (1 : ℝ) / 2 < gamma)
    (hgamma_lt_one : gamma < 1) :
    Tendsto
      (fun N : ℕ =>
        ‖(Real.sqrt (N : ℝ))⁻¹‖ *
          ∑ k ∈ Finset.range N,
            C * (((k + 1 : ℕ) : ℝ) ^ (-gamma)))
      atTop (𝓝 0) := by
  let D : ℝ := C * ((1 + (1 - gamma)⁻¹) * (2 : ℝ) ^ (1 - gamma))
  have hbeta_lt : 1 - gamma < (1 : ℝ) / 2 := by linarith
  refine
    chewi128_sqrt_inv_row_tendsto_zero_of_power_bound
      (fun N : ℕ =>
        ∑ k ∈ Finset.range N,
          C * (((k + 1 : ℕ) : ℝ) ^ (-gamma)))
      (D := D) (beta := 1 - gamma) hbeta_lt ?_ ?_
  · exact Eventually.of_forall fun N =>
      Finset.sum_nonneg fun k _hk =>
        mul_nonneg hC_nonneg
          (Real.rpow_nonneg (Nat.cast_nonneg (k + 1)) (-gamma))
  · refine eventually_atTop.2 ⟨1, ?_⟩
    intro N hN
    simpa [D] using
      chewi128_sum_range_one_add_rpow_neg_le_power
        (C := C) (gamma := gamma) hC_nonneg
        (by linarith : 0 < gamma) hgamma_lt_one hN

/--
Power-rate L1 handoff for Chewi Theorem 12.8.  This isolates the analytic
source estimate `E ||zeta_k|| = O((k+1)^(-gamma))` from the already-proved
uniform-coefficient residual plumbing.
-/
theorem chewi128ASGDZetaContribution_tendstoInMeasure_zero_of_zeta_l1_rate_and_uniform_coeff_bound
    {Ω E : Type*} [MeasurableSpace Ω] {P : Measure Ω}
    [IsFiniteMeasure P]
    [NormedAddCommGroup E] [NormedSpace ℝ E]
    (A Ainv : E →L[ℝ] E) (h : ℕ -> ℝ)
    (zeta : ℕ -> Ω -> E) (K C gamma : ℝ)
    (hK_nonneg : 0 ≤ K)
    (hcoeff_bound : ∀ N k, k ∈ Finset.Ico 1 N ->
      ‖chewi123SourceNoiseCoefficient A h k N - Ainv‖ ≤ K)
    (hzeta_int : ∀ k, Integrable (fun ω => ‖zeta k ω‖) P)
    (hZetaContribution_int :
      ∀ N,
        Integrable
          (fun ω => ‖chewi128ASGDZetaContribution A Ainv h zeta N ω‖) P)
    (hzeta_l1_bound :
      ∀ k, ∫ ω, ‖zeta k ω‖ ∂P ≤
        C * (((k + 1 : ℕ) : ℝ) ^ (-gamma)))
    (hpower_row :
      Tendsto
        (fun N : ℕ =>
          ‖(Real.sqrt (N : ℝ))⁻¹‖ *
            ∑ k ∈ Finset.range N,
              C * (((k + 1 : ℕ) : ℝ) ^ (-gamma)))
        atTop (𝓝 0)) :
    TendstoInMeasure P
      (fun N ω => chewi128ASGDZetaContribution A Ainv h zeta N ω)
      atTop (fun _ => 0) := by
  refine
    chewi128ASGDZetaContribution_tendstoInMeasure_zero_of_source_l1_and_uniform_coeff_bound
      A Ainv h zeta K hK_nonneg hcoeff_bound hzeta_int
      hZetaContribution_int ?_
  refine
    tendsto_of_tendsto_of_tendsto_of_le_of_le'
      tendsto_const_nhds hpower_row ?_ ?_
  · exact Eventually.of_forall fun N =>
      mul_nonneg (norm_nonneg _)
        (Finset.sum_nonneg fun k _hk =>
          integral_nonneg fun ω => norm_nonneg (zeta k ω))
  · exact Eventually.of_forall fun N =>
      mul_le_mul_of_nonneg_left
        (Finset.sum_le_sum fun k _hk => hzeta_l1_bound k)
        (norm_nonneg _)

/--
Power-sum version of the Chewi 12.8 residual handoff.  After Taylor/moment
estimates bound each `E ||zeta_k||` by a power row, it is enough to show that
the corresponding finite sum is eventually `O(N^beta)` for some
`beta < 1/2`.
-/
theorem chewi128ASGDZetaContribution_tendstoInMeasure_zero_of_zeta_l1_rate_and_power_sum_bound
    {Ω E : Type*} [MeasurableSpace Ω] {P : Measure Ω}
    [IsFiniteMeasure P]
    [NormedAddCommGroup E] [NormedSpace ℝ E]
    (A Ainv : E →L[ℝ] E) (h : ℕ -> ℝ)
    (zeta : ℕ -> Ω -> E) (K C D gamma beta : ℝ)
    (hK_nonneg : 0 ≤ K)
    (hC_nonneg : 0 ≤ C)
    (hbeta_lt : beta < (1 : ℝ) / 2)
    (hcoeff_bound : ∀ N k, k ∈ Finset.Ico 1 N ->
      ‖chewi123SourceNoiseCoefficient A h k N - Ainv‖ ≤ K)
    (hzeta_int : ∀ k, Integrable (fun ω => ‖zeta k ω‖) P)
    (hZetaContribution_int :
      ∀ N,
        Integrable
          (fun ω => ‖chewi128ASGDZetaContribution A Ainv h zeta N ω‖) P)
    (hzeta_l1_bound :
      ∀ k, ∫ ω, ‖zeta k ω‖ ∂P ≤
        C * (((k + 1 : ℕ) : ℝ) ^ (-gamma)))
    (hpower_sum_bound :
      ∀ᶠ N in atTop,
        (∑ k ∈ Finset.range N,
            C * (((k + 1 : ℕ) : ℝ) ^ (-gamma))) ≤
          D * (N : ℝ) ^ beta) :
    TendstoInMeasure P
      (fun N ω => chewi128ASGDZetaContribution A Ainv h zeta N ω)
      atTop (fun _ => 0) := by
  have hpower_row :
      Tendsto
        (fun N : ℕ =>
          ‖(Real.sqrt (N : ℝ))⁻¹‖ *
            ∑ k ∈ Finset.range N,
              C * (((k + 1 : ℕ) : ℝ) ^ (-gamma)))
        atTop (𝓝 0) := by
    refine
      chewi128_sqrt_inv_row_tendsto_zero_of_power_bound
        (fun N : ℕ =>
          ∑ k ∈ Finset.range N,
            C * (((k + 1 : ℕ) : ℝ) ^ (-gamma)))
        hbeta_lt ?_ hpower_sum_bound
    exact Eventually.of_forall fun N =>
      Finset.sum_nonneg fun k _hk =>
        mul_nonneg hC_nonneg
          (Real.rpow_nonneg (Nat.cast_nonneg (k + 1)) (-gamma))
  exact
    chewi128ASGDZetaContribution_tendstoInMeasure_zero_of_zeta_l1_rate_and_uniform_coeff_bound
      A Ainv h zeta K C gamma hK_nonneg hcoeff_bound hzeta_int
      hZetaContribution_int hzeta_l1_bound hpower_row

/--
Textbook-shaped Chewi 12.8 residual handoff for the `gamma > 1/2` source
regime: a per-step L1 Taylor-residual rate `E ||zeta_k|| ≤ C (k+1)^(-gamma)`
is enough to make the ASGD `zeta` contribution vanish in measure.
-/
theorem chewi128ASGDZetaContribution_tendstoInMeasure_zero_of_zeta_l1_rate_and_gamma_gt_half
    {Ω E : Type*} [MeasurableSpace Ω] {P : Measure Ω}
    [IsFiniteMeasure P]
    [NormedAddCommGroup E] [NormedSpace ℝ E]
    (A Ainv : E →L[ℝ] E) (h : ℕ -> ℝ)
    (zeta : ℕ -> Ω -> E) (K C gamma : ℝ)
    (hK_nonneg : 0 ≤ K)
    (hC_nonneg : 0 ≤ C)
    (hgamma_half : (1 : ℝ) / 2 < gamma)
    (hgamma_lt_one : gamma < 1)
    (hcoeff_bound : ∀ N k, k ∈ Finset.Ico 1 N ->
      ‖chewi123SourceNoiseCoefficient A h k N - Ainv‖ ≤ K)
    (hzeta_int : ∀ k, Integrable (fun ω => ‖zeta k ω‖) P)
    (hZetaContribution_int :
      ∀ N,
        Integrable
          (fun ω => ‖chewi128ASGDZetaContribution A Ainv h zeta N ω‖) P)
    (hzeta_l1_bound :
      ∀ k, ∫ ω, ‖zeta k ω‖ ∂P ≤
        C * (((k + 1 : ℕ) : ℝ) ^ (-gamma))) :
    TendstoInMeasure P
      (fun N ω => chewi128ASGDZetaContribution A Ainv h zeta N ω)
      atTop (fun _ => 0) := by
  exact
    chewi128ASGDZetaContribution_tendstoInMeasure_zero_of_zeta_l1_rate_and_uniform_coeff_bound
      A Ainv h zeta K C gamma hK_nonneg hcoeff_bound hzeta_int
      hZetaContribution_int hzeta_l1_bound
      (chewi128_power_source_row_tendsto_zero_of_gamma_gt_half
        C gamma hC_nonneg hgamma_half hgamma_lt_one)

/--
L1 source-rate handoff from the pointwise Taylor/Hessian quadratic remainder
bound and Chewi's second-moment rate for the iterate error.
-/
theorem chewi128_zeta_l1_bound_of_pointwise_quadratic_and_moment_rate
    {Ω E : Type*} [MeasurableSpace Ω] {P : Measure Ω}
    [NormedAddCommGroup E] [NormedSpace ℝ E]
    (zeta delta : ℕ -> Ω -> E) (C0 Ctheta gamma : ℝ)
    (hC0_nonneg : 0 ≤ C0)
    (hzeta_int : ∀ k, Integrable (fun ω => ‖zeta k ω‖) P)
    (hdelta_sq_int : ∀ k, Integrable (fun ω => ‖delta k ω‖ ^ (2 : ℕ)) P)
    (hzeta_point :
      ∀ k,
        (fun ω => ‖zeta k ω‖) ≤ᵐ[P]
          fun ω => C0 * ‖delta k ω‖ ^ (2 : ℕ))
    (hmoment_rate :
      ∀ k, ∫ ω, ‖delta k ω‖ ^ (2 : ℕ) ∂P ≤
        Ctheta * (((k + 1 : ℕ) : ℝ) ^ (-gamma)))
    (k : ℕ) :
    ∫ ω, ‖zeta k ω‖ ∂P ≤
      (C0 * Ctheta) * (((k + 1 : ℕ) : ℝ) ^ (-gamma)) := by
  have hdom_int :
      Integrable (fun ω => C0 * ‖delta k ω‖ ^ (2 : ℕ)) P :=
    (hdelta_sq_int k).const_mul C0
  calc
    ∫ ω, ‖zeta k ω‖ ∂P
        ≤ ∫ ω, C0 * ‖delta k ω‖ ^ (2 : ℕ) ∂P :=
          integral_mono_ae (hzeta_int k) hdom_int (hzeta_point k)
    _ = C0 * ∫ ω, ‖delta k ω‖ ^ (2 : ℕ) ∂P := by
          rw [integral_const_mul]
    _ ≤ C0 * (Ctheta * (((k + 1 : ℕ) : ℝ) ^ (-gamma))) :=
          mul_le_mul_of_nonneg_left (hmoment_rate k) hC0_nonneg
    _ = (C0 * Ctheta) * (((k + 1 : ℕ) : ℝ) ^ (-gamma)) := by ring

/--
Chewi 12.8 residual handoff from the Taylor/Hessian quadratic pointwise bound
and the iterate second-moment rate.  This removes the separate
`E ||zeta_k|| <= C (k+1)^(-gamma)` interface when the caller already has the
standard Taylor and moment-rate hypotheses.
-/
theorem chewi128ASGDZetaContribution_tendstoInMeasure_zero_of_pointwise_quadratic_moment_rate_and_gamma_gt_half
    {Ω E : Type*} [MeasurableSpace Ω] {P : Measure Ω}
    [IsFiniteMeasure P]
    [NormedAddCommGroup E] [NormedSpace ℝ E]
    (A Ainv : E →L[ℝ] E) (h : ℕ -> ℝ)
    (zeta delta : ℕ -> Ω -> E) (K C0 Ctheta gamma : ℝ)
    (hK_nonneg : 0 ≤ K)
    (hC0_nonneg : 0 ≤ C0)
    (hCtheta_nonneg : 0 ≤ Ctheta)
    (hgamma_half : (1 : ℝ) / 2 < gamma)
    (hgamma_lt_one : gamma < 1)
    (hcoeff_bound : ∀ N k, k ∈ Finset.Ico 1 N ->
      ‖chewi123SourceNoiseCoefficient A h k N - Ainv‖ ≤ K)
    (hzeta_int : ∀ k, Integrable (fun ω => ‖zeta k ω‖) P)
    (hdelta_sq_int : ∀ k, Integrable (fun ω => ‖delta k ω‖ ^ (2 : ℕ)) P)
    (hZetaContribution_int :
      ∀ N,
        Integrable
          (fun ω => ‖chewi128ASGDZetaContribution A Ainv h zeta N ω‖) P)
    (hzeta_point :
      ∀ k,
        (fun ω => ‖zeta k ω‖) ≤ᵐ[P]
          fun ω => C0 * ‖delta k ω‖ ^ (2 : ℕ))
    (hmoment_rate :
      ∀ k, ∫ ω, ‖delta k ω‖ ^ (2 : ℕ) ∂P ≤
        Ctheta * (((k + 1 : ℕ) : ℝ) ^ (-gamma))) :
    TendstoInMeasure P
      (fun N ω => chewi128ASGDZetaContribution A Ainv h zeta N ω)
      atTop (fun _ => 0) := by
  refine
    chewi128ASGDZetaContribution_tendstoInMeasure_zero_of_zeta_l1_rate_and_gamma_gt_half
      A Ainv h zeta K (C0 * Ctheta) gamma hK_nonneg
      (mul_nonneg hC0_nonneg hCtheta_nonneg)
      hgamma_half hgamma_lt_one hcoeff_bound hzeta_int
      hZetaContribution_int ?_
  intro k
  exact
    chewi128_zeta_l1_bound_of_pointwise_quadratic_and_moment_rate
      zeta delta C0 Ctheta gamma hC0_nonneg hzeta_int hdelta_sq_int
      hzeta_point hmoment_rate k

/--
Endpoint-corrected decomposition for the general ASGD recursion.  The first
remainder is the usual quadratic-ASGD endpoint correction for the martingale
increments, and the second is the deterministic Taylor/Hessian residual
contribution.
-/
theorem chewi128_general_sqrt_average_delta_endpoint_corrected_decomposition_ae
    {Ω E : Type*} [MeasurableSpace Ω] {P : Measure Ω}
    [NormedAddCommGroup E] [NormedSpace ℝ E]
    (A Ainv : E →L[ℝ] E) (h : ℕ -> ℝ)
    (delta xi zeta : ℕ -> Ω -> E)
    (hrec : ∀ n ω,
      delta (n + 1) ω =
        chewi123QuadraticStepMap (h (n + 1)) A (delta n ω) -
          h (n + 1) • (xi (n + 1) ω + zeta n ω))
    (N : ℕ) :
    (fun ω =>
        (-Ainv (chewi127ScaledNoiseSum xi N ω) +
            chewi123ASGDInitialTerm A h (delta 0 ω) N) +
          (chewi123ASGDEndpointCorrectedRemainder A Ainv h
              (fun n => xi n ω) N +
            chewi128ASGDZetaContribution A Ainv h zeta N ω))
      =ᵐ[P]
    (fun ω => chewi123ScaledAverageDelta (fun n => delta n ω) N) := by
  refine ae_of_all _ fun ω => ?_
  let shifted : ℕ -> E := fun n => chewi128ShiftedResidual zeta n ω
  let perturbed : ℕ -> E := fun n => chewi128PerturbedNoise xi zeta n ω
  have hrecPerturbed :
      ∀ n,
        delta (n + 1) ω =
          chewi123QuadraticStepMap (h (n + 1)) A (delta n ω) -
            h (n + 1) • perturbed (n + 1) := by
    intro n
    simpa [perturbed, chewi128PerturbedNoise] using hrec n ω
  have hdecomp :=
    chewi123_quadratic_sqrt_average_delta_endpoint_corrected_decomposition
      A Ainv h (fun n => delta n ω) perturbed hrecPerturbed N
  have hnoise :
      chewi127ScaledNoiseSum (fun n ω => xi n ω + chewi128ShiftedResidual zeta n ω) N ω =
        chewi127ScaledNoiseSum xi N ω +
          chewi127ScaledNoiseSum (chewi128ShiftedResidual zeta) N ω :=
    chewi127ScaledNoiseSum_add xi (chewi128ShiftedResidual zeta) N ω
  have hrem :
      chewi123ASGDEndpointCorrectedRemainder A Ainv h perturbed N =
        chewi123ASGDEndpointCorrectedRemainder A Ainv h (fun n => xi n ω) N +
          chewi123ASGDEndpointCorrectedRemainder A Ainv h shifted N := by
    simpa [perturbed, shifted, chewi128PerturbedNoise] using
      chewi123ASGDEndpointCorrectedRemainder_add
        A Ainv h (fun n => xi n ω) shifted N
  calc
    (-Ainv (chewi127ScaledNoiseSum xi N ω) +
          chewi123ASGDInitialTerm A h (delta 0 ω) N) +
        (chewi123ASGDEndpointCorrectedRemainder A Ainv h
            (fun n => xi n ω) N +
          chewi128ASGDZetaContribution A Ainv h zeta N ω)
        =
      (-Ainv (chewi127ScaledNoiseSum
            (fun n ω => xi n ω + chewi128ShiftedResidual zeta n ω) N ω) +
          chewi123ASGDInitialTerm A h (delta 0 ω) N) +
        chewi123ASGDEndpointCorrectedRemainder A Ainv h perturbed N := by
          rw [hnoise, hrem]
          simp [chewi128ASGDZetaContribution, shifted]
          module
    _ = chewi123ScaledAverageDelta (fun n => delta n ω) N := hdecomp

/--
Chewi Theorem 12.8 source bridge from the general ASGD recursion to the
compiled martingale CLT and quadratic ASGD endpoint.  The remaining analytic
obligation is exactly the residual contribution `zetaContribution = o_P(1)`.
-/
theorem chewi128_asgd_limit_package_of_martingale_certificate_endpoint_corrected
    {Ω Ω' E : Type*} [MeasurableSpace Ω] {P : Measure Ω}
    [IsProbabilityMeasure P] [MeasurableSpace Ω'] {Q : Measure Ω'}
    [IsProbabilityMeasure Q]
    [NormedAddCommGroup E] [NormedSpace ℝ E] [MeasurableSpace E]
    [CompleteSpace E] [SecondCountableTopology E] [BorelSpace E]
    [OpensMeasurableSpace E]
    (C : Chewi127MartingaleCLTCertificate Ω Ω' E P Q)
    (A Ainv : E →L[ℝ] E) (h : ℕ -> ℝ)
    (delta xi zeta : ℕ -> Ω -> E)
    (hrec : ∀ n ω,
      delta (n + 1) ω =
        chewi123QuadraticStepMap (h (n + 1)) A (delta n ω) -
          h (n + 1) • (xi (n + 1) ω + zeta n ω))
    (hInitial : TendstoInMeasure P
      (fun N ω => chewi123ASGDInitialTerm A h (delta 0 ω) N)
      atTop (fun _ => 0))
    (hRemainder : TendstoInMeasure P
      (fun N ω =>
        chewi123ASGDEndpointCorrectedRemainder A Ainv h
          (fun n => xi n ω) N)
      atTop (fun _ => 0))
    (hZeta : TendstoInMeasure P
      (fun N ω => chewi128ASGDZetaContribution A Ainv h zeta N ω)
      atTop (fun _ => 0))
    (hInitial_meas : ∀ N,
      AEMeasurable (fun ω => chewi123ASGDInitialTerm A h (delta 0 ω) N) P)
    (hRemainder_meas : ∀ N,
      AEMeasurable
        (fun ω =>
          chewi123ASGDEndpointCorrectedRemainder A Ainv h
            (fun n => xi n ω) N) P)
    (hZeta_meas : ∀ N,
      AEMeasurable
        (fun ω => chewi128ASGDZetaContribution A Ainv h zeta N ω) P)
    (hNoise_eq : ∀ N, C.noiseScaled N =ᵐ[P] chewi127ScaledNoiseSum xi N) :
    TendstoInDistribution
        (fun N ω => chewi123ScaledAverageDelta (fun n => delta n ω) N)
        atTop (fun ω => -Ainv (C.Z ω)) (fun _ => P) Q ∧
      ProbabilityTheory.HasGaussianLaw (fun ω => -Ainv (C.Z ω)) Q ∧
      ∀ L K : StrongDual ℝ E,
        ProbabilityTheory.covarianceBilinDual
            (Q.map fun ω => -Ainv (C.Z ω)) L K =
          vaart1998_inverseDerivativeCovarianceFunctional (-Ainv)
            (fun L0 K0 =>
              ProbabilityTheory.covarianceBilinDual (Q.map C.Z) L0 K0) L K := by
  let quadraticApprox : ℕ -> Ω -> E := fun N ω =>
    (-Ainv (C.noiseScaled N ω) +
        chewi123ASGDInitialTerm A h (delta 0 ω) N) +
      chewi123ASGDEndpointCorrectedRemainder A Ainv h (fun n => xi n ω) N
  have hquad_package :
      TendstoInDistribution quadraticApprox atTop
          (fun ω => -Ainv (C.Z ω)) (fun _ => P) Q ∧
        ProbabilityTheory.HasGaussianLaw (fun ω => -Ainv (C.Z ω)) Q ∧
        ∀ L K : StrongDual ℝ E,
          ProbabilityTheory.covarianceBilinDual
              (Q.map fun ω => -Ainv (C.Z ω)) L K =
            vaart1998_inverseDerivativeCovarianceFunctional (-Ainv)
              (fun L0 K0 =>
                ProbabilityTheory.covarianceBilinDual (Q.map C.Z) L0 K0) L K := by
    refine
      chewi123_asgd_limit_package_of_martingale_certificate
        (C := C) (Ainv := Ainv)
        (scaledAverage := quadraticApprox)
        (initial := fun N ω => chewi123ASGDInitialTerm A h (delta 0 ω) N)
        (remainder := fun N ω =>
          chewi123ASGDEndpointCorrectedRemainder A Ainv h
            (fun n => xi n ω) N)
        hInitial hRemainder hInitial_meas hRemainder_meas ?_
    intro N
    exact ae_of_all _ fun ω => by simp [quadraticApprox]
  have hwith_zeta :
      TendstoInDistribution
        (fun N ω =>
          quadraticApprox N ω +
            chewi128ASGDZetaContribution A Ainv h zeta N ω)
        atTop (fun ω => -Ainv (C.Z ω)) (fun _ => P) Q := by
    have hmain :=
      hquad_package.1.add_of_tendstoInMeasure_const
        (Y := fun N ω => chewi128ASGDZetaContribution A Ainv h zeta N ω)
        (c := (0 : E)) hZeta hZeta_meas
    simpa using hmain
  refine
    ⟨TendstoInDistribution.congr ?_ (ae_eq_refl _) hwith_zeta,
      hquad_package.2.1, hquad_package.2.2⟩
  intro N
  filter_upwards [hNoise_eq N,
    chewi128_general_sqrt_average_delta_endpoint_corrected_decomposition_ae
      (P := P) A Ainv h delta xi zeta hrec N] with ω hnoise hdecomp
  simpa [quadraticApprox, hnoise, add_assoc] using hdecomp

/--
Source-facing Chewi Theorem 12.8 bridge from the non-circular bounded
martingale CLT core.  All martingale-CLT and quadratic-ASGD endpoint plumbing
is discharged; the remaining theorem-specific analytic assumption is that the
Taylor/Hessian residual contribution is `o_P(1)`.
-/
theorem Chewi127BoundedMartingaleCharFunCLTCore.asgd_general_limit_package_endpoint_corrected
    {Ω Ω' E : Type*} [mΩ : MeasurableSpace Ω] {P : Measure Ω}
    [IsProbabilityMeasure P] [MeasurableSpace Ω'] {Q : Measure Ω'}
    [IsProbabilityMeasure Q]
    [NormedAddCommGroup E] [NormedSpace ℝ E] [MeasurableSpace E]
    [CompleteSpace E] [SecondCountableTopology E] [BorelSpace E]
    [OpensMeasurableSpace E]
    (S : Chewi127BoundedMartingaleCharFunCLTCore Ω Ω' E P Q)
    (A Ainv : E →L[ℝ] E) (h : ℕ -> ℝ)
    (delta zeta : ℕ -> Ω -> E)
    (hrec : ∀ n ω,
      delta (n + 1) ω =
        chewi123QuadraticStepMap (h (n + 1)) A (delta n ω) -
          h (n + 1) • (S.martingale.xi (n + 1) ω + zeta n ω))
    (hInitial : TendstoInMeasure P
      (fun N ω => chewi123ASGDInitialTerm A h (delta 0 ω) N)
      atTop (fun _ => 0))
    (hRemainder : TendstoInMeasure P
      (fun N ω =>
        chewi123ASGDEndpointCorrectedRemainder A Ainv h
          (fun n => S.martingale.xi n ω) N)
      atTop (fun _ => 0))
    (hZeta : TendstoInMeasure P
      (fun N ω => chewi128ASGDZetaContribution A Ainv h zeta N ω)
      atTop (fun _ => 0))
    (hInitial_meas : ∀ N,
      AEMeasurable (fun ω => chewi123ASGDInitialTerm A h (delta 0 ω) N) P)
    (hRemainder_meas : ∀ N,
      AEMeasurable
        (fun ω =>
          chewi123ASGDEndpointCorrectedRemainder A Ainv h
            (fun n => S.martingale.xi n ω) N) P)
    (hZeta_meas : ∀ N,
      AEMeasurable
        (fun ω => chewi128ASGDZetaContribution A Ainv h zeta N ω) P) :
    TendstoInDistribution
        (fun N ω => chewi123ScaledAverageDelta (fun n => delta n ω) N)
        atTop (fun ω => -Ainv (S.Z ω)) (fun _ => P) Q ∧
      ProbabilityTheory.HasGaussianLaw (fun ω => -Ainv (S.Z ω)) Q ∧
      ∀ L K : StrongDual ℝ E,
        ProbabilityTheory.covarianceBilinDual
            (Q.map fun ω => -Ainv (S.Z ω)) L K =
          vaart1998_inverseDerivativeCovarianceFunctional (-Ainv)
            (fun L0 K0 =>
              ProbabilityTheory.covarianceBilinDual (Q.map S.Z) L0 K0) L K := by
  let C : Chewi127MartingaleCLTCertificate Ω Ω' E P Q :=
    S.toMartingaleCLTCertificate_of_uniform_bound_no_factor_bound
  simpa [C,
    Chewi127BoundedMartingaleCharFunCLTCore.toMartingaleCLTCertificate_of_uniform_bound_no_factor_bound,
    Chewi127BoundedMartingaleCharFunCLTSource.toMartingaleCLTCertificate,
    Chewi127BoundedMartingaleCharFunCLTSource.toBoundedMartingaleCLTSource,
    Chewi127BoundedMartingaleCLTSource.toMartingaleCLTCertificate,
    Chewi127BoundedMartingaleCLTSource.toProjectedBridge,
    Chewi127ProjectedMartingaleCLTBridge.toMartingaleCLTCertificate] using
    chewi128_asgd_limit_package_of_martingale_certificate_endpoint_corrected
      (C := C) A Ainv h delta S.martingale.xi zeta hrec
      hInitial hRemainder hZeta hInitial_meas hRemainder_meas hZeta_meas
      (fun _ => ae_of_all _ fun _ => rfl)

end Optimization
end StatInference
