import StatInference.EmpiricalProcess.Average
import StatInference.EmpiricalProcess.EndpointStrongLaw
import StatInference.EmpiricalProcess.L1BracketingNumber

/-!
# VdV&W 2.4.1 current-GC assembly layer

This module adds the endpoint-control assembly layer for the dependency-minimal
route toward van der Vaart and Wellner Theorem 2.4.1.

The declarations here still target the repository's current
`GlivenkoCantelliClass` interface.  They are not the exact textbook theorem:
outer probability, outer almost-sure convergence, and concrete empirical-measure
semantics remain separate primitive layers.
-/

namespace StatInference

open Filter
open scoped Topology

/--
Empirical average of one bracket endpoint over one finite sample.

This is the concrete sample-average semantics that later measure-theoretic
empirical-process code should instantiate from `P_n endpoint`.
-/
noncomputable def bracketEndpointEmpiricalAverage
    {Observation Bracket : Type*} {sampleSize : ℕ}
    (sample : SampleAt Observation sampleSize)
    (endpoint : Bracket -> Observation -> ℝ) (bracket : Bracket) : ℝ :=
  empiricalAverage sample (endpoint bracket)

/-- Unfold the bracket endpoint empirical average to the repository average. -/
theorem bracketEndpointEmpiricalAverage_eq
    {Observation Bracket : Type*} {sampleSize : ℕ}
    (sample : SampleAt Observation sampleSize)
    (endpoint : Bracket -> Observation -> ℝ) (bracket : Bracket) :
    bracketEndpointEmpiricalAverage sample endpoint bracket =
      empiricalAverage sample (endpoint bracket) :=
  rfl

/--
Endpoint empirical averages generated by a deterministic sequence of finite
samples.
-/
noncomputable def bracketEndpointEmpiricalSequence
    {Observation Bracket : Type*}
    (samples : ∀ sampleSize, SampleAt Observation sampleSize)
    (endpoint : Bracket -> Observation -> ℝ) : ℕ -> Bracket -> ℝ :=
  fun sampleSize bracket =>
    bracketEndpointEmpiricalAverage (samples sampleSize) endpoint bracket

/-- Unfold endpoint empirical averages generated by a sample sequence. -/
theorem bracketEndpointEmpiricalSequence_apply
    {Observation Bracket : Type*}
    (samples : ∀ sampleSize, SampleAt Observation sampleSize)
    (endpoint : Bracket -> Observation -> ℝ)
    (sampleSize : ℕ) (bracket : Bracket) :
    bracketEndpointEmpiricalSequence samples endpoint sampleSize bracket =
      empiricalAverage (samples sampleSize) (endpoint bracket) :=
  rfl

/--
Endpoint strong-law assembly data for a selected finite bracketing sequence.

The fields are proof-carrying: endpoint empirical averages are represented by
`lowerEmpirical` and `upperEmpirical`, while the finite endpoint SLLN work is
summarized as absolute endpoint-error bounds with a radius tending to zero.
This is the finite-endpoint handoff needed before constructing
`L1BracketingNumberConstructorObligations`.
-/
structure FiniteBracketEndpointStrongLawAssembly {Index Bracket : Type*}
    [Fintype Bracket] (indexClass : Set Index)
    (populationRisk : Index -> ℝ)
    (empiricalRisk : ℕ -> Index -> ℝ) where
  family :
    ℕ ->
      FiniteL1BracketingFamily (Bracket := Bracket)
        indexClass populationRisk
  lowerEmpirical : ℕ -> Bracket -> ℝ
  upperEmpirical : ℕ -> Bracket -> ℝ
  endpointRadius : ℕ -> ℝ
  empirical_lower :
    ∀ sampleSize index hindex,
      lowerEmpirical sampleSize
          ((family sampleSize).bracketOf index hindex) ≤
        empiricalRisk sampleSize index
  empirical_upper :
    ∀ sampleSize index hindex,
      empiricalRisk sampleSize index ≤
        upperEmpirical sampleSize
          ((family sampleSize).bracketOf index hindex)
  upper_endpoint_abs_bound :
    ∀ sampleSize bracket,
      |upperEmpirical sampleSize bracket -
          (family sampleSize).upperPopulation bracket| ≤
        endpointRadius sampleSize
  lower_endpoint_abs_bound :
    ∀ sampleSize bracket,
      |(family sampleSize).lowerPopulation bracket -
          lowerEmpirical sampleSize bracket| ≤
        endpointRadius sampleSize
  endpoint_tendsto_zero :
    Tendsto endpointRadius atTop (𝓝 0)
  scale_tendsto_zero :
    Tendsto (fun sampleSize => (family sampleSize).scale) atTop (𝓝 0)

namespace FiniteBracketEndpointStrongLawAssembly

/--
Turn finite endpoint absolute-error control into constructor obligations for the
current finite-L1-bracketing GC handoff.
-/
def toConstructorObligations {Index Bracket : Type*} [Fintype Bracket]
    {indexClass : Set Index} {populationRisk : Index -> ℝ}
    {empiricalRisk : ℕ -> Index -> ℝ}
    (assembly :
      FiniteBracketEndpointStrongLawAssembly (Bracket := Bracket)
        indexClass populationRisk empiricalRisk) :
    L1BracketingNumberConstructorObligations (Bracket := Bracket)
      indexClass populationRisk empiricalRisk where
  family := assembly.family
  lowerEmpirical := assembly.lowerEmpirical
  upperEmpirical := assembly.upperEmpirical
  endpointRadius := assembly.endpointRadius
  empirical_lower := assembly.empirical_lower
  empirical_upper := assembly.empirical_upper
  upper_endpoint_bound := by
    intro sampleSize index hindex
    exact
      (abs_le.mp
        (assembly.upper_endpoint_abs_bound sampleSize
          ((assembly.family sampleSize).bracketOf index hindex))).2
  lower_endpoint_bound := by
    intro sampleSize index hindex
    exact
      (abs_le.mp
        (assembly.lower_endpoint_abs_bound sampleSize
          ((assembly.family sampleSize).bracketOf index hindex))).2
  endpoint_tendsto_zero := assembly.endpoint_tendsto_zero
  scale_tendsto_zero := assembly.scale_tendsto_zero

/-- Build the current shrinking finite-bracketing sequence route. -/
def toSequenceRoute {Index Bracket : Type*} [Fintype Bracket]
    {indexClass : Set Index} {populationRisk : Index -> ℝ}
    {empiricalRisk : ℕ -> Index -> ℝ}
    (assembly :
      FiniteBracketEndpointStrongLawAssembly (Bracket := Bracket)
        indexClass populationRisk empiricalRisk) :
    L1BracketingSequenceRoute (Bracket := Bracket)
      indexClass populationRisk empiricalRisk :=
  assembly.toConstructorObligations.toSequenceRoute

/-- Build the current `GlivenkoCantelliClass` interface from endpoint assembly. -/
def toGlivenkoCantelliClass {Index Bracket : Type*} [Fintype Bracket]
    {indexClass : Set Index} {populationRisk : Index -> ℝ}
    {empiricalRisk : ℕ -> Index -> ℝ}
    (assembly :
      FiniteBracketEndpointStrongLawAssembly (Bracket := Bracket)
        indexClass populationRisk empiricalRisk) :
    GlivenkoCantelliClass indexClass populationRisk empiricalRisk :=
  assembly.toConstructorObligations.toGlivenkoCantelliClass

end FiniteBracketEndpointStrongLawAssembly

/--
Concrete sample-average semantics for the finite endpoint assembly layer.

The lower and upper endpoint empirical values are no longer arbitrary fields:
they are generated by `empiricalAverage` over a sequence of finite samples.
The remaining assumptions are the honest proof obligations that still need
measure-theoretic endpoint SLLN and empirical-measure instantiation.
-/
structure FiniteBracketSampleAverageSemantics
    {Observation Index Bracket : Type*} [Fintype Bracket]
    (indexClass : Set Index)
    (populationRisk : Index -> ℝ)
    (empiricalRisk : ℕ -> Index -> ℝ) where
  samples : ∀ sampleSize, SampleAt Observation sampleSize
  family :
    ℕ ->
      FiniteL1BracketingFamily (Bracket := Bracket)
        indexClass populationRisk
  lowerEndpoint : Bracket -> Observation -> ℝ
  upperEndpoint : Bracket -> Observation -> ℝ
  endpointRadius : ℕ -> ℝ
  empirical_lower :
    ∀ sampleSize index hindex,
      bracketEndpointEmpiricalSequence samples lowerEndpoint sampleSize
          ((family sampleSize).bracketOf index hindex) ≤
        empiricalRisk sampleSize index
  empirical_upper :
    ∀ sampleSize index hindex,
      empiricalRisk sampleSize index ≤
        bracketEndpointEmpiricalSequence samples upperEndpoint sampleSize
          ((family sampleSize).bracketOf index hindex)
  upper_endpoint_abs_bound :
    ∀ sampleSize bracket,
      |bracketEndpointEmpiricalSequence samples upperEndpoint sampleSize bracket -
          (family sampleSize).upperPopulation bracket| ≤
        endpointRadius sampleSize
  lower_endpoint_abs_bound :
    ∀ sampleSize bracket,
      |(family sampleSize).lowerPopulation bracket -
          bracketEndpointEmpiricalSequence samples lowerEndpoint sampleSize bracket| ≤
        endpointRadius sampleSize
  endpoint_tendsto_zero :
    Tendsto endpointRadius atTop (𝓝 0)
  scale_tendsto_zero :
    Tendsto (fun sampleSize => (family sampleSize).scale) atTop (𝓝 0)

namespace FiniteBracketSampleAverageSemantics

/--
Forget only the concrete sample-average representation, producing the endpoint
assembly consumed by the current finite-L1-bracketing GC constructor.
-/
noncomputable def toEndpointStrongLawAssembly {Observation Index Bracket : Type*}
    [Fintype Bracket] {indexClass : Set Index}
    {populationRisk : Index -> ℝ} {empiricalRisk : ℕ -> Index -> ℝ}
    (semantics :
      FiniteBracketSampleAverageSemantics (Observation := Observation)
        (Bracket := Bracket) indexClass populationRisk empiricalRisk) :
    FiniteBracketEndpointStrongLawAssembly (Bracket := Bracket)
      indexClass populationRisk empiricalRisk where
  family := semantics.family
  lowerEmpirical :=
    bracketEndpointEmpiricalSequence semantics.samples semantics.lowerEndpoint
  upperEmpirical :=
    bracketEndpointEmpiricalSequence semantics.samples semantics.upperEndpoint
  endpointRadius := semantics.endpointRadius
  empirical_lower := semantics.empirical_lower
  empirical_upper := semantics.empirical_upper
  upper_endpoint_abs_bound := semantics.upper_endpoint_abs_bound
  lower_endpoint_abs_bound := semantics.lower_endpoint_abs_bound
  endpoint_tendsto_zero := semantics.endpoint_tendsto_zero
  scale_tendsto_zero := semantics.scale_tendsto_zero

/-- Build constructor obligations from concrete sample-average semantics. -/
noncomputable def toConstructorObligations {Observation Index Bracket : Type*}
    [Fintype Bracket] {indexClass : Set Index}
    {populationRisk : Index -> ℝ} {empiricalRisk : ℕ -> Index -> ℝ}
    (semantics :
      FiniteBracketSampleAverageSemantics (Observation := Observation)
        (Bracket := Bracket) indexClass populationRisk empiricalRisk) :
    L1BracketingNumberConstructorObligations (Bracket := Bracket)
      indexClass populationRisk empiricalRisk :=
  semantics.toEndpointStrongLawAssembly.toConstructorObligations

/-- Build the current `GlivenkoCantelliClass` from sample-average semantics. -/
noncomputable def toGlivenkoCantelliClass {Observation Index Bracket : Type*}
    [Fintype Bracket] {indexClass : Set Index}
    {populationRisk : Index -> ℝ} {empiricalRisk : ℕ -> Index -> ℝ}
    (semantics :
      FiniteBracketSampleAverageSemantics (Observation := Observation)
        (Bracket := Bracket) indexClass populationRisk empiricalRisk) :
    GlivenkoCantelliClass indexClass populationRisk empiricalRisk :=
  semantics.toEndpointStrongLawAssembly.toGlivenkoCantelliClass

end FiniteBracketSampleAverageSemantics

end StatInference
