import StatInference.EmpiricalProcess.Average
import StatInference.EmpiricalProcess.EndpointStrongLaw
import StatInference.EmpiricalProcess.L1BracketingNumber

/-!
# VdV&W 2.4.1 current-GC assembly layer

This module adds the endpoint-control assembly layer for the dependency-minimal
route toward van der Vaart and Wellner Theorem 2.4.1.

The declarations here still target the repository's current
`GlivenkoCantelliClass` interface.  They are not the exact textbook theorem:
outer probability, outer almost-sure convergence, and concrete empirical-measure
semantics remain separate primitive layers.
-/

namespace StatInference

open MeasureTheory ProbabilityTheory
open Filter
open scoped BigOperators Topology Function

/--
Empirical average of one bracket endpoint over one finite sample.

This is the concrete sample-average semantics that later measure-theoretic
empirical-process code should instantiate from `P_n endpoint`.
-/
noncomputable def bracketEndpointEmpiricalAverage
    {Observation Bracket : Type*} {sampleSize : ℕ}
    (sample : SampleAt Observation sampleSize)
    (endpoint : Bracket -> Observation -> ℝ) (bracket : Bracket) : ℝ :=
  empiricalAverage sample (endpoint bracket)

/-- Unfold the bracket endpoint empirical average to the repository average. -/
theorem bracketEndpointEmpiricalAverage_eq
    {Observation Bracket : Type*} {sampleSize : ℕ}
    (sample : SampleAt Observation sampleSize)
    (endpoint : Bracket -> Observation -> ℝ) (bracket : Bracket) :
    bracketEndpointEmpiricalAverage sample endpoint bracket =
      empiricalAverage sample (endpoint bracket) :=
  rfl

/--
Endpoint empirical averages generated by a deterministic sequence of finite
samples.
-/
noncomputable def bracketEndpointEmpiricalSequence
    {Observation Bracket : Type*}
    (samples : ∀ sampleSize, SampleAt Observation sampleSize)
    (endpoint : Bracket -> Observation -> ℝ) : ℕ -> Bracket -> ℝ :=
  fun sampleSize bracket =>
    bracketEndpointEmpiricalAverage (samples sampleSize) endpoint bracket

/-- Unfold endpoint empirical averages generated by a sample sequence. -/
theorem bracketEndpointEmpiricalSequence_apply
    {Observation Bracket : Type*}
    (samples : ∀ sampleSize, SampleAt Observation sampleSize)
    (endpoint : Bracket -> Observation -> ℝ)
    (sampleSize : ℕ) (bracket : Bracket) :
    bracketEndpointEmpiricalSequence samples endpoint sampleSize bracket =
      empiricalAverage (samples sampleSize) (endpoint bracket) :=
  rfl

/--
View a stochastic observation process `X_i(ω)` as the fixed-size sample seen at
one outcome `ω`.
-/
def stochasticProcessSampleAt {SampleSpace Observation : Type*}
    (observations : ℕ -> SampleSpace -> Observation)
    (ω : SampleSpace) (sampleSize : ℕ) : SampleAt Observation sampleSize :=
  fun sampleIndex => observations sampleIndex ω

/-- The sample sequence induced by a stochastic observation process at `ω`. -/
def stochasticProcessSamples {SampleSpace Observation : Type*}
    (observations : ℕ -> SampleSpace -> Observation)
    (ω : SampleSpace) : ∀ sampleSize, SampleAt Observation sampleSize :=
  fun sampleSize => stochasticProcessSampleAt observations ω sampleSize

/--
Endpoint process induced by composing a bracket endpoint with an observation
process.
-/
def bracketEndpointObservationProcess
    {SampleSpace Observation Bracket : Type*}
    (observations : ℕ -> SampleSpace -> Observation)
    (endpoint : Bracket -> Observation -> ℝ) :
    Bracket -> ℕ -> SampleSpace -> ℝ :=
  fun bracket sampleIndex ω => endpoint bracket (observations sampleIndex ω)

/--
The endpoint empirical sequence induced by a stochastic process is the usual
range-sum average used by the endpoint strong-law wrappers.
-/
theorem bracketEndpointEmpiricalSequence_stochasticProcessSamples_eq_range_sum
    {SampleSpace Observation Bracket : Type*}
    (observations : ℕ -> SampleSpace -> Observation)
    (endpoint : Bracket -> Observation -> ℝ)
    (ω : SampleSpace) (sampleSize : ℕ) (bracket : Bracket) :
    bracketEndpointEmpiricalSequence
        (stochasticProcessSamples observations ω) endpoint sampleSize bracket =
      (∑ sampleIndex ∈ Finset.range sampleSize,
          bracketEndpointObservationProcess observations endpoint bracket
            sampleIndex ω) / sampleSize := by
  unfold bracketEndpointEmpiricalSequence bracketEndpointEmpiricalAverage
    empiricalAverage stochasticProcessSamples stochasticProcessSampleAt
    bracketEndpointObservationProcess
  exact congrArg (fun total : ℝ => total / (sampleSize : ℝ))
    (Fin.sum_univ_eq_sum_range
      (fun sampleIndex => endpoint bracket (observations sampleIndex ω))
      sampleSize)

/--
Endpoint strong law for empirical averages generated by a stochastic process.

This converts the mathlib SLLN range-sum statement into the repository's
`SampleAt`/`bracketEndpointEmpiricalSequence` notation.
-/
theorem finite_endpoint_process_strong_law_eventually_abs_le_real
    {Endpoint Observation SampleSpace : Type*} [Fintype Endpoint]
    [MeasurableSpace SampleSpace] {μ : Measure SampleSpace}
    (observations : ℕ -> SampleSpace -> Observation)
    (endpoint : Endpoint -> Observation -> ℝ)
    (hint :
      ∀ endpointIndex,
        Integrable
          (bracketEndpointObservationProcess observations endpoint
            endpointIndex 0) μ)
    (hindep :
      ∀ endpointIndex,
        Pairwise
          ((· ⟂ᵢ[μ] ·) on
            (bracketEndpointObservationProcess observations endpoint
              endpointIndex)))
    (hident :
      ∀ endpointIndex sampleIndex,
        IdentDistrib
          (bracketEndpointObservationProcess observations endpoint
            endpointIndex sampleIndex)
          (bracketEndpointObservationProcess observations endpoint
            endpointIndex 0) μ μ)
    (tolerance : ℝ) (htolerance : 0 < tolerance) :
    ∀ᵐ ω ∂μ, ∀ᶠ sampleSize : ℕ in atTop, ∀ endpointIndex,
      |bracketEndpointEmpiricalSequence
          (stochasticProcessSamples observations ω) endpoint sampleSize
            endpointIndex -
        μ[bracketEndpointObservationProcess observations endpoint
          endpointIndex 0]| ≤ tolerance := by
  filter_upwards
    [finite_endpoint_strong_law_eventually_abs_le_real
      (bracketEndpointObservationProcess observations endpoint)
      hint hindep hident tolerance htolerance] with ω hω
  exact hω.mono (fun sampleSize hsample endpointIndex => by
    simpa
      [bracketEndpointEmpiricalSequence_stochasticProcessSamples_eq_range_sum]
      using hsample endpointIndex)

/--
Assemble the lower and upper bracket endpoint SLLN events for a stochastic
observation process.

This is still an endpoint event layer: it produces simultaneous finite-bracket
eventual absolute-error bounds, not the final outer almost-sure VdV&W theorem.
-/
theorem finite_bracket_process_endpoints_eventually_abs_le_real
    {Bracket Observation SampleSpace : Type*} [Fintype Bracket]
    [MeasurableSpace SampleSpace] {μ : Measure SampleSpace}
    (observations : ℕ -> SampleSpace -> Observation)
    (lowerEndpoint upperEndpoint : Bracket -> Observation -> ℝ)
    (hint_lower :
      ∀ bracket,
        Integrable
          (bracketEndpointObservationProcess observations lowerEndpoint
            bracket 0) μ)
    (hint_upper :
      ∀ bracket,
        Integrable
          (bracketEndpointObservationProcess observations upperEndpoint
            bracket 0) μ)
    (hindep_lower :
      ∀ bracket,
        Pairwise
          ((· ⟂ᵢ[μ] ·) on
            (bracketEndpointObservationProcess observations lowerEndpoint
              bracket)))
    (hindep_upper :
      ∀ bracket,
        Pairwise
          ((· ⟂ᵢ[μ] ·) on
            (bracketEndpointObservationProcess observations upperEndpoint
              bracket)))
    (hident_lower :
      ∀ bracket sampleIndex,
        IdentDistrib
          (bracketEndpointObservationProcess observations lowerEndpoint
            bracket sampleIndex)
          (bracketEndpointObservationProcess observations lowerEndpoint
            bracket 0) μ μ)
    (hident_upper :
      ∀ bracket sampleIndex,
        IdentDistrib
          (bracketEndpointObservationProcess observations upperEndpoint
            bracket sampleIndex)
          (bracketEndpointObservationProcess observations upperEndpoint
            bracket 0) μ μ)
    (tolerance : ℝ) (htolerance : 0 < tolerance) :
    ∀ᵐ ω ∂μ, ∀ᶠ sampleSize : ℕ in atTop, ∀ bracket,
      |bracketEndpointEmpiricalSequence
          (stochasticProcessSamples observations ω) lowerEndpoint sampleSize
            bracket -
        μ[bracketEndpointObservationProcess observations lowerEndpoint
          bracket 0]| ≤ tolerance ∧
      |bracketEndpointEmpiricalSequence
          (stochasticProcessSamples observations ω) upperEndpoint sampleSize
            bracket -
        μ[bracketEndpointObservationProcess observations upperEndpoint
          bracket 0]| ≤ tolerance := by
  filter_upwards
    [finite_endpoint_process_strong_law_eventually_abs_le_real observations
      lowerEndpoint hint_lower hindep_lower hident_lower tolerance htolerance,
     finite_endpoint_process_strong_law_eventually_abs_le_real observations
      upperEndpoint hint_upper hindep_upper hident_upper tolerance htolerance]
    with ω hLower hUpper
  exact (hLower.and hUpper).mono (fun sampleSize hsample bracket =>
    ⟨hsample.1 bracket, hsample.2 bracket⟩)

/--
Population integral of one bracket endpoint.

This is the measure-backed endpoint counterpart of
`bracketEndpointEmpiricalAverage`.  It records the intended `P endpoint`
semantics before the exact outer-probability theorem is assembled.
-/
noncomputable def bracketEndpointPopulationIntegral
    {Observation Bracket : Type*} [MeasurableSpace Observation]
    (populationMeasure : Measure Observation)
    (endpoint : Bracket -> Observation -> ℝ) (bracket : Bracket) : ℝ :=
  ∫ observation, endpoint bracket observation ∂populationMeasure

/-- Unfold a population endpoint integral to mathlib's integral notation. -/
theorem bracketEndpointPopulationIntegral_eq
    {Observation Bracket : Type*} [MeasurableSpace Observation]
    (populationMeasure : Measure Observation)
    (endpoint : Bracket -> Observation -> ℝ) (bracket : Bracket) :
    bracketEndpointPopulationIntegral populationMeasure endpoint bracket =
      ∫ observation, endpoint bracket observation ∂populationMeasure :=
  rfl

/--
Endpoint empirical values represented by a sequence of empirical measures.

This is the first measure-backed `Pₙ endpoint` interface.  A later layer should
identify these empirical-measure integrals with sample averages for concrete
iid samples.
-/
noncomputable def bracketEndpointEmpiricalMeasureSequence
    {Observation Bracket : Type*} [MeasurableSpace Observation]
    (empiricalMeasure : ℕ -> Measure Observation)
    (endpoint : Bracket -> Observation -> ℝ) : ℕ -> Bracket -> ℝ :=
  fun sampleSize bracket =>
    ∫ observation, endpoint bracket observation ∂empiricalMeasure sampleSize

/-- Unfold endpoint empirical-measure values to mathlib's integral notation. -/
theorem bracketEndpointEmpiricalMeasureSequence_apply
    {Observation Bracket : Type*} [MeasurableSpace Observation]
    (empiricalMeasure : ℕ -> Measure Observation)
    (endpoint : Bracket -> Observation -> ℝ)
    (sampleSize : ℕ) (bracket : Bracket) :
    bracketEndpointEmpiricalMeasureSequence empiricalMeasure endpoint
        sampleSize bracket =
      ∫ observation, endpoint bracket observation ∂empiricalMeasure sampleSize :=
  rfl

/--
Endpoint strong-law assembly data for a selected finite bracketing sequence.

The fields are proof-carrying: endpoint empirical averages are represented by
`lowerEmpirical` and `upperEmpirical`, while the finite endpoint SLLN work is
summarized as absolute endpoint-error bounds with a radius tending to zero.
This is the finite-endpoint handoff needed before constructing
`L1BracketingNumberConstructorObligations`.
-/
structure FiniteBracketEndpointStrongLawAssembly {Index Bracket : Type*}
    [Fintype Bracket] (indexClass : Set Index)
    (populationRisk : Index -> ℝ)
    (empiricalRisk : ℕ -> Index -> ℝ) where
  family :
    ℕ ->
      FiniteL1BracketingFamily (Bracket := Bracket)
        indexClass populationRisk
  lowerEmpirical : ℕ -> Bracket -> ℝ
  upperEmpirical : ℕ -> Bracket -> ℝ
  endpointRadius : ℕ -> ℝ
  empirical_lower :
    ∀ sampleSize index hindex,
      lowerEmpirical sampleSize
          ((family sampleSize).bracketOf index hindex) ≤
        empiricalRisk sampleSize index
  empirical_upper :
    ∀ sampleSize index hindex,
      empiricalRisk sampleSize index ≤
        upperEmpirical sampleSize
          ((family sampleSize).bracketOf index hindex)
  upper_endpoint_abs_bound :
    ∀ sampleSize bracket,
      |upperEmpirical sampleSize bracket -
          (family sampleSize).upperPopulation bracket| ≤
        endpointRadius sampleSize
  lower_endpoint_abs_bound :
    ∀ sampleSize bracket,
      |(family sampleSize).lowerPopulation bracket -
          lowerEmpirical sampleSize bracket| ≤
        endpointRadius sampleSize
  endpoint_tendsto_zero :
    Tendsto endpointRadius atTop (𝓝 0)
  scale_tendsto_zero :
    Tendsto (fun sampleSize => (family sampleSize).scale) atTop (𝓝 0)

namespace FiniteBracketEndpointStrongLawAssembly

/--
Turn finite endpoint absolute-error control into constructor obligations for the
current finite-L1-bracketing GC handoff.
-/
def toConstructorObligations {Index Bracket : Type*} [Fintype Bracket]
    {indexClass : Set Index} {populationRisk : Index -> ℝ}
    {empiricalRisk : ℕ -> Index -> ℝ}
    (assembly :
      FiniteBracketEndpointStrongLawAssembly (Bracket := Bracket)
        indexClass populationRisk empiricalRisk) :
    L1BracketingNumberConstructorObligations (Bracket := Bracket)
      indexClass populationRisk empiricalRisk where
  family := assembly.family
  lowerEmpirical := assembly.lowerEmpirical
  upperEmpirical := assembly.upperEmpirical
  endpointRadius := assembly.endpointRadius
  empirical_lower := assembly.empirical_lower
  empirical_upper := assembly.empirical_upper
  upper_endpoint_bound := by
    intro sampleSize index hindex
    exact
      (abs_le.mp
        (assembly.upper_endpoint_abs_bound sampleSize
          ((assembly.family sampleSize).bracketOf index hindex))).2
  lower_endpoint_bound := by
    intro sampleSize index hindex
    exact
      (abs_le.mp
        (assembly.lower_endpoint_abs_bound sampleSize
          ((assembly.family sampleSize).bracketOf index hindex))).2
  endpoint_tendsto_zero := assembly.endpoint_tendsto_zero
  scale_tendsto_zero := assembly.scale_tendsto_zero

/-- Build the current shrinking finite-bracketing sequence route. -/
def toSequenceRoute {Index Bracket : Type*} [Fintype Bracket]
    {indexClass : Set Index} {populationRisk : Index -> ℝ}
    {empiricalRisk : ℕ -> Index -> ℝ}
    (assembly :
      FiniteBracketEndpointStrongLawAssembly (Bracket := Bracket)
        indexClass populationRisk empiricalRisk) :
    L1BracketingSequenceRoute (Bracket := Bracket)
      indexClass populationRisk empiricalRisk :=
  assembly.toConstructorObligations.toSequenceRoute

/-- Build the current `GlivenkoCantelliClass` interface from endpoint assembly. -/
def toGlivenkoCantelliClass {Index Bracket : Type*} [Fintype Bracket]
    {indexClass : Set Index} {populationRisk : Index -> ℝ}
    {empiricalRisk : ℕ -> Index -> ℝ}
    (assembly :
      FiniteBracketEndpointStrongLawAssembly (Bracket := Bracket)
        indexClass populationRisk empiricalRisk) :
    GlivenkoCantelliClass indexClass populationRisk empiricalRisk :=
  assembly.toConstructorObligations.toGlivenkoCantelliClass

end FiniteBracketEndpointStrongLawAssembly

/--
Concrete sample-average semantics for the finite endpoint assembly layer.

The lower and upper endpoint empirical values are no longer arbitrary fields:
they are generated by `empiricalAverage` over a sequence of finite samples.
The remaining assumptions are the honest proof obligations that still need
measure-theoretic endpoint SLLN and empirical-measure instantiation.
-/
structure FiniteBracketSampleAverageSemantics
    {Observation Index Bracket : Type*} [Fintype Bracket]
    (indexClass : Set Index)
    (populationRisk : Index -> ℝ)
    (empiricalRisk : ℕ -> Index -> ℝ) where
  samples : ∀ sampleSize, SampleAt Observation sampleSize
  family :
    ℕ ->
      FiniteL1BracketingFamily (Bracket := Bracket)
        indexClass populationRisk
  lowerEndpoint : Bracket -> Observation -> ℝ
  upperEndpoint : Bracket -> Observation -> ℝ
  endpointRadius : ℕ -> ℝ
  empirical_lower :
    ∀ sampleSize index hindex,
      bracketEndpointEmpiricalSequence samples lowerEndpoint sampleSize
          ((family sampleSize).bracketOf index hindex) ≤
        empiricalRisk sampleSize index
  empirical_upper :
    ∀ sampleSize index hindex,
      empiricalRisk sampleSize index ≤
        bracketEndpointEmpiricalSequence samples upperEndpoint sampleSize
          ((family sampleSize).bracketOf index hindex)
  upper_endpoint_abs_bound :
    ∀ sampleSize bracket,
      |bracketEndpointEmpiricalSequence samples upperEndpoint sampleSize bracket -
          (family sampleSize).upperPopulation bracket| ≤
        endpointRadius sampleSize
  lower_endpoint_abs_bound :
    ∀ sampleSize bracket,
      |(family sampleSize).lowerPopulation bracket -
          bracketEndpointEmpiricalSequence samples lowerEndpoint sampleSize bracket| ≤
        endpointRadius sampleSize
  endpoint_tendsto_zero :
    Tendsto endpointRadius atTop (𝓝 0)
  scale_tendsto_zero :
    Tendsto (fun sampleSize => (family sampleSize).scale) atTop (𝓝 0)

namespace FiniteBracketSampleAverageSemantics

/--
Forget only the concrete sample-average representation, producing the endpoint
assembly consumed by the current finite-L1-bracketing GC constructor.
-/
noncomputable def toEndpointStrongLawAssembly {Observation Index Bracket : Type*}
    [Fintype Bracket] {indexClass : Set Index}
    {populationRisk : Index -> ℝ} {empiricalRisk : ℕ -> Index -> ℝ}
    (semantics :
      FiniteBracketSampleAverageSemantics (Observation := Observation)
        (Bracket := Bracket) indexClass populationRisk empiricalRisk) :
    FiniteBracketEndpointStrongLawAssembly (Bracket := Bracket)
      indexClass populationRisk empiricalRisk where
  family := semantics.family
  lowerEmpirical :=
    bracketEndpointEmpiricalSequence semantics.samples semantics.lowerEndpoint
  upperEmpirical :=
    bracketEndpointEmpiricalSequence semantics.samples semantics.upperEndpoint
  endpointRadius := semantics.endpointRadius
  empirical_lower := semantics.empirical_lower
  empirical_upper := semantics.empirical_upper
  upper_endpoint_abs_bound := semantics.upper_endpoint_abs_bound
  lower_endpoint_abs_bound := semantics.lower_endpoint_abs_bound
  endpoint_tendsto_zero := semantics.endpoint_tendsto_zero
  scale_tendsto_zero := semantics.scale_tendsto_zero

/-- Build constructor obligations from concrete sample-average semantics. -/
noncomputable def toConstructorObligations {Observation Index Bracket : Type*}
    [Fintype Bracket] {indexClass : Set Index}
    {populationRisk : Index -> ℝ} {empiricalRisk : ℕ -> Index -> ℝ}
    (semantics :
      FiniteBracketSampleAverageSemantics (Observation := Observation)
        (Bracket := Bracket) indexClass populationRisk empiricalRisk) :
    L1BracketingNumberConstructorObligations (Bracket := Bracket)
      indexClass populationRisk empiricalRisk :=
  semantics.toEndpointStrongLawAssembly.toConstructorObligations

/-- Build the current `GlivenkoCantelliClass` from sample-average semantics. -/
noncomputable def toGlivenkoCantelliClass {Observation Index Bracket : Type*}
    [Fintype Bracket] {indexClass : Set Index}
    {populationRisk : Index -> ℝ} {empiricalRisk : ℕ -> Index -> ℝ}
    (semantics :
      FiniteBracketSampleAverageSemantics (Observation := Observation)
        (Bracket := Bracket) indexClass populationRisk empiricalRisk) :
    GlivenkoCantelliClass indexClass populationRisk empiricalRisk :=
  semantics.toEndpointStrongLawAssembly.toGlivenkoCantelliClass

end FiniteBracketSampleAverageSemantics

/--
Measure-backed endpoint semantics for the finite-bracketing route.

Compared with `FiniteBracketSampleAverageSemantics`, the lower and upper
endpoint empirical values are represented as empirical-measure integrals
`Pₙ l` and `Pₙ u`, while the population endpoint fields in the finite bracket
family are tied to `P l` and `P u`.

This remains an interface layer: it does not assert that the empirical measures
come from iid samples, nor does it provide outer almost-sure convergence.
-/
structure FiniteBracketEmpiricalMeasureSemantics
    {Observation Index Bracket : Type*} [MeasurableSpace Observation]
    [Fintype Bracket]
    (indexClass : Set Index)
    (populationRisk : Index -> ℝ)
    (empiricalRisk : ℕ -> Index -> ℝ) where
  populationMeasure : Measure Observation
  empiricalMeasure : ℕ -> Measure Observation
  family :
    ℕ ->
      FiniteL1BracketingFamily (Bracket := Bracket)
        indexClass populationRisk
  lowerEndpoint : Bracket -> Observation -> ℝ
  upperEndpoint : Bracket -> Observation -> ℝ
  endpointRadius : ℕ -> ℝ
  lower_population_eq :
    ∀ sampleSize bracket,
      (family sampleSize).lowerPopulation bracket =
        bracketEndpointPopulationIntegral populationMeasure lowerEndpoint
          bracket
  upper_population_eq :
    ∀ sampleSize bracket,
      (family sampleSize).upperPopulation bracket =
        bracketEndpointPopulationIntegral populationMeasure upperEndpoint
          bracket
  empirical_lower :
    ∀ sampleSize index hindex,
      bracketEndpointEmpiricalMeasureSequence empiricalMeasure lowerEndpoint
          sampleSize ((family sampleSize).bracketOf index hindex) ≤
        empiricalRisk sampleSize index
  empirical_upper :
    ∀ sampleSize index hindex,
      empiricalRisk sampleSize index ≤
        bracketEndpointEmpiricalMeasureSequence empiricalMeasure upperEndpoint
          sampleSize ((family sampleSize).bracketOf index hindex)
  upper_endpoint_abs_bound :
    ∀ sampleSize bracket,
      |bracketEndpointEmpiricalMeasureSequence empiricalMeasure upperEndpoint
          sampleSize bracket -
          bracketEndpointPopulationIntegral populationMeasure upperEndpoint
            bracket| ≤
        endpointRadius sampleSize
  lower_endpoint_abs_bound :
    ∀ sampleSize bracket,
      |bracketEndpointPopulationIntegral populationMeasure lowerEndpoint
          bracket -
          bracketEndpointEmpiricalMeasureSequence empiricalMeasure lowerEndpoint
            sampleSize bracket| ≤
        endpointRadius sampleSize
  endpoint_tendsto_zero :
    Tendsto endpointRadius atTop (𝓝 0)
  scale_tendsto_zero :
    Tendsto (fun sampleSize => (family sampleSize).scale) atTop (𝓝 0)

namespace FiniteBracketEmpiricalMeasureSemantics

/--
Forget the measure-backed endpoint representation, producing the endpoint
assembly consumed by the current finite-L1-bracketing GC constructor.
-/
noncomputable def toEndpointStrongLawAssembly
    {Observation Index Bracket : Type*} [MeasurableSpace Observation]
    [Fintype Bracket] {indexClass : Set Index}
    {populationRisk : Index -> ℝ} {empiricalRisk : ℕ -> Index -> ℝ}
    (semantics :
      FiniteBracketEmpiricalMeasureSemantics (Observation := Observation)
        (Bracket := Bracket) indexClass populationRisk empiricalRisk) :
    FiniteBracketEndpointStrongLawAssembly (Bracket := Bracket)
      indexClass populationRisk empiricalRisk where
  family := semantics.family
  lowerEmpirical :=
    bracketEndpointEmpiricalMeasureSequence semantics.empiricalMeasure
      semantics.lowerEndpoint
  upperEmpirical :=
    bracketEndpointEmpiricalMeasureSequence semantics.empiricalMeasure
      semantics.upperEndpoint
  endpointRadius := semantics.endpointRadius
  empirical_lower := semantics.empirical_lower
  empirical_upper := semantics.empirical_upper
  upper_endpoint_abs_bound := by
    intro sampleSize bracket
    simpa [semantics.upper_population_eq sampleSize bracket]
      using semantics.upper_endpoint_abs_bound sampleSize bracket
  lower_endpoint_abs_bound := by
    intro sampleSize bracket
    simpa [semantics.lower_population_eq sampleSize bracket]
      using semantics.lower_endpoint_abs_bound sampleSize bracket
  endpoint_tendsto_zero := semantics.endpoint_tendsto_zero
  scale_tendsto_zero := semantics.scale_tendsto_zero

/-- Build constructor obligations from empirical-measure endpoint semantics. -/
noncomputable def toConstructorObligations
    {Observation Index Bracket : Type*} [MeasurableSpace Observation]
    [Fintype Bracket] {indexClass : Set Index}
    {populationRisk : Index -> ℝ} {empiricalRisk : ℕ -> Index -> ℝ}
    (semantics :
      FiniteBracketEmpiricalMeasureSemantics (Observation := Observation)
        (Bracket := Bracket) indexClass populationRisk empiricalRisk) :
    L1BracketingNumberConstructorObligations (Bracket := Bracket)
      indexClass populationRisk empiricalRisk :=
  semantics.toEndpointStrongLawAssembly.toConstructorObligations

/-- Build the current `GlivenkoCantelliClass` from empirical-measure semantics. -/
noncomputable def toGlivenkoCantelliClass
    {Observation Index Bracket : Type*} [MeasurableSpace Observation]
    [Fintype Bracket] {indexClass : Set Index}
    {populationRisk : Index -> ℝ} {empiricalRisk : ℕ -> Index -> ℝ}
    (semantics :
      FiniteBracketEmpiricalMeasureSemantics (Observation := Observation)
        (Bracket := Bracket) indexClass populationRisk empiricalRisk) :
    GlivenkoCantelliClass indexClass populationRisk empiricalRisk :=
  semantics.toEndpointStrongLawAssembly.toGlivenkoCantelliClass

end FiniteBracketEmpiricalMeasureSemantics

/--
Concrete bridge from sample-average endpoint semantics to measure-backed
endpoint semantics.

The bridge is proof-carrying: it accepts an empirical-measure sequence only
when its integrals agree with the selected sample averages for every lower and
upper bracket endpoint.  This avoids treating arbitrary measures as empirical
measures while still keeping the exact iid construction as a later primitive.
-/
structure FiniteBracketSampleEmpiricalMeasureSemantics
    {Observation Index Bracket : Type*} [MeasurableSpace Observation]
    [Fintype Bracket]
    (indexClass : Set Index)
    (populationRisk : Index -> ℝ)
    (empiricalRisk : ℕ -> Index -> ℝ) where
  sampleSemantics :
    FiniteBracketSampleAverageSemantics (Observation := Observation)
      (Bracket := Bracket) indexClass populationRisk empiricalRisk
  populationMeasure : Measure Observation
  empiricalMeasure : ℕ -> Measure Observation
  lower_population_eq :
    ∀ sampleSize bracket,
      (sampleSemantics.family sampleSize).lowerPopulation bracket =
        bracketEndpointPopulationIntegral populationMeasure
          sampleSemantics.lowerEndpoint bracket
  upper_population_eq :
    ∀ sampleSize bracket,
      (sampleSemantics.family sampleSize).upperPopulation bracket =
        bracketEndpointPopulationIntegral populationMeasure
          sampleSemantics.upperEndpoint bracket
  lower_empirical_measure_eq_sample_average :
    ∀ sampleSize bracket,
      bracketEndpointEmpiricalMeasureSequence empiricalMeasure
          sampleSemantics.lowerEndpoint sampleSize bracket =
        bracketEndpointEmpiricalSequence sampleSemantics.samples
          sampleSemantics.lowerEndpoint sampleSize bracket
  upper_empirical_measure_eq_sample_average :
    ∀ sampleSize bracket,
      bracketEndpointEmpiricalMeasureSequence empiricalMeasure
          sampleSemantics.upperEndpoint sampleSize bracket =
        bracketEndpointEmpiricalSequence sampleSemantics.samples
          sampleSemantics.upperEndpoint sampleSize bracket

namespace FiniteBracketSampleEmpiricalMeasureSemantics

/--
Promote a proof-carrying sample/empirical-measure bridge to the measure-backed
endpoint semantics used by the current GC constructor.
-/
noncomputable def toEmpiricalMeasureSemantics
    {Observation Index Bracket : Type*} [MeasurableSpace Observation]
    [Fintype Bracket] {indexClass : Set Index}
    {populationRisk : Index -> ℝ} {empiricalRisk : ℕ -> Index -> ℝ}
    (semantics :
      FiniteBracketSampleEmpiricalMeasureSemantics (Observation := Observation)
        (Bracket := Bracket) indexClass populationRisk empiricalRisk) :
    FiniteBracketEmpiricalMeasureSemantics (Observation := Observation)
      (Bracket := Bracket) indexClass populationRisk empiricalRisk where
  populationMeasure := semantics.populationMeasure
  empiricalMeasure := semantics.empiricalMeasure
  family := semantics.sampleSemantics.family
  lowerEndpoint := semantics.sampleSemantics.lowerEndpoint
  upperEndpoint := semantics.sampleSemantics.upperEndpoint
  endpointRadius := semantics.sampleSemantics.endpointRadius
  lower_population_eq := semantics.lower_population_eq
  upper_population_eq := semantics.upper_population_eq
  empirical_lower := by
    intro sampleSize index hindex
    rw [semantics.lower_empirical_measure_eq_sample_average sampleSize
      ((semantics.sampleSemantics.family sampleSize).bracketOf index hindex)]
    exact semantics.sampleSemantics.empirical_lower sampleSize index hindex
  empirical_upper := by
    intro sampleSize index hindex
    rw [semantics.upper_empirical_measure_eq_sample_average sampleSize
      ((semantics.sampleSemantics.family sampleSize).bracketOf index hindex)]
    exact semantics.sampleSemantics.empirical_upper sampleSize index hindex
  upper_endpoint_abs_bound := by
    intro sampleSize bracket
    rw [semantics.upper_empirical_measure_eq_sample_average sampleSize bracket,
      ← semantics.upper_population_eq sampleSize bracket]
    exact semantics.sampleSemantics.upper_endpoint_abs_bound sampleSize bracket
  lower_endpoint_abs_bound := by
    intro sampleSize bracket
    rw [semantics.lower_empirical_measure_eq_sample_average sampleSize bracket,
      ← semantics.lower_population_eq sampleSize bracket]
    exact semantics.sampleSemantics.lower_endpoint_abs_bound sampleSize bracket
  endpoint_tendsto_zero := semantics.sampleSemantics.endpoint_tendsto_zero
  scale_tendsto_zero := semantics.sampleSemantics.scale_tendsto_zero

/-- Build endpoint assembly from the sample/empirical-measure bridge. -/
noncomputable def toEndpointStrongLawAssembly
    {Observation Index Bracket : Type*} [MeasurableSpace Observation]
    [Fintype Bracket] {indexClass : Set Index}
    {populationRisk : Index -> ℝ} {empiricalRisk : ℕ -> Index -> ℝ}
    (semantics :
      FiniteBracketSampleEmpiricalMeasureSemantics (Observation := Observation)
        (Bracket := Bracket) indexClass populationRisk empiricalRisk) :
    FiniteBracketEndpointStrongLawAssembly (Bracket := Bracket)
      indexClass populationRisk empiricalRisk :=
  semantics.toEmpiricalMeasureSemantics.toEndpointStrongLawAssembly

/-- Build constructor obligations from the sample/empirical-measure bridge. -/
noncomputable def toConstructorObligations
    {Observation Index Bracket : Type*} [MeasurableSpace Observation]
    [Fintype Bracket] {indexClass : Set Index}
    {populationRisk : Index -> ℝ} {empiricalRisk : ℕ -> Index -> ℝ}
    (semantics :
      FiniteBracketSampleEmpiricalMeasureSemantics (Observation := Observation)
        (Bracket := Bracket) indexClass populationRisk empiricalRisk) :
    L1BracketingNumberConstructorObligations (Bracket := Bracket)
      indexClass populationRisk empiricalRisk :=
  semantics.toEmpiricalMeasureSemantics.toConstructorObligations

/-- Build the current `GlivenkoCantelliClass` from the bridge. -/
noncomputable def toGlivenkoCantelliClass
    {Observation Index Bracket : Type*} [MeasurableSpace Observation]
    [Fintype Bracket] {indexClass : Set Index}
    {populationRisk : Index -> ℝ} {empiricalRisk : ℕ -> Index -> ℝ}
    (semantics :
      FiniteBracketSampleEmpiricalMeasureSemantics (Observation := Observation)
        (Bracket := Bracket) indexClass populationRisk empiricalRisk) :
    GlivenkoCantelliClass indexClass populationRisk empiricalRisk :=
  semantics.toEmpiricalMeasureSemantics.toGlivenkoCantelliClass

end FiniteBracketSampleEmpiricalMeasureSemantics

end StatInference
